/* AI-CLO PTITHCM — static GitHub Pages client for the existing Supabase schema */
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const cfg=window.AICLO_CONFIG||{};
const db=window.supabase?.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const state={user:null,profile:null,subjects:[],subjectId:localStorage.getItem('aiclo_subject')||'',view:'dashboard'};
const titles={dashboard:['Tổng quan','Theo dõi dữ liệu học phần và hoạt động'],subjects:['Học phần','Quản lý môn học theo năm học và học kỳ'],structure:['Chương · Chủ đề · CLO','Xây dựng cấu trúc nội dung và chuẩn đầu ra'],questions:['Ngân hàng câu hỏi','Biên soạn, duyệt và quản lý câu hỏi'],exams:['Bài kiểm tra','Tạo, phát hành và theo dõi bài kiểm tra theo Chương · Chủ đề · CLO'],results:['Kết quả CLO','Theo dõi kết quả bài làm và mức độ đạt CLO'],users:['Người dùng','Quản lý thành viên và phân quyền học phần']};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const questionCode=id=>`Q-${String(id||'').replaceAll('-','').slice(0,6).toUpperCase()}`;
let mathRenderQueue=Promise.resolve();
function renderMath(container=document.body){if(!container)return;const run=()=>{if(!window.MathJax?.typesetPromise)return;mathRenderQueue=mathRenderQueue.then(()=>{window.MathJax.typesetClear?.([container]);return window.MathJax.typesetPromise([container])}).catch(console.error)};if(window.MathJax?.typesetPromise)run();else window.addEventListener('load',run,{once:true})}
const toast=(m,e=false)=>{const x=$('#toast');x.textContent=m;x.className='toast show'+(e?' error':'');setTimeout(()=>x.className='toast',3000)};
const err=e=>{console.error(e);toast(e?.message||'Có lỗi xảy ra',true)};
const role=()=>state.profile?.role||'student'; const canTeach=()=>['admin','teacher','lecturer','giangvien'].includes(role());
const activeSubject=()=>state.subjects.find(x=>x.id===state.subjectId);
function empty(){return $('#emptyTpl').content.cloneNode(true)}
function modal(title,html){let d=$('#modal');$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;if(!d.open)d.showModal();renderMath($('#modalBody'))}
function closeModal(){ $('#modal').close() }
const drawerStack=[];
function renderDrawerFrame(){let d=$('#sideDrawer'),b=$('#drawerBackdrop'),frame=drawerStack[drawerStack.length-1];if(!frame){d?.classList.add('hidden');b?.classList.add('hidden');d?.setAttribute('aria-hidden','true');b?.setAttribute('aria-hidden','true');document.body.classList.remove('drawer-open');return}d.classList.remove('hidden');b.classList.remove('hidden');d.setAttribute('aria-hidden','false');b.setAttribute('aria-hidden','false');document.body.classList.add('drawer-open');$('#drawerTitle').textContent=frame.title||'Chi tiết';$('#drawerEyebrow').textContent=frame.eyebrow||'CHI TIẾT';$('#drawerBody').innerHTML=frame.html||'';$('#drawerBack').classList.toggle('hidden',drawerStack.length<2);d.classList.toggle('wide',!!frame.wide);d.classList.remove('expanded');frame.bind?.($('#drawerBody'));renderMath($('#drawerBody'))}
function openDrawer(title,html,bind=null,opts={}){drawerStack.length=0;drawerStack.push({title,html,bind,...opts});renderDrawerFrame()}
function pushDrawer(title,html,bind=null,opts={}){drawerStack.push({title,html,bind,...opts});renderDrawerFrame()}
function replaceDrawer(title,html,bind=null,opts={}){if(drawerStack.length)drawerStack[drawerStack.length-1]={title,html,bind,...opts};else drawerStack.push({title,html,bind,...opts});renderDrawerFrame()}
function backDrawer(){if(drawerStack.length>1){drawerStack.pop();renderDrawerFrame()}else closeDrawer()}
function closeDrawer(){drawerStack.length=0;renderDrawerFrame()}
function confirmAction(title,message,{confirmLabel='Xác nhận',danger=false}={}){return new Promise(resolve=>{let d=$('#confirmDialog'),ok=$('#confirmOk'),cancel=$('#confirmCancel');$('#confirmTitle').textContent=title||'Xác nhận thao tác';$('#confirmMessage').textContent=message||'';ok.textContent=confirmLabel;ok.className=danger?'danger':'primary';let finish=v=>{ok.onclick=null;cancel.onclick=null;d.oncancel=null;if(d.open)d.close();resolve(v)};ok.onclick=()=>finish(true);cancel.onclick=()=>finish(false);d.oncancel=e=>{e.preventDefault();finish(false)};if(!d.open)d.showModal()})}
async function q(table,select='*',build=x=>x){let r=await build(db.from(table).select(select));if(r.error)throw r.error;return r.data||[]}

document.addEventListener('DOMContentLoaded',init);
async function init(){
 if(!db){return err('Không tải được thư viện Supabase. Hãy kiểm tra kết nối mạng.')}
 $('#loginForm').onsubmit=login; $('#logoutBtn').onclick=async()=>{await window.logActivity?.('logout','session',null,'Đăng xuất hệ thống');await db.auth.signOut()}; $('#resetBtn').onclick=resetPassword;
 setTimeout(()=>$('#email')?.focus(),50);
 $('#drawerClose').onclick=closeDrawer;$('#drawerBack').onclick=backDrawer;$('#drawerExpand').onclick=()=>$('#sideDrawer').classList.toggle('expanded');$('#drawerBackdrop').onclick=closeDrawer;
 $('#menuBtn').onclick=()=>$('aside').classList.toggle('open'); $('#subjectSelect').onchange=e=>{state.subjectId=e.target.value;localStorage.setItem('aiclo_subject',state.subjectId);render()};
 $('#nav').onclick=e=>{let b=e.target.closest('[data-view]');if(b)navigate(b.dataset.view)};
 db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')return showAuth();if(!session?.user)return;if(event==='SIGNED_IN'||event==='INITIAL_SESSION'||!state.user)boot(session.user);else state.user=session.user});
 const {data}=await db.auth.getSession(); data.session?.user?boot(data.session.user):showAuth();
}
function showAuth(){closeDrawer();document.body.classList.add('login-active');$('#auth').classList.remove('hidden');$('#app').classList.add('hidden');state.user=null;state.profile=null;setTimeout(()=>$('#email')?.focus(),50)}
function enterApp(){if(!state.user||!state.profile)return showAuth();document.body.classList.remove('login-active');$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');fillSubjectSelect();navigate(state.view)}
async function login(e){e.preventDefault();let {error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)err(error);else toast('Đăng nhập thành công')}
async function resetPassword(){let email=$('#email').value.trim();if(!email)return toast('Nhập email trước khi yêu cầu đặt lại mật khẩu',true);let {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});error?err(error):toast('Đã gửi email đặt lại mật khẩu')}
async function boot(user){
 try{state.user=user;let {data,error}=await db.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;state.profile=data;
   state.subjects=await q('subjects','*',x=>x.order('academic_year',{ascending:false}).order('name'));
   if(!state.subjects.some(s=>s.id===state.subjectId))state.subjectId=state.subjects[0]?.id||'';
   $('#miniUser').innerHTML=`<b>${esc(data.full_name)}</b><br>${esc(data.email)} · ${esc(data.role)}`;
   if(window.logActivity)window.logActivity('login','session',null,'Đăng nhập hệ thống','success',null,{source:'web'});
   $$('[data-admin]').forEach(x=>x.hidden=role()!=='admin');$$('[data-staff]').forEach(x=>x.hidden=!['admin','teacher','lecturer','giangvien'].includes(role()));$('#usersNavLabel').textContent=role()==='admin'?'Người dùng':'Danh sách lớp';fillSubjectSelect();enterApp();
 }catch(e){err(e)}
}
function fillSubjectSelect(){let s=$('#subjectSelect');s.innerHTML=state.subjects.length?state.subjects.map(x=>`<option value="${x.id}" ${x.id===state.subjectId?'selected':''}>${esc(x.name)} · ${esc(x.semester)}</option>`).join(''):'<option value="">Chưa có học phần</option>'}
function navigate(v){closeDrawer();if(v==='users'&&!['admin','teacher','lecturer','giangvien'].includes(role()))v='dashboard';state.view=v;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('aside').classList.remove('open');let [t,s]=titles[v];if(v==='users'&&role()!=='admin'){t='Danh sách lớp';s='Sinh viên thuộc học phần hiện tại'}$('#pageTitle').textContent=t;$('#pageSub').textContent=s;render()}
async function render(){let c=$('#content');c.innerHTML='<div class="panel">Đang tải dữ liệu…</div>';try{await ({dashboard,subjects,structure,questions,exams,results,users}[state.view]||dashboard)(c)}catch(e){c.innerHTML=`<div class="panel"><b>Không thể tải dữ liệu</b><p>${esc(e.message)}</p></div>`;err(e)}}

async function dashboard(c){
 let sid=state.subjectId;let [chapters,clos,questions,exams]=sid?await Promise.all([q('chapters','id',x=>x.eq('subject_id',sid)),q('clos','id',x=>x.eq('subject_id',sid)),q('questions','id,status',x=>x.eq('subject_id',sid)),q('exams','id,status',x=>x.eq('subject_id',sid))]):[[],[],[],[]];
 c.innerHTML=`<div class="stats"><div class="stat"><small>Học phần được truy cập</small><b>${state.subjects.length}</b></div><div class="stat"><small>Câu hỏi</small><i>?</i><b>${questions.length}</b></div><div class="stat"><small>CLO</small><i>◎</i><b>${clos.length}</b></div><div class="stat"><small>Đề thi</small><i>✎</i><b>${exams.length}</b></div></div><div class="grid2"><section class="panel"><div class="panel-head"><h3>Tiến độ học phần</h3></div>${metric('Cấu trúc chương',chapters.length,Math.min(100,chapters.length*20))}${metric('Ngân hàng câu hỏi',questions.length,Math.min(100,questions.length*2))}${metric('Đề thi đã tạo',exams.length,Math.min(100,exams.length*20))}</section><section class="panel"><div class="panel-head"><h3>Học phần hiện tại</h3></div>${activeSubject()?`<h2>${esc(activeSubject().name)}</h2><p>${esc(activeSubject().semester)} · ${esc(activeSubject().academic_year)}</p><p><span class="badge green">${questions.filter(x=>x.status==='active').length} câu đang hoạt động</span></p>`:'<p>Quản trị viên cần tạo học phần và thêm bạn vào học phần.</p>'}</section></div>`;
}
const metric=(name,n,p)=>`<p><b>${esc(name)}</b><span style="float:right">${n}</span></p><div class="bar"><span style="width:${p}%"></span></div>`;

async function subjects(c){
 c.innerHTML=`<div class="toolbar"><input id="search" placeholder="Tìm học phần…"><button class="primary" id="addSubject" ${role()!=='admin'?'hidden':''}>+ Tạo học phần</button></div><div class="panel table-wrap"><table><thead><tr><th>Học phần</th><th>Học kỳ</th><th>Năm học</th><th>Vai trò</th><th></th></tr></thead><tbody id="rows"></tbody></table></div>`;
 const draw=(list=state.subjects)=>$('#rows').innerHTML=list.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.semester)}</td><td>${esc(s.academic_year)}</td><td><span class="badge">${role()==='admin'?'Quản trị':'Thành viên'}</span></td><td class="row-actions"><button data-open="${s.id}">Mở</button>${role()==='admin'?`<button data-edit="${s.id}">Sửa</button><button data-del="${s.id}">Xóa</button>`:''}</td></tr>`).join('');draw();
 $('#search').oninput=e=>draw(state.subjects.filter(s=>s.name.toLowerCase().includes(e.target.value.toLowerCase())));$('#addSubject')?.addEventListener('click',()=>subjectForm());
 $('#rows').onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.open){state.subjectId=b.dataset.open;fillSubjectSelect();navigate('dashboard')}if(b.dataset.edit)subjectForm(state.subjects.find(x=>x.id===b.dataset.edit));if(b.dataset.del)remove('subjects',b.dataset.del,'học phần')};
}
function subjectForm(s={}){modal(s.id?'Sửa học phần':'Tạo học phần',`<form id="subjectForm" class="form-grid"><label class="field wide">Tên học phần<input name="name" required value="${esc(s.name)}"></label><label class="field">Học kỳ<input name="semester" required value="${esc(s.semester||'Học kỳ 1')}"></label><label class="field">Năm học<input name="academic_year" required value="${esc(s.academic_year||'2026-2027')}"></label><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary">Lưu</button></div></form>`);$('#subjectForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));let r=s.id?await db.from('subjects').update(v).eq('id',s.id):await db.from('subjects').insert(v);if(r.error)return err(r.error);closeModal();toast('Đã lưu học phần');await boot(state.user)}}

async function structure(c){
 if(!state.subjectId){c.replaceChildren(empty());return}
 let [ch,topics,clos]=await Promise.all([
   q('chapters','*',x=>x.eq('subject_id',state.subjectId).order('order_index')),
   q('topics','*',x=>x.order('order_index')),
   q('clos','*',x=>x.eq('subject_id',state.subjectId).order('code'))
 ]);
 let relevantTopics=topics.filter(t=>ch.some(x=>x.id===t.chapter_id));
 c.innerHTML=`<div class="grid2"><section class="panel"><div class="panel-head"><h3>Chương và chủ đề</h3>${canTeach()?'<button id="addChapter" class="primary">+ Chương</button>':''}</div><div id="chapterList" class="structure-list">${ch.map(x=>{let ts=relevantTopics.filter(t=>t.chapter_id===x.id);return `<div class="structure-chapter"><div class="structure-chapter-head"><div><b>${esc(x.order_index)}. ${esc(x.name)}</b><small>${ts.length} chủ đề</small></div>${canTeach()?`<div class="structure-actions"><button data-topic="${x.id}">+ Chủ đề</button><button data-edit-chapter="${x.id}">Sửa</button><button class="danger-link" data-delete-chapter="${x.id}">Xóa</button></div>`:''}</div><div class="topic-list">${ts.map(t=>`<div class="topic-row"><span><span class="badge">${esc(t.order_index)}. ${esc(t.name)}</span></span>${canTeach()?`<span class="topic-actions"><button data-edit-topic="${t.id}">Sửa</button><button class="danger-link" data-delete-topic="${t.id}">Xóa</button></span>`:''}</div>`).join('')||'<small>Chưa có chủ đề</small>'}</div></div>`}).join('')||'<p>Chưa có chương.</p>'}</div></section><section class="panel"><div class="panel-head"><h3>Chuẩn đầu ra CLO</h3>${role()==='admin'?'<button id="addClo" class="primary">+ CLO</button>':''}</div><div id="cloList">${clos.map(x=>`<div style="padding:12px 0;border-bottom:1px solid var(--line)"><span class="badge red">${esc(x.code)}</span> ${esc(x.description)}${role()==='admin'?`<button class="danger-link" data-delete-clo="${x.id}" style="float:right">Xóa</button>`:''}</div>`).join('')||'<p>Chưa có CLO.</p>'}</div></section></div>`;
 $('#addChapter')?.addEventListener('click',()=>chapterForm(null,ch));
 $('#addClo')?.addEventListener('click',()=>simpleForm('Tạo CLO',[['code','Mã CLO'],['description','Mô tả']],async v=>db.from('clos').insert({...v,subject_id:state.subjectId})));
 $('#chapterList').onclick=e=>{
   let b=e.target.closest('button');if(!b)return;
   if(b.dataset.topic)return topicForm(b.dataset.topic,null,relevantTopics);
   if(b.dataset.editChapter)return chapterForm(ch.find(x=>x.id===b.dataset.editChapter),ch);
   if(b.dataset.deleteChapter)return deleteChapter(ch.find(x=>x.id===b.dataset.deleteChapter));
   if(b.dataset.editTopic)return topicForm(relevantTopics.find(x=>x.id===b.dataset.editTopic)?.chapter_id,relevantTopics.find(x=>x.id===b.dataset.editTopic),relevantTopics);
   if(b.dataset.deleteTopic)return deleteTopic(relevantTopics.find(x=>x.id===b.dataset.deleteTopic));
 };
 $('#cloList')?.addEventListener('click',async e=>{let b=e.target.closest('[data-delete-clo]');if(!b)return;let x=clos.find(v=>v.id===b.dataset.deleteClo);try{let [questions,examClos,pool]=await Promise.all([dependencyCount('questions','clo_id',x.id),dependencyCount('exam_clos','clo_id',x.id),dependencyCount('exam_question_pool','clo_id',x.id)]);if(questions||examClos||pool)return modal('Không thể xóa CLO',`<p>CLO <b>${esc(x.code)}</b> đang được sử dụng (${questions} câu hỏi, ${examClos} cấu hình đề, ${pool} câu trong pool).</p><p class="hint">Hãy xử lý các dữ liệu liên quan trước.</p>`);if(!await confirmAction('Xóa CLO',`Xóa ${x.code}?`,{confirmLabel:'Xóa',danger:true}))return;let {error}=await db.from('clos').delete().eq('id',x.id);if(error)throw error;window.logActivity?.('delete','clo',x.id,`Xóa ${x.code}`);toast('Đã xóa CLO');render()}catch(ex){err(ex)}});
}
function chapterForm(x=null,chapters=[]){
 x=x||{};let nextOrder=x.id?x.order_index:(Math.max(0,...chapters.map(v=>+v.order_index||0))+1);
 modal(x.id?'Sửa chương':'Tạo chương',`<form id="chapterForm" class="form-grid"><label class="field wide">Tên chương<input name="name" required value="${esc(x.name||'')}"></label><label class="field wide">Thứ tự<input name="order_index" type="number" min="0" required value="${esc(nextOrder)}"></label><p class="hint wide">Có thể đổi tên và thứ tự chương. Các câu hỏi đang gắn với chương vẫn được giữ nguyên.</p><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary">Lưu</button></div></form>`);
 $('#chapterForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));v.order_index=+v.order_index;let r=x.id?await db.from('chapters').update(v).eq('id',x.id):await db.from('chapters').insert({...v,subject_id:state.subjectId});if(r.error)return err(r.error);closeModal();toast(x.id?'Đã cập nhật chương':'Đã thêm chương');render()};
}
function topicForm(chapterId,x=null,topics=[]){
 x=x||{};let sameChapter=topics.filter(t=>t.chapter_id===chapterId),nextOrder=x.id?x.order_index:(Math.max(0,...sameChapter.map(v=>+v.order_index||0))+1);
 modal(x.id?'Sửa chủ đề':'Tạo chủ đề',`<form id="topicForm" class="form-grid"><label class="field wide">Tên chủ đề<input name="name" required value="${esc(x.name||'')}"></label><label class="field wide">Thứ tự<input name="order_index" type="number" min="0" required value="${esc(nextOrder)}"></label><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary">Lưu</button></div></form>`);
 $('#topicForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));v.order_index=+v.order_index;let r=x.id?await db.from('topics').update(v).eq('id',x.id):await db.from('topics').insert({...v,chapter_id:chapterId});if(r.error)return err(r.error);closeModal();toast(x.id?'Đã cập nhật chủ đề':'Đã thêm chủ đề');render()};
}
async function dependencyCount(table,column,id){let {count,error}=await db.from(table).select('id',{count:'exact',head:true}).eq(column,id);if(error)throw error;return count||0}
async function deleteChapter(x){
 if(!x)return;
 try{let [topicCount,questionCount,examCount]=await Promise.all([dependencyCount('topics','chapter_id',x.id),dependencyCount('questions','chapter_id',x.id),dependencyCount('exam_chapters','chapter_id',x.id)]);
   if(topicCount||questionCount||examCount){modal('Không thể xóa chương',`<div class="safe-delete"><p><b>${esc(x.name)}</b> đang được sử dụng nên hệ thống không xóa để tránh mất dữ liệu.</p><div class="dependency-list"><span><b>${topicCount}</b> chủ đề</span><span><b>${questionCount}</b> câu hỏi</span><span><b>${examCount}</b> cấu hình đề thi</span></div><p class="hint">Bạn vẫn có thể đổi tên hoặc đổi thứ tự chương. Muốn xóa, cần xử lý các dữ liệu đang liên kết trước.</p><div class="form-actions"><button class="primary" type="button" onclick="document.querySelector('#modal').close()">Đã hiểu</button></div></div>`);return}
   if(!await confirmAction('Xóa chương',`Xóa chương “${x.name}”? Dữ liệu liên quan có thể khiến thao tác bị từ chối.`,{confirmLabel:'Xóa',danger:true}))return;let {error}=await db.from('chapters').delete().eq('id',x.id);if(error)throw error;toast('Đã xóa chương');render();
 }catch(ex){err(ex)}
}
async function deleteTopic(x){
 if(!x)return;
 try{let questionCount=await dependencyCount('questions','topic_id',x.id);if(questionCount){modal('Không thể xóa chủ đề',`<div class="safe-delete"><p><b>${esc(x.name)}</b> đang có <b>${questionCount}</b> câu hỏi liên kết.</p><p class="hint">Để bảo vệ ngân hàng câu hỏi, hãy chuyển hoặc xóa các câu hỏi liên quan trước khi xóa chủ đề.</p><div class="form-actions"><button class="primary" type="button" onclick="document.querySelector('#modal').close()">Đã hiểu</button></div></div>`);return}
   if(!await confirmAction('Xóa chủ đề',`Xóa chủ đề “${x.name}”? Dữ liệu liên quan có thể khiến thao tác bị từ chối.`,{confirmLabel:'Xóa',danger:true}))return;let {error}=await db.from('topics').delete().eq('id',x.id);if(error)throw error;toast('Đã xóa chủ đề');render();
 }catch(ex){err(ex)}
}
function simpleForm(title,fields,save){modal(title,`<form id="simpleForm" class="form-grid">${fields.map(f=>`<label class="field wide">${f[1]}<input name="${f[0]}" type="${f[2]||'text'}" required></label>`).join('')}<div class="form-actions"><button class="primary">Lưu</button></div></form>`);$('#simpleForm').onsubmit=async e=>{e.preventDefault();let r=await save(Object.fromEntries(new FormData(e.target)));if(r.error)return err(r.error);closeModal();toast('Đã lưu');render()}}

async function questions(c){
 if(!canTeach()){c.innerHTML='<div class="panel">Sinh viên không được truy cập ngân hàng câu hỏi.</div>';return}if(!state.subjectId){c.replaceChildren(empty());return}let [items,ch,topics,clos]=await Promise.all([q('questions','*, question_options(*)',x=>x.eq('subject_id',state.subjectId).order('created_at',{ascending:false})),q('chapters','*',x=>x.eq('subject_id',state.subjectId).order('order_index')),q('topics'),q('clos','*',x=>x.eq('subject_id',state.subjectId).order('code'))]);let relevantTopics=topics.filter(t=>ch.some(x=>x.id===t.chapter_id));
 c.innerHTML=`<div class="question-tools"><input id="qsearch" placeholder="Tìm theo mã hoặc nội dung…"><select id="qchapterFilter"><option value="all">Tất cả chương</option>${ch.map(x=>`<option value="${x.id}">${esc(x.order_index)}. ${esc(x.name)}</option>`).join('')}</select><select id="qtopicFilter"><option value="all">Tất cả chủ đề</option>${relevantTopics.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><select id="qcloFilter"><option value="all">Tất cả CLO</option>${clos.map(x=>`<option value="${x.id}">${esc(x.code)}</option>`).join('')}</select><select id="qstatusFilter"><option value="all">Tất cả trạng thái</option><option value="active">Đang dùng</option><option value="draft">Bản nháp</option></select></div><div class="toolbar bank-actions"><span id="questionCount" class="hint"></span><button id="aiHistory" class="secondary">Phiên AI</button><button id="generateAI" class="ai-btn">✦ Tạo bằng Gemini</button><button id="addQ" class="primary">+ Thêm câu hỏi</button></div><div class="panel table-wrap question-table"><table><thead><tr><th>Mã câu</th><th>Nội dung</th><th>CLO</th><th>Chương · Chủ đề</th><th>Trạng thái</th><th></th></tr></thead><tbody id="qrows"></tbody></table></div>`;
 const fillTopicFilter=()=>{let chapterId=$('#qchapterFilter').value,allowed=chapterId==='all'?relevantTopics:relevantTopics.filter(t=>t.chapter_id===chapterId),old=$('#qtopicFilter').value;$('#qtopicFilter').innerHTML='<option value="all">Tất cả chủ đề</option>'+allowed.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(allowed.some(x=>x.id===old))$('#qtopicFilter').value=old};
 const draw=()=>{let search=$('#qsearch').value.trim().toLowerCase(),chapterId=$('#qchapterFilter').value,topicId=$('#qtopicFilter').value,cloId=$('#qcloFilter').value,status=$('#qstatusFilter').value,list=items.filter(x=>(!search||x.content.toLowerCase().includes(search)||questionCode(x.id).toLowerCase().includes(search))&&(chapterId==='all'||x.chapter_id===chapterId)&&(topicId==='all'||x.topic_id===topicId)&&(cloId==='all'||x.clo_id===cloId)&&(status==='all'||x.status===status));$('#questionCount').textContent=`Hiển thị ${list.length}/${items.length} câu`;let rows=$('#qrows');rows.innerHTML=list.map(x=>{let chapter=ch.find(z=>z.id===x.chapter_id),topic=relevantTopics.find(z=>z.id===x.topic_id);return `<tr><td><button class="question-code" data-detail="${x.id}">${questionCode(x.id)}</button></td><td><button class="question-summary" data-detail="${x.id}">${esc(x.content)}</button></td><td><span class="badge red">${esc(clos.find(z=>z.id===x.clo_id)?.code||'—')}</span></td><td>${esc(chapter?.name||'—')}<br><small>${esc(topic?.name||'—')}</small></td><td><span class="badge ${x.status==='active'?'green':''}">${x.status==='active'?'Đang dùng':'Bản nháp'}</span></td><td class="row-actions"><button data-detail="${x.id}">Chi tiết</button><button data-edit="${x.id}">Sửa</button><button data-del="${x.id}">Xóa</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">Không có câu hỏi phù hợp.</td></tr>';renderMath(rows)};fillTopicFilter();draw();
 $('#qsearch').oninput=draw;$('#qchapterFilter').onchange=()=>{fillTopicFilter();draw()};$('#qtopicFilter').onchange=draw;$('#qcloFilter').onchange=draw;$('#qstatusFilter').onchange=draw;$('#addQ').onclick=()=>questionForm(null,{ch,topics:relevantTopics,clos});$('#generateAI').onclick=()=>aiGenerateForm({ch,topics:relevantTopics,clos});$('#aiHistory').onclick=aiHistory;$('#qrows').onclick=e=>{let b=e.target.closest('button');if(!b)return;let item=items.find(x=>x.id===(b.dataset.detail||b.dataset.edit||b.dataset.del));if(b.dataset.detail)questionDetail(item,{ch,topics:relevantTopics,clos});if(b.dataset.edit)questionForm(item,{ch,topics:relevantTopics,clos});if(b.dataset.del)removeQuestion(item.id)};
}
function questionDetail(x,sets){let opts=Object.fromEntries((x.question_options||[]).map(o=>[o.option_key,o.content])),chapter=sets.ch.find(v=>v.id===x.chapter_id),topic=sets.topics.find(v=>v.id===x.topic_id),clo=sets.clos.find(v=>v.id===x.clo_id);modal(`${questionCode(x.id)} · Chi tiết câu hỏi`,`<div class="question-detail"><div class="detail-meta"><span class="badge red">${esc(clo?.code||'—')}</span><span class="badge">${esc(chapter?.name||'—')}</span><span class="badge">${esc(topic?.name||'—')}</span><span class="badge ${x.status==='active'?'green':''}">${x.status==='active'?'Đang dùng':'Bản nháp'}</span></div><div class="detail-question">${esc(x.content)}</div><div class="detail-options">${['A','B','C','D'].map(k=>`<div class="${x.correct_answer===k?'correct':''}"><b>${k}</b><span>${esc(opts[k]||'')}</span></div>`).join('')}</div><div class="detail-explanation"><b>Lời giải</b><p>${esc(x.explanation||'Chưa có lời giải.')}</p></div><div class="account-actions"><button id="detailEditQuestion" class="primary">Sửa câu hỏi</button></div></div>`);$('#detailEditQuestion').onclick=()=>questionForm(x,sets)}
function questionForm(x={},sets){x=x||{};let opts=Object.fromEntries((x.question_options||[]).map(o=>[o.option_key,o.content]));let preview=x.id?`<div class="wide ai-note"><b>Xem trước công thức</b><div>${esc(x.content)}</div>${['A','B','C','D'].map(v=>`<div><b>${v}.</b> ${esc(opts[v]||'')}</div>`).join('')}${x.explanation?`<div><b>Giải thích:</b> ${esc(x.explanation)}</div>`:''}</div>`:'';modal(x.id?'Sửa câu hỏi':'Thêm câu hỏi',`<form id="qForm" class="form-grid">${preview}<label class="field wide">Nội dung<textarea name="content" required>${esc(x.content)}</textarea></label><label class="field">Chương<select name="chapter_id" id="qchapter" required>${sets.ch.map(v=>`<option value="${v.id}" ${v.id===x.chapter_id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label class="field">Chủ đề<select name="topic_id" id="qtopic" required></select></label><label class="field">CLO<select name="clo_id" required>${sets.clos.map(v=>`<option value="${v.id}" ${v.id===x.clo_id?'selected':''}>${esc(v.code)} — ${esc(v.description)}</option>`).join('')}</select></label><label class="field">Đáp án đúng<select name="correct_answer">${['A','B','C','D'].map(v=>`<option ${v===x.correct_answer?'selected':''}>${v}</option>`).join('')}</select></label><div class="wide option-grid">${['A','B','C','D'].map(v=>`<label class="field">Phương án ${v}<input name="opt_${v}" required value="${esc(opts[v])}"></label>`).join('')}</div><label class="field wide">Giải thích<textarea name="explanation">${esc(x.explanation)}</textarea></label><label class="field">Trạng thái<select name="status"><option value="active">Đang dùng</option><option value="draft" ${x.status==='draft'?'selected':''}>Bản nháp</option></select></label><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary">Lưu câu hỏi</button></div></form>`);
 const topicSelect=()=>{$('#qtopic').innerHTML=sets.topics.filter(t=>t.chapter_id===$('#qchapter').value).map(t=>`<option value="${t.id}" ${t.id===x.topic_id?'selected':''}>${esc(t.name)}</option>`).join('')};topicSelect();$('#qchapter').onchange=topicSelect;
 $('#qForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target)),optionRows=['A','B','C','D'].map(k=>({option_key:k,content:v['opt_'+k]}));['A','B','C','D'].forEach(k=>delete v['opt_'+k]);Object.assign(v,{subject_id:state.subjectId,created_by:state.user.id});let r=x.id?await db.from('questions').update(v).eq('id',x.id).select().single():await db.from('questions').insert(v).select().single();if(r.error)return err(r.error);let id=x.id||r.data.id;if(x.id){let d=await db.from('question_options').delete().eq('question_id',id);if(d.error)return err(d.error)}let o=await db.from('question_options').insert(optionRows.map(z=>({...z,question_id:id})));if(o.error)return err(o.error);closeModal();toast('Đã lưu câu hỏi');render()};}

function aiGenerateForm(sets){
 if(!sets.ch.length||!sets.clos.length)return toast('Học phần cần có chương và CLO trước khi tạo câu hỏi',true);
 modal('Tạo câu hỏi bằng Gemini',`<form id="aiForm" class="form-grid"><div class="ai-note wide"><b>Gemini chỉ tạo bản nháp.</b><span>Câu hỏi chỉ vào ngân hàng sau khi giảng viên xác nhận.</span></div><label class="field">Chương<select name="chapter_id" id="aiChapter" required>${sets.ch.map(v=>`<option value="${v.id}">${esc(v.order_index)}. ${esc(v.name)}</option>`).join('')}</select></label><label class="field">Chủ đề<select name="topic_id" id="aiTopic"><option value="">Tất cả chủ đề trong chương</option></select></label><label class="field">CLO<select name="clo_id" id="aiClo" required>${sets.clos.map(v=>`<option value="${v.id}">${esc(v.code)}</option>`).join('')}</select></label><label class="field">Số câu<select name="count"><option>5</option><option selected>10</option></select></label><div id="cloDescription" class="clo-description wide"></div><label class="field wide">Yêu cầu bổ sung (không bắt buộc)<textarea name="additional_requirements" placeholder="Ví dụ: 4 câu lý thuyết, 6 câu nhận biết mệnh đề đúng…"></textarea></label><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="ai-btn" id="aiSubmit">✦ Sinh câu hỏi</button></div></form>`);
 const fillTopics=()=>{$('#aiTopic').innerHTML='<option value="">Tất cả chủ đề trong chương</option>'+sets.topics.filter(t=>t.chapter_id===$('#aiChapter').value).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')};
 const showClo=()=>{let x=sets.clos.find(c=>c.id===$('#aiClo').value),box=$('#cloDescription');box.innerHTML=`<b>${esc(x?.code||'')}</b><span>${esc(x?.description||'')}</span>`;renderMath(box)};fillTopics();showClo();$('#aiChapter').onchange=fillTopics;$('#aiClo').onchange=showClo;
 $('#aiForm').onsubmit=async e=>{e.preventDefault();let btn=$('#aiSubmit'),v=Object.fromEntries(new FormData(e.target));btn.disabled=true;btn.textContent='Gemini đang tạo…';try{let {data,error}=await db.functions.invoke('generate-questions',{body:{subject_id:state.subjectId,chapter_id:v.chapter_id,topic_id:v.topic_id||null,clo_id:v.clo_id,count:+v.count,additional_requirements:v.additional_requirements}});if(error)throw error;if(!data?.success)throw new Error(data?.error||'Không tạo được câu hỏi');closeModal();toast(`Đã tạo ${data.total} câu chờ duyệt`);await reviewBatch(data.batch_id,0)}catch(ex){err(ex);btn.disabled=false;btn.textContent='✦ Sinh câu hỏi'}};
}

async function aiHistory(){
 try{let batches=await q('ai_generation_batches','*, chapters(name), clos(code)',x=>x.eq('subject_id',state.subjectId).order('created_at',{ascending:false}).limit(30));modal('Các phiên tạo câu hỏi AI',`<div class="history-list">${batches.map(b=>`<button data-batch="${b.id}"><span><b>${esc(b.clos?.code)} · ${esc(b.chapters?.name)}</b><small>${new Date(b.created_at).toLocaleString('vi-VN')} · ${b.generated_count}/${b.requested_count} câu</small></span><span class="badge ${b.status==='completed'?'green':'red'}">${esc(b.status)}</span></button>`).join('')||'<div class="empty">Chưa có phiên AI nào.</div>'}</div>`);$$('.history-list [data-batch]').forEach(b=>b.onclick=()=>{closeModal();reviewBatch(b.dataset.batch,0)})}catch(ex){err(ex)}
}

async function reviewBatch(batchId,index=0){
 let [batches,drafts]=await Promise.all([q('ai_generation_batches','*, chapters(name), clos(code,description)',x=>x.eq('id',batchId)),q('ai_question_drafts','*',x=>x.eq('batch_id',batchId).order('order_index'))]);let batch=batches[0];if(!batch||!drafts.length)return toast('Không tìm thấy câu hỏi trong phiên này',true);let pending=drafts.filter(d=>d.review_status==='pending'),current=pending[index]||pending[0]||drafts[0],pos=drafts.findIndex(d=>d.id===current.id);showDraft(batch,drafts,current,pos);
}

function showDraft(batch,drafts,d,pos){
 let approved=drafts.filter(x=>x.review_status==='approved').length,rejected=drafts.filter(x=>x.review_status==='rejected').length;
 modal('Duyệt câu hỏi Gemini',`<div class="review-wrap"><div class="review-progress"><b>Câu ${pos+1}/${drafts.length}</b><span>Đã lưu: ${approved} · Bỏ qua: ${rejected} · Chờ duyệt: ${drafts.length-approved-rejected}</span></div><div class="review-tags"><span class="badge red">${esc(batch.clos?.code)}</span><span class="badge">${esc(batch.chapters?.name)}</span><span class="badge ${d.review_status==='approved'?'green':''}">${esc(d.review_status)}</span></div><div class="ai-note"><b>Xem trước công thức</b><div>${esc(d.content)}</div>${['A','B','C','D'].map(k=>`<div><b>${k}.</b> ${esc(d.options?.[k]||'')}</div>`).join('')}${d.explanation?`<div><b>Giải thích:</b> ${esc(d.explanation)}</div>`:''}</div><label class="field">Nội dung<textarea id="draftContent">${esc(d.content)}</textarea></label><div class="review-options">${['A','B','C','D'].map(k=>`<label class="${d.correct_answer===k?'correct':''}"><b>${k}</b><input id="draft${k}" value="${esc(d.options?.[k])}"></label>`).join('')}</div><label class="field">Đáp án đúng<select id="draftCorrect">${['A','B','C','D'].map(k=>`<option ${d.correct_answer===k?'selected':''}>${k}</option>`).join('')}</select></label><label class="field">Giải thích<textarea id="draftExplanation">${esc(d.explanation)}</textarea></label><div class="review-actions"><button class="secondary" id="prevDraft" ${pos===0?'disabled':''}>← Trước</button><button class="danger" id="rejectDraft">Bỏ qua</button><button class="primary" id="approveDraft">Xác nhận và lưu</button><button class="secondary" id="nextDraft" ${pos===drafts.length-1?'disabled':''}>Sau →</button></div></div>`);
 $('#prevDraft').onclick=()=>showDraft(batch,drafts,drafts[pos-1],pos-1);$('#nextDraft').onclick=()=>showDraft(batch,drafts,drafts[pos+1],pos+1);
 $('#rejectDraft').onclick=async()=>{let {error}=await db.from('ai_question_drafts').update({review_status:'rejected',reviewed_by:state.user.id,reviewed_at:new Date().toISOString()}).eq('id',d.id);if(error)return err(error);d.review_status='rejected';toast('Đã bỏ qua câu hỏi');advanceReview(batch,drafts,pos)};
 $('#approveDraft').onclick=async()=>{let btn=$('#approveDraft');btn.disabled=true;try{let qrow={subject_id:batch.subject_id,chapter_id:batch.chapter_id,topic_id:d.topic_id||batch.topic_id,clo_id:batch.clo_id,content:$('#draftContent').value.trim(),explanation:$('#draftExplanation').value.trim()||null,correct_answer:$('#draftCorrect').value,created_by:state.user.id,status:'active'};if(!qrow.content)throw new Error('Nội dung câu hỏi không được để trống');if(!qrow.topic_id)throw new Error('Câu hỏi chưa được gắn chủ đề');let {data:question,error:qerr}=await db.from('questions').insert(qrow).select().single();if(qerr)throw qerr;let options=['A','B','C','D'].map(k=>({question_id:question.id,option_key:k,content:$('#draft'+k).value.trim()}));let {error:oerr}=await db.from('question_options').insert(options);if(oerr){await db.from('questions').delete().eq('id',question.id);throw oerr}let {error:derr}=await db.from('ai_question_drafts').update({content:qrow.content,options:Object.fromEntries(options.map(o=>[o.option_key,o.content])),correct_answer:qrow.correct_answer,explanation:qrow.explanation,review_status:'approved',approved_question_id:question.id,reviewed_by:state.user.id,reviewed_at:new Date().toISOString()}).eq('id',d.id);if(derr)throw derr;d.review_status='approved';toast('Đã lưu câu hỏi vào ngân hàng');advanceReview(batch,drafts,pos)}catch(ex){err(ex);btn.disabled=false}};
}

async function advanceReview(batch,drafts,pos){let pending=drafts.findIndex((x,i)=>i>pos&&x.review_status==='pending');if(pending<0)pending=drafts.findIndex(x=>x.review_status==='pending');if(pending>=0)return showDraft(batch,drafts,drafts[pending],pending);let {error}=await db.from('ai_generation_batches').update({status:'completed',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',batch.id);if(error)err(error);closeModal();toast('Đã duyệt xong phiên câu hỏi');render()}

async function exams(c){
 if(window.AICLO_ASSESSMENT?.exams)return window.AICLO_ASSESSMENT.exams(c);
 if(!state.subjectId){c.replaceChildren(empty());return}let items=await q('exams','*',x=>x.eq('subject_id',state.subjectId).order('created_at',{ascending:false}));c.innerHTML=`<div class="toolbar"><span></span>${canTeach()?'<button id="addExam" class="primary">+ Tạo đề thi</button>':''}</div><div class="panel table-wrap"><table><thead><tr><th>Tên đề</th><th>Loại</th><th>Số câu</th><th>Thời gian</th><th>Trạng thái</th><th></th></tr></thead><tbody id="examRows">${items.map(x=>`<tr><td><b>${esc(x.title)}</b><br><small>${esc(x.description||'')}</small></td><td>${esc(x.exam_type)}</td><td>${x.total_questions}</td><td>${x.duration_minutes||'—'} phút</td><td><span class="badge green">${esc(x.status)}</span></td><td class="row-actions">${canTeach()?`<button data-preview="${x.id}">Làm thử</button><button data-del="${x.id}">Xóa</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;$('#addExam')?.addEventListener('click',examForm);$('#examRows').onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.preview)previewExam(items.find(x=>x.id===b.dataset.preview));if(b.dataset.del)remove('exams',b.dataset.del,'đề thi')};
}
function examForm(){modal('Tạo đề thi',`<form id="examForm" class="form-grid"><label class="field wide">Tên đề<input name="title" required></label><label class="field wide">Mô tả<textarea name="description"></textarea></label><label class="field">Loại đề<select name="exam_type"><option value="chapter_test">Luyện tập theo chương</option><option value="clo_assessment">Đánh giá CLO</option><option value="final_exam">Thi cuối kỳ</option></select></label><label class="field">Số câu<input name="total_questions" type="number" min="1" required></label><label class="field">Thời gian (phút)<input name="duration_minutes" type="number" min="1"></label><label class="field">Trạng thái<select name="status"><option value="draft">Bản nháp</option><option value="active">Đang hoạt động</option></select></label><div class="form-actions"><button class="primary">Tạo đề</button></div></form>`);$('#examForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));Object.assign(v,{subject_id:state.subjectId,created_by:state.user.id,total_questions:+v.total_questions,duration_minutes:v.duration_minutes?+v.duration_minutes:null,is_clo_assessment:v.exam_type==='clo_assessment'});let {error}=await db.from('exams').insert(v);if(error)return err(error);closeModal();toast('Đã tạo đề thi');render()}}

async function previewExam(exam){
 try{let links=await q('exam_questions','*',x=>x.eq('exam_id',exam.id).order('question_order'));if(!links.length)return toast('Đề chưa có câu hỏi để làm thử',true);let ids=links.map(x=>x.question_id),[questions,clos]=await Promise.all([q('questions','*, question_options(*)',x=>x.in('id',ids)),q('clos','id,code',x=>x.eq('subject_id',exam.subject_id))]),ordered=links.map(link=>questions.find(x=>x.id===link.question_id)).filter(Boolean);if(!ordered.length)return toast('Không đọc được câu hỏi của đề',true);let answers={};showPreviewQuestion(exam,ordered,clos,answers,0)}catch(ex){err(ex)}
}

function showPreviewQuestion(exam,questions,clos,answers,index){
 let x=questions[index],opts=[...(x.question_options||[])].sort((a,b)=>a.option_key.localeCompare(b.option_key));modal(`Làm thử · ${exam.title}`,`<div class="exam-preview"><div class="preview-head"><b>Câu ${index+1}/${questions.length}</b><span class="badge red">${esc(clos.find(c=>c.id===x.clo_id)?.code||'—')}</span><span>Không lưu kết quả</span></div><div class="preview-question">${esc(x.content)}</div><div class="preview-options">${opts.map(o=>`<label class="${answers[x.id]===o.option_key?'selected':''}"><input type="radio" name="previewAnswer" value="${o.option_key}" ${answers[x.id]===o.option_key?'checked':''}><b>${o.option_key}</b><span>${esc(o.content)}</span></label>`).join('')}</div><div class="preview-nav"><button id="previewPrev" class="secondary" ${index===0?'disabled':''}>← Câu trước</button><button id="previewNext" class="secondary" ${index===questions.length-1?'disabled':''}>Câu sau →</button><button id="previewSubmit" class="primary">Nộp bài thử</button></div></div>`);$$('input[name="previewAnswer"]').forEach(r=>r.onchange=()=>{answers[x.id]=r.value;$$('.preview-options label').forEach(l=>l.classList.toggle('selected',l.contains(r)))});$('#previewPrev').onclick=()=>showPreviewQuestion(exam,questions,clos,answers,index-1);$('#previewNext').onclick=()=>showPreviewQuestion(exam,questions,clos,answers,index+1);$('#previewSubmit').onclick=()=>{let unanswered=questions.filter(q=>!answers[q.id]).length;if(unanswered&&!confirm(`Còn ${unanswered} câu chưa trả lời. Vẫn nộp bài thử?`))return;showPreviewResult(exam,questions,clos,answers)}
}

function showPreviewResult(exam,questions,clos,answers){
 let correct=questions.filter(q=>answers[q.id]===q.correct_answer).length,score=questions.length?correct*10/questions.length:0,byClo=clos.map(clo=>{let qs=questions.filter(q=>q.clo_id===clo.id);return {code:clo.code,total:qs.length,correct:qs.filter(q=>answers[q.id]===q.correct_answer).length}}).filter(x=>x.total);modal(`Kết quả làm thử · ${exam.title}`,`<div class="preview-result"><div class="result-score"><small>Điểm bài thử</small><b>${score.toFixed(2)}</b><span>${correct}/${questions.length} câu đúng</span></div><div class="clo-results">${byClo.map(x=>`<div><b>${esc(x.code)}</b><span>${x.correct}/${x.total} câu · ${(x.correct*10/x.total).toFixed(2)} điểm</span></div>`).join('')}</div><h4>Đáp án và lời giải</h4><div class="answer-review">${questions.map((q,i)=>`<details class="${answers[q.id]===q.correct_answer?'right':'wrong'}"><summary>Câu ${i+1} · ${questionCode(q.id)} — ${answers[q.id]===q.correct_answer?'Đúng':'Chưa đúng'}</summary><div>${esc(q.content)}</div><p>Bạn chọn: <b>${esc(answers[q.id]||'Chưa trả lời')}</b> · Đáp án đúng: <b>${esc(q.correct_answer)}</b></p><p>${esc(q.explanation||'Chưa có lời giải.')}</p></details>`).join('')}</div><div class="account-actions"><button id="retryPreview" class="primary">Làm lại</button></div></div>`);$('#retryPreview').onclick=()=>showPreviewQuestion(exam,questions,clos,{},0)
}

function cloFeedbackHtml(record){
 let a=record?.analysis;if(!a)return '<div class="ai-feedback-empty"><b>Chưa có nhận xét</b><p>Sau khi đã nộp ít nhất một bài, hãy nhấn nút bên trên để Gemini phân tích kết quả theo từng CLO.</p></div>';
 let metrics=a.metrics?.clos||[],feedback=a.clo_feedback||[];return `<div class="ai-feedback-content"><div class="ai-summary"><span class="ai-spark">✦</span><p>${esc(a.summary||'Đã phân tích kết quả học tập theo CLO.')}</p></div><div class="clo-feedback-grid">${metrics.map(m=>{let f=feedback.find(x=>x.clo_code===m.clo_code)||{};return `<article class="clo-feedback-card"><div class="clo-feedback-head"><b>${esc(m.clo_code)}</b><span class="badge ${Number(m.score)>=4?'green':'red'}">${Number(m.score).toFixed(2)} · ${esc(m.level)}</span></div><small>${esc(m.status)} · ${esc(m.confidence)} · ${m.correct_answers}/${m.total_questions} câu đúng</small><p>${esc(f.comment||'Chưa có nhận xét riêng cho CLO này.')}</p><div><b>Nên làm tiếp:</b> ${esc(f.recommendation||'Tiếp tục luyện tập các nội dung thuộc CLO này.')}</div></article>`}).join('')}</div>${(a.strengths||[]).length?`<div class="feedback-section"><h4>Điểm mạnh</h4><ul>${a.strengths.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${(a.needs_improvement||[]).length?`<div class="feedback-section"><h4>Nội dung cần củng cố</h4><ul>${a.needs_improvement.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${(a.next_actions||[]).length?`<div class="feedback-section"><h4>Hành động đề xuất</h4><ol>${a.next_actions.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>`:''}<p class="ai-disclaimer">${esc(a.disclaimer||'Nhận xét do AI tạo để tham khảo, không thay thế kết luận chính thức của giảng viên.')}</p></div>`}

async function studentResults(c,exams,attempts){
 let submitted=attempts.filter(x=>x.submitted_at),scored=submitted.filter(x=>x.score!=null),avg=scored.reduce((a,b)=>a+Number(b.score),0)/(scored.length||1),cached=[];try{cached=await q('student_clo_ai_feedback','analysis,generated_at',x=>x.eq('student_id',state.user.id).eq('subject_id',state.subjectId).limit(1))}catch(ex){console.warn('Không tải được nhận xét CLO đã lưu:',ex)}
 c.innerHTML=`<div class="stats"><div class="stat"><small>Lượt làm bài</small><b>${attempts.length}</b></div><div class="stat"><small>Đã nộp</small><b>${submitted.length}</b></div><div class="stat"><small>Điểm trung bình</small><b>${avg.toFixed(2)}</b></div><div class="stat"><small>Đề đã làm</small><b>${new Set(attempts.map(x=>x.exam_id)).size}</b></div></div><section class="panel ai-feedback-panel"><div class="panel-head"><div><h3>Nhận xét CLO của Gemini</h3><p>Phân tích dựa trên các bài đã nộp; hệ thống chỉ tạo lại khi có bài nộp mới.</p></div><button id="analyzeClo" class="ai-btn" ${!submitted.length?'disabled':''}>✦ ${cached.length?'Kiểm tra nhận xét mới':'Nhận xét của Gemini'}</button></div><div class="clo-scale"><span>M0 &lt; 4</span><span>M1: 4–&lt;5,5</span><span>M2: 5,5–&lt;7</span><span>M3: 7–&lt;8,5</span><span>M4: 8,5–10</span></div><div id="aiFeedback">${cloFeedbackHtml(cached[0])}</div></section><div class="panel table-wrap"><table><thead><tr><th>Đề thi</th><th>Lần</th><th>Điểm</th><th>Trạng thái</th><th>Thời điểm nộp</th></tr></thead><tbody>${attempts.map(x=>`<tr><td>${esc(exams.find(e=>e.id===x.exam_id)?.title||'—')}</td><td>${x.attempt_number}</td><td><b>${x.score??'—'}</b></td><td><span class="badge ${x.submitted_at?'green':''}">${x.submitted_at?'Đã nộp':'Đang làm'}</span></td><td>${x.submitted_at?new Date(x.submitted_at).toLocaleString('vi-VN'):'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Bạn chưa có lượt làm bài nào.</td></tr>'}</tbody></table></div>`;
 let btn=$('#analyzeClo');if(btn)btn.onclick=async()=>{btn.disabled=true;btn.textContent='✦ Gemini đang phân tích…';try{let {data,error}=await db.functions.invoke('analyze-student-clo',{body:{subject_id:state.subjectId}});if(error){let detail;try{detail=await error.context?.json()}catch{}throw new Error(detail?.error||error.message)}if(!data?.success)throw new Error(data?.error||'Không thể tạo nhận xét CLO.');$('#aiFeedback').innerHTML=cloFeedbackHtml({analysis:data.analysis});btn.textContent=data.cached?'✓ Đã dùng nhận xét hiện tại':'✓ Đã tạo nhận xét mới';toast(data.cached?'Chưa có bài nộp mới; đang hiển thị nhận xét đã lưu.':'Gemini đã hoàn tất nhận xét CLO.')}catch(ex){err(ex);btn.disabled=false;btn.textContent='✦ Thử lại nhận xét'}};
}

async function results(c){if(window.AICLO_ASSESSMENT?.results)return window.AICLO_ASSESSMENT.results(c);let exams=state.subjectId?await q('exams','id,title',x=>x.eq('subject_id',state.subjectId)):[];let ids=exams.map(x=>x.id),student=role()==='student';let attempts=ids.length?await q('exam_attempts',student?'*':'*, profiles:student_id(full_name,mssv)',x=>x.in('exam_id',ids).order('created_at',{ascending:false})):[];if(student)return studentResults(c,exams,attempts);let avg=attempts.filter(x=>x.score!=null).reduce((a,b)=>a+Number(b.score),0)/(attempts.filter(x=>x.score!=null).length||1);c.innerHTML=`<div class="stats"><div class="stat"><small>Lượt làm bài</small><b>${attempts.length}</b></div><div class="stat"><small>Đã nộp</small><b>${attempts.filter(x=>x.submitted_at).length}</b></div><div class="stat"><small>Điểm trung bình</small><b>${avg.toFixed(2)}</b></div><div class="stat"><small>Đề có dữ liệu</small><b>${new Set(attempts.map(x=>x.exam_id)).size}</b></div></div><div class="panel table-wrap"><table><thead><tr><th>Sinh viên</th><th>Đề thi</th><th>Lần</th><th>Điểm</th><th>Trạng thái</th></tr></thead><tbody>${attempts.map(x=>`<tr><td>${esc(x.profiles?.full_name||x.student_id)}<br><small>${esc(x.profiles?.mssv||'')}</small></td><td>${esc(exams.find(e=>e.id===x.exam_id)?.title)}</td><td>${x.attempt_number}</td><td><b>${x.score??'—'}</b></td><td><span class="badge ${x.submitted_at?'green':''}">${x.submitted_at?'Đã nộp':'Đang làm'}</span></td></tr>`).join('')}</tbody></table></div>`}

async function users(c){
 if(!['admin','teacher','lecturer','giangvien'].includes(role())){c.innerHTML='<div class="panel">Bạn không có quyền xem danh sách lớp.</div>';return}
 if(role()!=='admin')return teacherClassList(c);
 let [profiles,members]=await Promise.all([q('profiles','*',x=>x.order('full_name')),q('subject_members','*')]);
 c.innerHTML=`<div class="stats" id="userStats"></div><div class="toolbar user-toolbar"><input id="userSearch" placeholder="Tìm theo họ tên, email hoặc MSSV…"><select id="userSubject"><option value="all">Tất cả người dùng</option>${state.subjects.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.semester)}</option>`).join('')}</select><select id="userStatus"><option value="all">Tất cả trạng thái</option><option value="active">Đang hoạt động</option><option value="locked">Đã khóa</option></select><button id="manageClass" class="secondary" disabled>Quản lý lớp</button><button id="importUsers" class="secondary">Nhập CSV</button><button id="addUser" class="primary">+ Thêm người dùng</button></div><div class="panel table-wrap"><table><thead><tr><th>Họ tên</th><th>Email / MSSV</th><th>Vai trò</th><th>Trạng thái</th><th id="membershipHeading">Học phần</th><th></th></tr></thead><tbody id="userRows"></tbody></table></div>`;
 const draw=()=>{let s=$('#userSearch').value.toLowerCase(),status=$('#userStatus').value,subjectId=$('#userSubject').value,subjectMembers=subjectId==='all'?members:members.filter(m=>m.subject_id===subjectId),memberIds=new Set(subjectMembers.map(m=>m.user_id)),base=subjectId==='all'?profiles:profiles.filter(p=>memberIds.has(p.id)),list=base.filter(p=>[p.full_name,p.email,p.mssv].some(v=>String(v||'').toLowerCase().includes(s))).filter(p=>status==='all'||(status==='active'?p.is_active!==false:p.is_active===false));let teachers=base.filter(p=>p.role==='teacher').length,students=base.filter(p=>p.role==='student').length,locked=base.filter(p=>p.is_active===false).length;$('#userStats').innerHTML=`<div class="stat"><small>${subjectId==='all'?'Tổng tài khoản':'Tổng thành viên'}</small><b>${base.length}</b></div><div class="stat"><small>Giảng viên</small><b>${teachers}</b></div><div class="stat"><small>Sinh viên</small><b>${students}</b></div><div class="stat"><small>Đang bị khóa</small><b>${locked}</b></div>`;$('#manageClass').disabled=subjectId==='all';$('#membershipHeading').textContent=subjectId==='all'?'Học phần':'Vai trò trong lớp';$('#userRows').innerHTML=list.map(p=>{let membership=subjectId==='all'?members.filter(m=>m.user_id===p.id).length:(subjectMembers.find(m=>m.user_id===p.id)?.role||'—');return `<tr class="${p.is_active===false?'account-locked':''}"><td><b>${esc(p.full_name)}</b>${p.id===state.user.id?' <span class="badge">Bạn</span>':''}</td><td>${esc(p.email)}<br><small>${esc(p.mssv||'')}</small></td><td><span class="badge ${p.role==='student'?'green':'red'}">${esc(p.role)}</span></td><td><span class="badge ${p.is_active===false?'red':'green'}">${p.is_active===false?'Đã khóa':'Hoạt động'}</span></td><td>${esc(membership)}</td><td class="row-actions"><button data-detail="${p.id}">Chi tiết</button><button data-edit-user="${p.id}">Sửa</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">Không có tài khoản phù hợp.</td></tr>'};draw();
 $('#userSearch').oninput=draw;$('#userStatus').onchange=draw;$('#userSubject').onchange=draw;
 $('#userRows').onclick=e=>{let b=e.target.closest('button');if(!b)return;let p=profiles.find(x=>x.id===(b.dataset.detail||b.dataset.editUser));if(b.dataset.detail)userDetail(p,members);if(b.dataset.editUser)editUserForm(p)};
 $('#addUser').onclick=()=>manualUserForm();$('#importUsers').onclick=csvUserForm;$('#manageClass').onclick=()=>{let subjectId=$('#userSubject').value;if(subjectId!=='all')classManager(profiles,members,subjectId)};
}

async function teacherClassList(c){
 if(window.AICLO_ASSESSMENT?.teacherClassList)return window.AICLO_ASSESSMENT.teacherClassList(c);
 if(!state.subjectId){c.replaceChildren(empty());return}let members=await q('subject_members','*',x=>x.eq('subject_id',state.subjectId)),studentIds=members.filter(m=>m.role==='student').map(m=>m.user_id),profiles=studentIds.length?await q('profiles','id,full_name,email,mssv,role,is_active',x=>x.in('id',studentIds).order('full_name')):[];
 c.innerHTML=`<div class="stats class-stats"><div class="stat"><small>Sinh viên trong lớp</small><b>${profiles.length}</b></div><div class="stat"><small>Đang hoạt động</small><b>${profiles.filter(p=>p.is_active!==false).length}</b></div><div class="stat"><small>Đã khóa</small><b>${profiles.filter(p=>p.is_active===false).length}</b></div></div><div class="toolbar"><input id="classSearch" placeholder="Tìm theo họ tên, email hoặc MSSV…"></div><div class="panel table-wrap"><table><thead><tr><th>Họ tên</th><th>Email</th><th>MSSV</th><th>Trạng thái</th></tr></thead><tbody id="classRows"></tbody></table></div><p class="hint">Giảng viên chỉ được xem danh sách sinh viên; việc thêm, sửa hoặc khóa tài khoản do Admin thực hiện.</p>`;
 const draw=list=>$('#classRows').innerHTML=list.map(p=>`<tr><td><b>${esc(p.full_name)}</b></td><td>${esc(p.email)}</td><td>${esc(p.mssv||'—')}</td><td><span class="badge ${p.is_active===false?'red':'green'}">${p.is_active===false?'Đã khóa':'Hoạt động'}</span></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Học phần chưa có sinh viên.</td></tr>';draw(profiles);$('#classSearch').oninput=e=>{let s=e.target.value.toLowerCase();draw(profiles.filter(p=>[p.full_name,p.email,p.mssv].some(v=>String(v||'').toLowerCase().includes(s))))}
}

async function invokeAdmin(body){let {data,error}=await db.functions.invoke('admin-users',{body});if(error){let message=error.message;try{let response=await error.context?.json();message=response?.error||message}catch{}throw new Error(message)}if(!data?.success)throw new Error(data?.error||'Không thực hiện được thao tác');return data}

function userDetail(p,members){
 let joined=members.filter(m=>m.user_id===p.id).map(m=>({member:m,subject:state.subjects.find(s=>s.id===m.subject_id)}));
 modal('Chi tiết tài khoản',`<div class="user-detail"><div class="detail-identity"><div class="avatar">${esc((p.full_name||'?').trim().charAt(0).toUpperCase())}</div><div><h3>${esc(p.full_name)}</h3><p>${esc(p.email)}${p.mssv?` · MSSV ${esc(p.mssv)}`:''}</p><span class="badge ${p.role==='student'?'green':'red'}">${esc(p.role)}</span> <span class="badge ${p.is_active===false?'red':'green'}">${p.is_active===false?'Đã khóa':'Đang hoạt động'}</span></div></div><h4>Học phần tham gia (${joined.length})</h4><div class="subject-memberships">${joined.map(x=>`<div><b>${esc(x.subject?.name||'Học phần không còn tồn tại')}</b><small>${esc(x.subject?.semester||'')} ${esc(x.subject?.academic_year||'')} · ${esc(x.member.role)}</small></div>`).join('')||'<p class="hint">Chưa được thêm vào học phần nào.</p>'}</div><div class="account-actions"><button id="detailEdit" class="secondary">Sửa thông tin</button><button id="resetUserPassword" class="secondary">Đặt lại mật khẩu</button>${p.role!=='admin'&&p.id!==state.user.id?`<button id="toggleUserLock" class="${p.is_active===false?'primary':'danger'}">${p.is_active===false?'Mở khóa':'Khóa tài khoản'}</button><button id="deleteUser" class="danger">Xóa tài khoản</button>`:''}</div><div id="temporaryPasswordBox"></div></div>`);
 $('#detailEdit').onclick=()=>editUserForm(p);$('#resetUserPassword').onclick=async()=>{if(!await confirmAction('Đặt lại mật khẩu',`Đặt lại mật khẩu cho ${p.full_name}?`,{confirmLabel:'Đặt lại'}))return;try{let data=await invokeAdmin({action:'reset_password',user_id:p.id});$('#temporaryPasswordBox').innerHTML=`<div class="password-result"><b>Mật khẩu tạm mới</b><code>${esc(data.temporary_password)}</code><small>Hãy sao chép ngay. Mật khẩu này chỉ hiển thị một lần.</small></div>`;toast('Đã đặt lại mật khẩu')}catch(ex){err(ex)}};
 $('#toggleUserLock')?.addEventListener('click',async()=>{let locking=p.is_active!==false;if(!await confirmAction(`${locking?'Khóa':'Mở khóa'} tài khoản`,`Xác nhận ${locking?'khóa':'mở khóa'} tài khoản ${p.full_name}?`,{confirmLabel:locking?'Khóa':'Mở khóa',danger:locking}))return;try{await invokeAdmin({action:locking?'ban':'unban',user_id:p.id});closeModal();toast(locking?'Đã khóa tài khoản':'Đã mở khóa tài khoản');render()}catch(ex){err(ex)}})
 $('#deleteUser')?.addEventListener('click',async()=>{if(!await confirmAction('Xóa tài khoản',`Xóa ${p.full_name} khỏi hệ thống?`,{confirmLabel:'Tiếp tục',danger:true}))return;if(!await confirmAction('Xác nhận lần cuối','Tài khoản đăng nhập sẽ bị xóa; dữ liệu học tập có liên kết có thể khiến hệ thống từ chối để bảo toàn dữ liệu.',{confirmLabel:'Xóa vĩnh viễn',danger:true}))return;try{await invokeAdmin({action:'delete',user_id:p.id});window.logActivity?.('delete','user',p.id,`Xóa người dùng ${p.full_name}`);closeModal();toast('Đã xóa tài khoản');render()}catch(ex){err(ex)}})
}

function editUserForm(p){
 let admin=p.role==='admin';modal('Sửa tài khoản',`<form id="editUserForm" class="form-grid"><label class="field wide">Họ và tên<input name="full_name" required value="${esc(p.full_name)}"></label><label class="field wide">Email<input name="email" type="email" required value="${esc(p.email)}"></label><label class="field">Vai trò<select name="role" id="editRole" ${admin?'disabled':''}><option value="teacher" ${p.role==='teacher'?'selected':''}>Giảng viên</option><option value="student" ${p.role==='student'?'selected':''}>Sinh viên</option>${admin?'<option value="admin" selected>Admin</option>':''}</select></label><label class="field">MSSV<input name="mssv" id="editMssv" value="${esc(p.mssv||'')}" ${p.role==='student'?'required':''}></label>${admin?'<p class="hint wide">Tài khoản Admin chỉ được sửa họ tên và email; không thể đổi vai trò hoặc khóa.</p>':'<p class="hint wide">Khi đổi vai trò, hệ thống sẽ đồng bộ vai trò trong tất cả học phần.</p>'}<div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary" id="saveUser">Lưu thay đổi</button></div></form>`);
 $('#editRole').onchange=e=>{$('#editMssv').required=e.target.value==='student';if(e.target.value!=='student')$('#editMssv').value=''};
 $('#editUserForm').onsubmit=async e=>{e.preventDefault();let btn=$('#saveUser'),v=Object.fromEntries(new FormData(e.target));btn.disabled=true;btn.textContent='Đang lưu…';try{await invokeAdmin({action:'update',user_id:p.id,full_name:v.full_name,email:v.email,role:admin?'admin':v.role,mssv:v.mssv||null});closeModal();toast('Đã cập nhật tài khoản');render()}catch(ex){err(ex);btn.disabled=false;btn.textContent='Lưu thay đổi'}}
}

function manualUserForm(){
 modal('Thêm người dùng',`<form id="newUserForm" class="form-grid"><label class="field wide">Họ và tên<input name="full_name" required></label><label class="field wide">Email<input name="email" type="email" required></label><label class="field">Vai trò<select name="role" id="newRole"><option value="teacher">Giảng viên</option><option value="student">Sinh viên</option></select></label><label class="field">MSSV<input name="mssv" id="newMssv" placeholder="Chỉ bắt buộc với sinh viên"></label><label class="check-row wide"><input type="checkbox" name="add_to_subject" ${state.subjectId?'checked':'disabled'}> Thêm ngay vào học phần đang chọn</label><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary" id="createUserBtn">Tạo tài khoản</button></div></form>`);
 $('#newRole').onchange=e=>{$('#newMssv').required=e.target.value==='student'};
 $('#newUserForm').onsubmit=async e=>{e.preventDefault();let btn=$('#createUserBtn'),v=Object.fromEntries(new FormData(e.target));btn.disabled=true;btn.textContent='Đang tạo…';try{let result=await createAccounts([{full_name:v.full_name,email:v.email,role:v.role,mssv:v.mssv||null}]);let created=result.results.filter(x=>x.success);if(v.add_to_subject&&created.length)await addProfilesToSubject(created);showAccountResults(result)}catch(ex){err(ex);btn.disabled=false;btn.textContent='Tạo tài khoản'}};
}

function parseCsv(text){
 const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){let ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(field);field=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field=''}else field+=ch}row.push(field);if(row.some(x=>x.trim()))rows.push(row);if(rows.length<2)throw new Error('File CSV chưa có dữ liệu');let headers=rows[0].map(x=>x.trim().toLowerCase().replace(/^\ufeff/,''));let required=['full_name','email','role'];for(let h of required)if(!headers.includes(h))throw new Error(`Thiếu cột ${h}`);return rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]||'').trim()])))}

function csvUserForm(){
 modal('Nhập người dùng từ CSV',`<form id="csvForm" class="form-grid"><div class="csv-guide wide"><b>Cấu trúc CSV</b><code>full_name,email,role,mssv</code><span>Vai trò dùng <b>teacher</b> hoặc <b>student</b>. Tối đa 100 người mỗi lần.</span></div><label class="field wide">Chọn file CSV<input id="csvFile" type="file" accept=".csv,text/csv" required></label><label class="check-row wide"><input type="checkbox" id="csvAddClass" ${state.subjectId?'checked':'disabled'}> Thêm các tài khoản tạo thành công vào học phần đang chọn</label><div id="csvPreview" class="wide"></div><div class="form-actions"><button class="primary" id="csvSubmit">Tạo tài khoản</button></div></form>`);
 let parsed=[];$('#csvFile').onchange=async e=>{try{parsed=parseCsv(await e.target.files[0].text());if(parsed.length>100)throw new Error('File có quá 100 người');$('#csvPreview').innerHTML=`<span class="badge green">Đã đọc ${parsed.length} người</span>`}catch(ex){parsed=[];err(ex)}};
 $('#csvForm').onsubmit=async e=>{e.preventDefault();if(!parsed.length)return toast('Chưa có dữ liệu CSV hợp lệ',true);let btn=$('#csvSubmit');btn.disabled=true;btn.textContent='Đang tạo…';try{let result=await createAccounts(parsed);let created=result.results.filter(x=>x.success);if($('#csvAddClass').checked&&created.length)await addProfilesToSubject(created);showAccountResults(result)}catch(ex){err(ex);btn.disabled=false;btn.textContent='Tạo tài khoản'}};
}

async function createAccounts(users){
 return invokeAdmin({action:'create',users});
}

async function addProfilesToSubject(created){
 if(!state.subjectId)return;let rows=created.map(x=>({subject_id:state.subjectId,user_id:x.id,role:x.role}));let {error}=await db.from('subject_members').upsert(rows,{onConflict:'subject_id,user_id'});if(error)throw error;
}

function showAccountResults(result){
 let created=result.created_count??result.results.filter(x=>x.success).length,failed=result.failed_count??result.results.filter(x=>!x.success).length;modal('Kết quả tạo tài khoản',`<div class="account-summary"><span class="badge green">Thành công: ${created}</span><span class="badge red">Lỗi: ${failed}</span></div><div class="table-wrap result-table"><table><thead><tr><th>Họ tên</th><th>Email</th><th>Vai trò</th><th>Mật khẩu tạm / Lỗi</th></tr></thead><tbody>${result.results.map(x=>`<tr><td>${esc(x.full_name||'—')}</td><td>${esc(x.email)}</td><td>${esc(x.role||'—')}</td><td>${x.success?`<code>${esc(x.temporary_password)}</code>`:`<span class="error-text">${esc(x.error)}</span>`}</td></tr>`).join('')}</tbody></table></div><div class="result-actions"><button id="downloadAccounts" class="primary">Tải CSV kết quả</button><button id="finishAccounts" class="secondary">Hoàn tất</button></div>`);
 $('#downloadAccounts').onclick=()=>downloadAccountCsv(result.results);$('#finishAccounts').onclick=()=>{closeModal();render()};
}

function csvCell(v){let s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function downloadAccountCsv(results){let lines=[['full_name','email','role','mssv','temporary_password','status','error'],...results.map(x=>[x.full_name,x.email,x.role,x.mssv,x.temporary_password,x.success?'success':'failed',x.error])];let blob=new Blob(['\ufeff'+lines.map(r=>r.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tai-khoan-ai-clo-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function classManager(profiles,members,subjectId=state.subjectId){
 if(!subjectId)return toast('Hãy chọn học phần trước',true);let subject=state.subjects.find(s=>s.id===subjectId),current=members.filter(m=>m.subject_id===subjectId),currentIds=new Set(current.map(m=>m.user_id)),eligible=profiles.filter(p=>['teacher','student'].includes(p.role)&&p.is_active!==false&&!currentIds.has(p.id));
 modal(`Thành viên · ${subject?.name||''}`,`<div class="class-manager"><div class="class-column"><h4>Thêm vào học phần</h4><input id="memberSearch" placeholder="Tìm tên, email, MSSV…"><div id="candidateList" class="member-list"></div><button id="addSelectedMembers" class="primary">Thêm người đã chọn</button></div><div class="class-column"><h4>Thành viên hiện tại (${current.length})</h4><div class="member-list">${current.map(m=>{let p=profiles.find(x=>x.id===m.user_id);return `<div class="member-item"><span><b>${esc(p?.full_name||m.user_id)}</b><small>${esc(p?.email||'')} · ${esc(m.role)}</small></span><button class="danger" data-remove-member="${m.id}">Xóa</button></div>`}).join('')||'<div class="empty">Chưa có thành viên.</div>'}</div></div></div>`);
 const draw=list=>$('#candidateList').innerHTML=list.map(p=>`<label class="member-item"><input type="checkbox" value="${p.id}"><span><b>${esc(p.full_name)}</b><small>${esc(p.email)} · ${esc(p.mssv||p.role)}</small></span></label>`).join('')||'<div class="empty">Không còn tài khoản phù hợp.</div>';draw(eligible);$('#memberSearch').oninput=e=>{let s=e.target.value.toLowerCase();draw(eligible.filter(p=>[p.full_name,p.email,p.mssv].some(v=>String(v||'').toLowerCase().includes(s))))};
 $('#addSelectedMembers').onclick=async()=>{let ids=$$('#candidateList input:checked').map(x=>x.value);if(!ids.length)return toast('Chưa chọn người dùng',true);let rows=profiles.filter(p=>ids.includes(p.id)).map(p=>({subject_id:subjectId,user_id:p.id,role:p.role}));try{let {error}=await db.from('subject_members').upsert(rows,{onConflict:'subject_id,user_id'});if(error)throw error;toast(`Đã thêm ${rows.length} thành viên`);closeModal();render()}catch(ex){err(ex)}};
 $$('[data-remove-member]').forEach(b=>b.onclick=async()=>{if(!await confirmAction('Xóa khỏi học phần','Xóa người này khỏi học phần hiện tại?',{confirmLabel:'Xóa',danger:true}))return;let {error}=await db.from('subject_members').delete().eq('id',b.dataset.removeMember);if(error)return err(error);toast('Đã xóa thành viên khỏi học phần');closeModal();render()});
}

async function remove(table,id,label){if(!await confirmAction(`Xóa ${label}`,`Bạn có chắc muốn xóa ${label} này? Dữ liệu liên quan có thể khiến thao tác bị từ chối.`,{confirmLabel:'Xóa',danger:true}))return;let {error}=await db.from(table).delete().eq('id',id);if(error)return err(error);toast(`Đã xóa ${label}`);if(table==='subjects')await boot(state.user);else render()}
async function removeQuestion(id){if(!await confirmAction('Xóa câu hỏi','Xóa câu hỏi này và toàn bộ phương án? Thao tác không thể hoàn tác.',{confirmLabel:'Xóa',danger:true}))return;let a=await db.from('question_options').delete().eq('question_id',id);if(a.error)return err(a.error);let b=await db.from('questions').delete().eq('id',id);if(b.error)return err(b.error);toast('Đã xóa câu hỏi');render()}
