/* AI-CLO PTITHCM — static GitHub Pages client for the existing Supabase schema */
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const cfg=window.AICLO_CONFIG||{};
const db=window.supabase?.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const state={user:null,profile:null,subjects:[],subjectId:localStorage.getItem('aiclo_subject')||'',view:'dashboard'};
const titles={dashboard:['Tổng quan','Theo dõi dữ liệu học phần và hoạt động'],subjects:['Học phần','Quản lý môn học theo năm học và học kỳ'],structure:['Chương · Chủ đề · CLO','Xây dựng cấu trúc nội dung và chuẩn đầu ra'],questions:['Ngân hàng câu hỏi','Biên soạn, duyệt và quản lý câu hỏi'],exams:['Đề thi','Thiết kế bài kiểm tra theo chương và CLO'],results:['Kết quả CLO','Theo dõi kết quả bài làm và mức độ đạt CLO'],users:['Người dùng','Quản lý thành viên và phân quyền học phần']};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=(m,e=false)=>{const x=$('#toast');x.textContent=m;x.className='toast show'+(e?' error':'');setTimeout(()=>x.className='toast',3000)};
const err=e=>{console.error(e);toast(e?.message||'Có lỗi xảy ra',true)};
const role=()=>state.profile?.role||'student'; const canTeach=()=>['admin','teacher','lecturer','giangvien'].includes(role());
const activeSubject=()=>state.subjects.find(x=>x.id===state.subjectId);
function empty(){return $('#emptyTpl').content.cloneNode(true)}
function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').showModal()}
function closeModal(){ $('#modal').close() }
async function q(table,select='*',build=x=>x){let r=await build(db.from(table).select(select));if(r.error)throw r.error;return r.data||[]}

document.addEventListener('DOMContentLoaded',init);
async function init(){
 if(!db){return err('Không tải được thư viện Supabase. Hãy kiểm tra kết nối mạng.')}
 $('#loginForm').onsubmit=login; $('#logoutBtn').onclick=async()=>{await window.logActivity?.('logout','system',null,'Đăng xuất hệ thống');await db.auth.signOut()}; $('#resetBtn').onclick=resetPassword;
 const openLogin=()=>{$('#loginPanel').classList.remove('hidden');setTimeout(()=>$('#email').focus(),50)};$('#openLogin').onclick=openLogin;$('#heroLogin').onclick=openLogin;$('#closeLogin').onclick=()=>$('#loginPanel').classList.add('hidden');$('#loginPanel').onclick=e=>{if(e.target===$('#loginPanel'))$('#loginPanel').classList.add('hidden')};
 $('#menuBtn').onclick=()=>$('aside').classList.toggle('open'); $('#subjectSelect').onchange=e=>{state.subjectId=e.target.value;localStorage.setItem('aiclo_subject',state.subjectId);render()};
 $('#nav').onclick=e=>{let b=e.target.closest('[data-view]');if(b)navigate(b.dataset.view)};
 db.auth.onAuthStateChange((event,session)=>{
   if(event==='SIGNED_OUT')return showAuth();
   if(event==='SIGNED_IN'&&session?.user&&state.user?.id!==session.user.id)boot(session.user);
   if(event==='USER_UPDATED'&&session?.user)boot(session.user);
 });
 const {data}=await db.auth.getSession();
 if(data.session?.user){if(state.user?.id!==data.session.user.id)await boot(data.session.user)}else showAuth();
}
function showAuth(){$('#auth').classList.remove('hidden');$('#app').classList.add('hidden');$('#loginPanel')?.classList.add('hidden');state.user=null}
async function login(e){e.preventDefault();let email=$('#email').value.trim(),{data,error}=await db.auth.signInWithPassword({email,password:$('#password').value});if(error){err(error);return}state.user=data.user||state.user;await window.logActivity?.('login','system',null,'Đăng nhập hệ thống');toast('Đăng nhập thành công')}
async function resetPassword(){let email=$('#email').value.trim();if(!email)return toast('Nhập email trước khi yêu cầu đặt lại mật khẩu',true);let {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});error?err(error):toast('Đã gửi email đặt lại mật khẩu')}
async function boot(user){
 try{state.user=user;let {data,error}=await db.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;if(data.is_active===false){toast('Tài khoản đã bị khóa',true);await db.auth.signOut();return}state.profile=data;
   state.subjects=await q('subjects','*',x=>x.order('academic_year',{ascending:false}).order('name'));
   if(!state.subjects.some(s=>s.id===state.subjectId))state.subjectId=state.subjects[0]?.id||'';
   $('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#miniUser').innerHTML=`<b>${esc(data.full_name)}</b><br>${esc(data.email)} · ${esc(data.role)}`;
   $$('[data-admin]').forEach(x=>x.hidden=role()!=='admin');$$('[data-teacher]').forEach(x=>x.hidden=!canTeach());fillSubjectSelect();navigate(state.view);
 }catch(e){err(e)}
}
function fillSubjectSelect(){let s=$('#subjectSelect');s.innerHTML=state.subjects.length?state.subjects.map(x=>`<option value="${x.id}" ${x.id===state.subjectId?'selected':''}>${esc(x.name)} · ${esc(x.semester)}</option>`).join(''):'<option value="">Chưa có học phần</option>'}
function navigate(v){state.view=v;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('aside').classList.remove('open');let [t,s]=titles[v];$('#pageTitle').textContent=t;$('#pageSub').textContent=s;render()}
async function render(){let c=$('#content');c.innerHTML='<div class="panel">Đang tải dữ liệu…</div>';try{await ({dashboard,subjects,structure,questions,exams,results,users}[state.view]||dashboard)(c)}catch(e){c.innerHTML=`<div class="panel"><b>Không thể tải dữ liệu</b><p>${esc(e.message)}</p></div>`;err(e)}}

async function dashboard(c){
 let sid=state.subjectId;let [chapters,clos,questions,exams]=sid?await Promise.all([q('chapters','id',x=>x.eq('subject_id',sid)),q('clos','id',x=>x.eq('subject_id',sid)),q('questions','id,status',x=>x.eq('subject_id',sid)),q('exams','id,status',x=>x.eq('subject_id',sid))]):[[],[],[],[]];
 c.innerHTML=`<div class="stats"><div class="stat"><small>Học phần được truy cập</small><b>${state.subjects.length}</b></div><div class="stat"><small>Câu hỏi</small><i>?</i><b>${questions.length}</b></div><div class="stat"><small>CLO</small><i>◎</i><b>${clos.length}</b></div><div class="stat"><small>Đề thi</small><i>✎</i><b>${exams.length}</b></div></div><div class="grid2"><section class="panel"><div class="panel-head"><h3>Tiến độ học phần</h3></div>${metric('Cấu trúc chương',chapters.length,Math.min(100,chapters.length*20))}${metric('Ngân hàng câu hỏi',questions.length,Math.min(100,questions.length*2))}${metric('Đề thi đã tạo',exams.length,Math.min(100,exams.length*20))}</section><section class="panel"><div class="panel-head"><h3>Học phần hiện tại</h3></div>${activeSubject()?`<h2>${esc(activeSubject().name)}</h2><p>${esc(activeSubject().semester)} · ${esc(activeSubject().academic_year)}</p><p><span class="badge green">${questions.filter(x=>x.status==='active').length} câu đang hoạt động</span></p>`:'<p>Quản trị viên cần tạo học phần và thêm bạn vào học phần.</p>'}</section></div>`;
}
const metric=(name,n,p)=>`<p><b>${esc(name)}</b><span style="float:right">${n}</span></p><div class="bar"><span style="width:${p}%"></span></div>`;

async function subjects(c){
 c.innerHTML=`<div class="toolbar"><input id="search" placeholder="Tìm học phần…"><button class="primary" id="addSubject" ${role()!=='admin'?'hidden':''}>+ Tạo học phần</button></div><div class="panel table-wrap"><table><thead><tr><th>Học phần</th><th>Học kỳ</th><th>Năm học</th><th>Vai trò</th><th></th></tr></thead><tbody id="rows"></tbody></table></div>`;
 const draw=(list=state.subjects)=>$('#rows').innerHTML=list.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.semester)}</td><td>${esc(s.academic_year)}</td><td><span class="badge">${role()==='admin'?'Quản trị':'Thành viên'}</span></td><td class="row-actions"><button data-open="${s.id}">Mở</button>${role()==='admin'?`<button data-edit="${s.id}">Sửa</button><button data-del="${s.id}">Xóa</button>`:''}</td></tr>`).join('');draw();
 $('#search').oninput=e=>draw(state.subjects.filter(s=>s.name.toLowerCase().includes(e.target.value.toLowerCase())));$('#addSubject')?.addEventListener('click',()=>subjectForm());
 $('#rows').onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.open){state.subjectId=b.dataset.open;fillSubjectSelect();navigate('dashboard')}if(b.dataset.edit)subjectForm(state.subjects.find(x=>x.id===b.dataset.edit));if(b.dataset.del)remove('subjects',b.dataset.del,'học phần')};
}
function subjectForm(s={}){modal(s.id?'Sửa học phần':'Tạo học phần',`<form id="subjectForm" class="form-grid"><label class="field wide">Tên học phần<input name="name" required value="${esc(s.name)}"></label><label class="field">Học kỳ<input name="semester" required value="${esc(s.semester||'Học kỳ 1')}"></label><label class="field">Năm học<input name="academic_year" required value="${esc(s.academic_year||'2026-2027')}"></label><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary">Lưu</button></div></form>`);$('#subjectForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));let r=s.id?await db.from('subjects').update(v).eq('id',s.id):await db.from('subjects').insert(v);if(r.error)return err(r.error);closeModal();toast('Đã lưu học phần');await boot(state.user)}}

async function structure(c){
 if(!state.subjectId){c.replaceChildren(empty());return}let [ch,topics,clos]=await Promise.all([q('chapters','*',x=>x.eq('subject_id',state.subjectId).order('order_index')),q('topics','*',x=>x.order('order_index')),q('clos','*',x=>x.eq('subject_id',state.subjectId).order('code'))]);let relevantTopics=topics.filter(t=>ch.some(x=>x.id===t.chapter_id));
 c.innerHTML=`<div class="grid2"><section class="panel"><div class="panel-head"><h3>Chương và chủ đề</h3>${canTeach()?'<button id="addChapter" class="primary">+ Chương</button>':''}</div><div id="chapterList">${ch.map(x=>`<div style="padding:12px 0;border-bottom:1px solid var(--line)"><b>${x.order_index}. ${esc(x.name)}</b>${canTeach()?`<button data-topic="${x.id}" style="float:right">+ Chủ đề</button>`:''}<div>${relevantTopics.filter(t=>t.chapter_id===x.id).map(t=>`<span class="badge">${esc(t.name)}</span> `).join('')||'<small>Chưa có chủ đề</small>'}</div></div>`).join('')||'<p>Chưa có chương.</p>'}</div></section><section class="panel"><div class="panel-head"><h3>Chuẩn đầu ra CLO</h3>${role()==='admin'?'<button id="addClo" class="primary">+ CLO</button>':''}</div>${clos.map(x=>`<div style="padding:12px 0;border-bottom:1px solid var(--line)"><span class="badge red">${esc(x.code)}</span> ${esc(x.description)}</div>`).join('')||'<p>Chưa có CLO.</p>'}</section></div>`;
 $('#addChapter')?.addEventListener('click',()=>simpleForm('Tạo chương',[['name','Tên chương'],['order_index','Thứ tự','number']],async v=>db.from('chapters').insert({...v,order_index:+v.order_index,subject_id:state.subjectId})));
 $('#addClo')?.addEventListener('click',()=>simpleForm('Tạo CLO',[['code','Mã CLO'],['description','Mô tả']],async v=>db.from('clos').insert({...v,subject_id:state.subjectId})));
 $('#chapterList').onclick=e=>{let b=e.target.closest('[data-topic]');if(b)simpleForm('Tạo chủ đề',[['name','Tên chủ đề'],['order_index','Thứ tự','number']],async v=>db.from('topics').insert({...v,order_index:+v.order_index,chapter_id:b.dataset.topic}))};
}
function simpleForm(title,fields,save){modal(title,`<form id="simpleForm" class="form-grid">${fields.map(f=>`<label class="field wide">${f[1]}<input name="${f[0]}" type="${f[2]||'text'}" required></label>`).join('')}<div class="form-actions"><button class="primary">Lưu</button></div></form>`);$('#simpleForm').onsubmit=async e=>{e.preventDefault();let r=await save(Object.fromEntries(new FormData(e.target)));if(r.error)return err(r.error);closeModal();toast('Đã lưu');render()}}

async function questions(c){
 if(!state.subjectId){c.replaceChildren(empty());return}let [items,ch,topics,clos]=await Promise.all([q('questions','*, question_options(*)',x=>x.eq('subject_id',state.subjectId).order('created_at',{ascending:false})),q('chapters','*',x=>x.eq('subject_id',state.subjectId).order('order_index')),q('topics'),q('clos','*',x=>x.eq('subject_id',state.subjectId).order('code'))]);
 const draw=list=>{$('#qrows').innerHTML=list.map(x=>`<tr><td><b>${esc(x.content).slice(0,120)}</b><br><small>${esc(x.explanation||'')}</small></td><td><span class="badge red">${esc(clos.find(z=>z.id===x.clo_id)?.code||'—')}</span></td><td>${esc(ch.find(z=>z.id===x.chapter_id)?.name||'—')}</td><td><span class="badge ${x.status==='active'?'green':''}">${esc(x.status)}</span></td><td class="row-actions">${canTeach()?`<button data-edit="${x.id}">Sửa</button><button data-del="${x.id}">Xóa</button>`:''}</td></tr>`).join('')};
 c.innerHTML=`<div class="toolbar"><input id="qsearch" placeholder="Tìm nội dung câu hỏi…">${canTeach()?'<button id="aiHistory" class="secondary">Phiên AI</button><button id="generateAI" class="ai-btn">✦ Tạo bằng Gemini</button><button id="addQ" class="primary">+ Thêm câu hỏi</button>':''}</div><div class="panel table-wrap"><table><thead><tr><th>Nội dung</th><th>CLO</th><th>Chương</th><th>Trạng thái</th><th></th></tr></thead><tbody id="qrows"></tbody></table></div>`;draw(items);
 $('#qsearch').oninput=e=>draw(items.filter(x=>x.content.toLowerCase().includes(e.target.value.toLowerCase())));$('#addQ')?.addEventListener('click',()=>questionForm(null,{ch,topics,clos}));$('#generateAI')?.addEventListener('click',()=>aiGenerateForm({ch,topics,clos}));$('#aiHistory')?.addEventListener('click',aiHistory);$('#qrows').onclick=e=>{let b=e.target.closest('button');if(b?.dataset.edit)questionForm(items.find(x=>x.id===b.dataset.edit),{ch,topics,clos});if(b?.dataset.del)removeQuestion(b.dataset.del)};
}
function questionForm(x={},sets){x=x||{};let opts=Object.fromEntries((x.question_options||[]).map(o=>[o.option_key,o.content]));modal(x.id?'Sửa câu hỏi':'Thêm câu hỏi',`<form id="qForm" class="form-grid"><label class="field wide">Nội dung<textarea name="content" required>${esc(x.content)}</textarea></label><label class="field">Chương<select name="chapter_id" id="qchapter" required>${sets.ch.map(v=>`<option value="${v.id}" ${v.id===x.chapter_id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label class="field">Chủ đề<select name="topic_id" id="qtopic" required></select></label><label class="field">CLO<select name="clo_id" required>${sets.clos.map(v=>`<option value="${v.id}" ${v.id===x.clo_id?'selected':''}>${esc(v.code)} — ${esc(v.description)}</option>`).join('')}</select></label><label class="field">Đáp án đúng<select name="correct_answer">${['A','B','C','D'].map(v=>`<option ${v===x.correct_answer?'selected':''}>${v}</option>`).join('')}</select></label><div class="wide option-grid">${['A','B','C','D'].map(v=>`<label class="field">Phương án ${v}<input name="opt_${v}" required value="${esc(opts[v])}"></label>`).join('')}</div><label class="field wide">Giải thích<textarea name="explanation">${esc(x.explanation)}</textarea></label><label class="field">Trạng thái<select name="status"><option value="active">Đang dùng</option><option value="draft" ${x.status==='draft'?'selected':''}>Bản nháp</option></select></label><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary">Lưu câu hỏi</button></div></form>`);
 const topicSelect=()=>{$('#qtopic').innerHTML=sets.topics.filter(t=>t.chapter_id===$('#qchapter').value).map(t=>`<option value="${t.id}" ${t.id===x.topic_id?'selected':''}>${esc(t.name)}</option>`).join('')};topicSelect();$('#qchapter').onchange=topicSelect;
 $('#qForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target)),optionRows=['A','B','C','D'].map(k=>({option_key:k,content:v['opt_'+k]}));['A','B','C','D'].forEach(k=>delete v['opt_'+k]);Object.assign(v,{subject_id:state.subjectId,created_by:state.user.id});let r=x.id?await db.from('questions').update(v).eq('id',x.id).select().single():await db.from('questions').insert(v).select().single();if(r.error)return err(r.error);let id=x.id||r.data.id;if(x.id){let d=await db.from('question_options').delete().eq('question_id',id);if(d.error)return err(d.error)}let o=await db.from('question_options').insert(optionRows.map(z=>({...z,question_id:id})));if(o.error)return err(o.error);closeModal();toast('Đã lưu câu hỏi');render()};}

function aiGenerateForm(sets){
 if(!sets.ch.length||!sets.clos.length)return toast('Học phần cần có chương và CLO trước khi tạo câu hỏi',true);
 modal('Tạo câu hỏi bằng Gemini',`<form id="aiForm" class="form-grid"><div class="ai-note wide"><b>Gemini chỉ tạo bản nháp.</b><span>Câu hỏi chỉ vào ngân hàng sau khi giảng viên xác nhận.</span></div><label class="field">Chương<select name="chapter_id" id="aiChapter" required>${sets.ch.map(v=>`<option value="${v.id}">${esc(v.order_index)}. ${esc(v.name)}</option>`).join('')}</select></label><label class="field">Chủ đề<select name="topic_id" id="aiTopic"><option value="">Tất cả chủ đề trong chương</option></select></label><label class="field">CLO<select name="clo_id" id="aiClo" required>${sets.clos.map(v=>`<option value="${v.id}">${esc(v.code)}</option>`).join('')}</select></label><label class="field">Số câu<select name="count"><option>5</option><option selected>10</option></select></label><div id="cloDescription" class="clo-description wide"></div><label class="field wide">Yêu cầu bổ sung (không bắt buộc)<textarea name="additional_requirements" placeholder="Ví dụ: 4 câu lý thuyết, 6 câu nhận biết mệnh đề đúng…"></textarea></label><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="ai-btn" id="aiSubmit">✦ Sinh câu hỏi</button></div></form>`);
 const fillTopics=()=>{$('#aiTopic').innerHTML='<option value="">Tất cả chủ đề trong chương</option>'+sets.topics.filter(t=>t.chapter_id===$('#aiChapter').value).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')};
 const showClo=()=>{let x=sets.clos.find(c=>c.id===$('#aiClo').value);$('#cloDescription').innerHTML=`<b>${esc(x?.code||'')}</b><span>${esc(x?.description||'')}</span>`};fillTopics();showClo();$('#aiChapter').onchange=fillTopics;$('#aiClo').onchange=showClo;
 $('#aiForm').onsubmit=async e=>{e.preventDefault();let btn=$('#aiSubmit'),v=Object.fromEntries(new FormData(e.target));btn.disabled=true;btn.textContent='Gemini đang tạo…';try{let {data,error}=await db.functions.invoke('generate-questions',{body:{subject_id:state.subjectId,chapter_id:v.chapter_id,topic_id:v.topic_id||null,clo_id:v.clo_id,count:+v.count,additional_requirements:v.additional_requirements}});if(error)throw error;if(!data?.success)throw new Error(data?.error||'Không tạo được câu hỏi');closeModal();toast(`Đã tạo ${data.total} câu chờ duyệt`);await reviewBatch(data.batch_id,0)}catch(ex){err(ex);btn.disabled=false;btn.textContent='✦ Sinh câu hỏi'}};
}

async function aiHistory(){
 try{let batches=await q('ai_generation_batches','*, chapters(name), clos(code)',x=>x.eq('subject_id',state.subjectId).order('created_at',{ascending:false}).limit(30));modal('Các phiên tạo câu hỏi AI',`<div class="history-list">${batches.map(b=>`<button data-batch="${b.id}"><span><b>${esc(b.clos?.code)} · ${esc(b.chapters?.name)}</b><small>${new Date(b.created_at).toLocaleString('vi-VN')} · ${b.generated_count}/${b.requested_count} câu</small></span><span class="badge ${b.status==='completed'?'green':'red'}">${esc(b.status)}</span></button>`).join('')||'<div class="empty">Chưa có phiên AI nào.</div>'}</div>`);$$('.history-list [data-batch]').forEach(b=>b.onclick=()=>{closeModal();reviewBatch(b.dataset.batch,0)})}catch(ex){err(ex)}
}

async function reviewBatch(batchId,index=0){
 let [batches,drafts]=await Promise.all([q('ai_generation_batches','*, chapters(name), clos(code,description)',x=>x.eq('id',batchId)),q('ai_question_drafts','*',x=>x.eq('batch_id',batchId).order('order_index'))]);let batch=batches[0];if(!batch||!drafts.length)return toast('Không tìm thấy câu hỏi trong phiên này',true);let pending=drafts.filter(d=>d.review_status==='pending'),current=pending[index]||pending[0]||drafts[0],pos=drafts.findIndex(d=>d.id===current.id);showDraft(batch,drafts,current,pos);
}

function showDraft(batch,drafts,d,pos){
 let approved=drafts.filter(x=>x.review_status==='approved').length,rejected=drafts.filter(x=>x.review_status==='rejected').length;
 modal('Duyệt câu hỏi Gemini',`<div class="review-wrap"><div class="review-progress"><b>Câu ${pos+1}/${drafts.length}</b><span>Đã lưu: ${approved} · Bỏ qua: ${rejected} · Chờ duyệt: ${drafts.length-approved-rejected}</span></div><div class="review-tags"><span class="badge red">${esc(batch.clos?.code)}</span><span class="badge">${esc(batch.chapters?.name)}</span><span class="badge ${d.review_status==='approved'?'green':''}">${esc(d.review_status)}</span></div><label class="field">Nội dung<textarea id="draftContent">${esc(d.content)}</textarea></label><div class="review-options">${['A','B','C','D'].map(k=>`<label class="${d.correct_answer===k?'correct':''}"><b>${k}</b><input id="draft${k}" value="${esc(d.options?.[k])}"></label>`).join('')}</div><label class="field">Đáp án đúng<select id="draftCorrect">${['A','B','C','D'].map(k=>`<option ${d.correct_answer===k?'selected':''}>${k}</option>`).join('')}</select></label><label class="field">Giải thích<textarea id="draftExplanation">${esc(d.explanation)}</textarea></label><div class="review-actions"><button class="secondary" id="prevDraft" ${pos===0?'disabled':''}>← Trước</button><button class="danger" id="rejectDraft">Bỏ qua</button><button class="primary" id="approveDraft">Xác nhận và lưu</button><button class="secondary" id="nextDraft" ${pos===drafts.length-1?'disabled':''}>Sau →</button></div></div>`);
 $('#prevDraft').onclick=()=>showDraft(batch,drafts,drafts[pos-1],pos-1);$('#nextDraft').onclick=()=>showDraft(batch,drafts,drafts[pos+1],pos+1);
 $('#rejectDraft').onclick=async()=>{let {error}=await db.from('ai_question_drafts').update({review_status:'rejected',reviewed_by:state.user.id,reviewed_at:new Date().toISOString()}).eq('id',d.id);if(error)return err(error);d.review_status='rejected';toast('Đã bỏ qua câu hỏi');advanceReview(batch,drafts,pos)};
 $('#approveDraft').onclick=async()=>{let btn=$('#approveDraft');btn.disabled=true;try{let qrow={subject_id:batch.subject_id,chapter_id:batch.chapter_id,topic_id:d.topic_id||batch.topic_id,clo_id:batch.clo_id,content:$('#draftContent').value.trim(),explanation:$('#draftExplanation').value.trim()||null,correct_answer:$('#draftCorrect').value,created_by:state.user.id,status:'active'};if(!qrow.content)throw new Error('Nội dung câu hỏi không được để trống');if(!qrow.topic_id)throw new Error('Câu hỏi chưa được gắn chủ đề');let {data:question,error:qerr}=await db.from('questions').insert(qrow).select().single();if(qerr)throw qerr;let options=['A','B','C','D'].map(k=>({question_id:question.id,option_key:k,content:$('#draft'+k).value.trim()}));let {error:oerr}=await db.from('question_options').insert(options);if(oerr){await db.from('questions').delete().eq('id',question.id);throw oerr}let {error:derr}=await db.from('ai_question_drafts').update({content:qrow.content,options:Object.fromEntries(options.map(o=>[o.option_key,o.content])),correct_answer:qrow.correct_answer,explanation:qrow.explanation,review_status:'approved',approved_question_id:question.id,reviewed_by:state.user.id,reviewed_at:new Date().toISOString()}).eq('id',d.id);if(derr)throw derr;d.review_status='approved';toast('Đã lưu câu hỏi vào ngân hàng');advanceReview(batch,drafts,pos)}catch(ex){err(ex);btn.disabled=false}};
}

async function advanceReview(batch,drafts,pos){let pending=drafts.findIndex((x,i)=>i>pos&&x.review_status==='pending');if(pending<0)pending=drafts.findIndex(x=>x.review_status==='pending');if(pending>=0)return showDraft(batch,drafts,drafts[pending],pending);let {error}=await db.from('ai_generation_batches').update({status:'completed',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',batch.id);if(error)err(error);closeModal();toast('Đã duyệt xong phiên câu hỏi');render()}

async function exams(c){
 if(!state.subjectId){c.replaceChildren(empty());return}let items=await q('exams','*',x=>x.eq('subject_id',state.subjectId).order('created_at',{ascending:false}));c.innerHTML=`<div class="toolbar"><span></span>${canTeach()?'<button id="addExam" class="primary">+ Tạo đề thi</button>':''}</div><div class="panel table-wrap"><table><thead><tr><th>Tên đề</th><th>Loại</th><th>Số câu</th><th>Thời gian</th><th>Trạng thái</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${esc(x.title)}</b><br><small>${esc(x.description||'')}</small></td><td>${esc(x.exam_type)}</td><td>${x.total_questions}</td><td>${x.duration_minutes||'—'} phút</td><td><span class="badge green">${esc(x.status)}</span></td><td class="row-actions">${canTeach()?`<button data-del="${x.id}">Xóa</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;$('#addExam')?.addEventListener('click',examForm);$('tbody').onclick=e=>{let b=e.target.closest('[data-del]');if(b)remove('exams',b.dataset.del,'đề thi')};
}
function examForm(){modal('Tạo đề thi',`<form id="examForm" class="form-grid"><label class="field wide">Tên đề<input name="title" required></label><label class="field wide">Mô tả<textarea name="description"></textarea></label><label class="field">Loại đề<select name="exam_type"><option value="chapter_test">Luyện tập theo chương</option><option value="clo_assessment">Đánh giá CLO</option><option value="final_exam">Thi cuối kỳ</option></select></label><label class="field">Số câu<input name="total_questions" type="number" min="1" required></label><label class="field">Thời gian (phút)<input name="duration_minutes" type="number" min="1"></label><label class="field">Trạng thái<select name="status"><option value="draft">Bản nháp</option><option value="active">Đang hoạt động</option></select></label><div class="form-actions"><button class="primary">Tạo đề</button></div></form>`);$('#examForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));Object.assign(v,{subject_id:state.subjectId,created_by:state.user.id,total_questions:+v.total_questions,duration_minutes:v.duration_minutes?+v.duration_minutes:null,is_clo_assessment:v.exam_type==='clo_assessment'});let {error}=await db.from('exams').insert(v);if(error)return err(error);closeModal();toast('Đã tạo đề thi');render()}}

async function results(c){let exams=state.subjectId?await q('exams','id,title',x=>x.eq('subject_id',state.subjectId)):[];let ids=exams.map(x=>x.id);let attempts=ids.length?await q('exam_attempts','*, profiles:student_id(full_name,mssv)',x=>x.in('exam_id',ids).order('created_at',{ascending:false})):[];let avg=attempts.filter(x=>x.score!=null).reduce((a,b)=>a+Number(b.score),0)/(attempts.filter(x=>x.score!=null).length||1);c.innerHTML=`<div class="stats"><div class="stat"><small>Lượt làm bài</small><b>${attempts.length}</b></div><div class="stat"><small>Đã nộp</small><b>${attempts.filter(x=>x.submitted_at).length}</b></div><div class="stat"><small>Điểm trung bình</small><b>${avg.toFixed(2)}</b></div><div class="stat"><small>Đề có dữ liệu</small><b>${new Set(attempts.map(x=>x.exam_id)).size}</b></div></div><div class="panel table-wrap"><table><thead><tr><th>Sinh viên</th><th>Đề thi</th><th>Lần</th><th>Điểm</th><th>Trạng thái</th></tr></thead><tbody>${attempts.map(x=>`<tr><td>${esc(x.profiles?.full_name||x.student_id)}<br><small>${esc(x.profiles?.mssv||'')}</small></td><td>${esc(exams.find(e=>e.id===x.exam_id)?.title)}</td><td>${x.attempt_number}</td><td><b>${x.score??'—'}</b></td><td><span class="badge ${x.submitted_at?'green':''}">${x.submitted_at?'Đã nộp':'Đang làm'}</span></td></tr>`).join('')}</tbody></table></div>`}

async function users(c){if(role()!=='admin'){c.innerHTML='<div class="panel">Chỉ quản trị viên được truy cập.</div>';return}let [profiles,members]=await Promise.all([q('profiles','*',x=>x.order('full_name')),q('subject_members','*')]);c.innerHTML=`<div class="panel table-wrap"><div class="panel-head"><h3>Tài khoản đã có hồ sơ</h3></div><table><thead><tr><th>Họ tên</th><th>Email / MSSV</th><th>Vai trò hệ thống</th><th>Học phần tham gia</th></tr></thead><tbody>${profiles.map(p=>`<tr><td><b>${esc(p.full_name)}</b></td><td>${esc(p.email)}<br><small>${esc(p.mssv||'')}</small></td><td><span class="badge red">${esc(p.role)}</span></td><td>${members.filter(m=>m.user_id===p.id).length}</td></tr>`).join('')}</tbody></table><p class="hint">Tạo tài khoản đăng nhập mới cần thực hiện trong Supabase Authentication hoặc bằng Edge Function có quyền quản trị; không đặt service_role key trên GitHub Pages.</p></div>`}

async function remove(table,id,label){if(!confirm(`Xóa ${label} này? Dữ liệu liên quan có thể khiến thao tác bị từ chối.`))return;let {error}=await db.from(table).delete().eq('id',id);if(error)return err(error);toast(`Đã xóa ${label}`);if(table==='subjects')await boot(state.user);else render()}
async function removeQuestion(id){if(!confirm('Xóa câu hỏi và các phương án?'))return;let a=await db.from('question_options').delete().eq('question_id',id);if(a.error)return err(a.error);let b=await db.from('questions').delete().eq('id',id);if(b.error)return err(b.error);toast('Đã xóa câu hỏi');render()}
