/* AI-CLO PTITHCM V12.2 — Assessment single-owner engine.
   Step 5A: lifecycle + online-test builder, matrix and atomic frozen design. */
(()=>{
'use strict';

const VERSION='12.2.0-step5a';
const $1=(s,r=document)=>r.querySelector(s);
const $$1=(s,r=document)=>[...r.querySelectorAll(s)];
const esc2=s=>window.esc?esc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const localInput=v=>{if(!v)return'';const d=new Date(v),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)};
const iso=v=>v?new Date(v).toISOString():null;
const isTeacher=()=>typeof canTeach==='function'&&canTeach();
const subjectId=()=>state?.subjectId||null;
const byId=(rows,id)=>rows.find(x=>x.id===id);
const shuf=rows=>{const a=[...rows];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const modeLabel=v=>({common_fixed:'Đề chung cố định',student_fixed:'Đề riêng theo sinh viên',attempt_random:'Rút lại mỗi lần làm'}[v]||'Đề chung cố định');
const structureLabel=v=>v==='chapter_pool'?'CLO chung các mục được chọn':'CLO cho mỗi mục';
const notify=(message,bad=false)=>{if(typeof toast==='function')toast(message,bad);else if(bad&&typeof err==='function')err(new Error(message));};
const showError=e=>{if(typeof err==='function')err(e);else console.error(e)};
const statusMeta=x=>{if(x.status==='draft')return {code:'draft',label:'Bản nháp',className:''};if(x.status==='closed')return {code:'closed',label:'Tạm dừng',className:'red'};const now=Date.now(),opens=x.opens_at?new Date(x.opens_at).getTime():null,closes=x.closes_at?new Date(x.closes_at).getTime():null;if(opens&&now<opens)return {code:'upcoming',label:'Sắp mở',className:''};if(closes&&now>closes)return {code:'expired',label:'Đã hết hạn',className:'red'};return {code:'active',label:'Đang mở',className:'green'}};

async function schemaReady(){try{const {data,error}=await db.rpc('assessment_schema_version');if(error)throw error;return String(data||'')==='12.2'}catch{return false}}
function migrationNotice(c){c.innerHTML=`<div class="panel migration-panel"><h3>Cần hoàn tất Assessment V12.2 trên Supabase</h3><p>Frontend V12.2 chỉ chạy khi backend contract 12.2 đã được cài.</p><ol><li>Mở <b>Supabase → SQL Editor</b>.</li><li>Chạy <code>docs/assessment-v12.2-migration.sql</code>.</li><li>Tải lại trang.</li></ol></div>`}
async function ask(title,message,label='Xác nhận'){if(typeof confirmAction==='function')return !!(await confirmAction(title,message,{confirmLabel:label}));return window.confirm(message)}
async function fetchExams(){const {data,error}=await db.from('exams').select('*').eq('subject_id',subjectId()).order('created_at',{ascending:false});if(error)throw error;return data||[]}
async function fetchAttemptCounts(examIds){const out=new Map();if(!examIds.length)return out;const {data,error}=await db.from('exam_attempts').select('exam_id,submitted_at').in('exam_id',examIds);if(error)throw error;for(const row of data||[]){const x=out.get(row.exam_id)||{all:0,submitted:0};x.all++;if(row.submitted_at)x.submitted++;out.set(row.exam_id,x)}return out}
async function fetchFinalPackages(){try{const {data,error}=await db.from('final_exam_packages').select('id,title,status,updated_at,created_at,metadata,source_scope').eq('subject_id',subjectId()).order('updated_at',{ascending:false});if(error)throw error;return data||[]}catch(e){console.warn('V12.2 final package list unavailable',e);return []}}
async function loadPracticeSets(){const [{data:chapters,error:ce},{data:clos,error:loe}]=await Promise.all([db.from('chapters').select('*').eq('subject_id',subjectId()).order('order_index'),db.from('clos').select('*').eq('subject_id',subjectId()).order('code')]);if(ce)throw ce;if(loe)throw loe;const chIds=(chapters||[]).map(x=>x.id);let topics=[];if(chIds.length){const r=await db.from('topics').select('*').in('chapter_id',chIds).order('order_index');if(r.error)throw r.error;topics=r.data||[]}const qr=await db.from('questions').select('id,subject_id,display_code,chapter_id,topic_id,clo_id,content,correct_answer,explanation,status,question_scope,approval_status,question_options(id,option_key,content)').eq('subject_id',subjectId()).eq('status','active').eq('approval_status','approved');if(qr.error)throw qr.error;const questions=(qr.data||[]).filter(q=>['practice','both'].includes(q.question_scope)&&validOptions(q));return {chapters:chapters||[],topics,clos:clos||[],questions}}
function validOptions(q){const keys=(q.question_options||[]).map(o=>String(o.option_key||'').toUpperCase());return keys.length===4&&new Set(keys).size===4&&['A','B','C','D'].every(k=>keys.includes(k))&&keys.includes(String(q.correct_answer||'').toUpperCase())}
function poolSnapshot(q,sets){return {question_id:q.id,chapter_id:q.chapter_id,chapter_name:byId(sets.chapters,q.chapter_id)?.name||null,topic_id:q.topic_id,topic_name:byId(sets.topics,q.topic_id)?.name||null,clo_id:q.clo_id,clo_code:byId(sets.clos,q.clo_id)?.code||null,content:q.content,correct_answer:String(q.correct_answer||'').toUpperCase(),explanation:q.explanation||null,options:(q.question_options||[]).map(o=>({key:String(o.option_key||'').toUpperCase(),content:o.content})).sort((a,b)=>a.key.localeCompare(b.key))}}

function topTabs(active='online'){return `<div class="v109-tabs assessment-v122-tabs"><button type="button" class="${active==='online'?'active':''}" data-v122-tab="online">Bài kiểm tra trực tuyến</button><button type="button" class="${active==='final'?'active':''}" data-v122-tab="final">Đề thi cuối kỳ</button></div>`}
function onlineTable(items,counts){return `<div class="toolbar"><span class="hint">Mỗi bài có một trang Chi tiết duy nhất.</span><button id="v122CreateExam" class="primary">+ Tạo bài kiểm tra</button></div><div class="panel table-wrap"><table class="assessment-table"><thead><tr><th>Bài kiểm tra</th><th>Cấu trúc</th><th>Chế độ câu</th><th>Thời gian</th><th>Bài làm</th><th>Trạng thái</th><th></th></tr></thead><tbody>${items.map(x=>{const s=statusMeta(x),n=counts.get(x.id)||{all:0,submitted:0};return `<tr><td><button type="button" class="exam-title-link" data-v122-detail="${x.id}"><b>${esc2(x.title||'Bài kiểm tra')}</b></button><br><small>${esc2(x.description||'')}</small></td><td><b>${Number(x.total_questions||0)}</b> câu<br><small>${esc2(structureLabel(x.structure_mode))}</small></td><td><span class="badge">${esc2(modeLabel(x.question_mode))}</span></td><td>${x.duration_minutes||'—'} phút<br><small>${x.opens_at?fmt(x.opens_at):'Khi phát hành'} → ${x.closes_at?fmt(x.closes_at):'Không giới hạn'}</small></td><td><b>${n.submitted}</b> đã nộp<br><small>${n.all} lượt</small></td><td><span class="badge ${s.className}">${s.label}</span></td><td><button type="button" class="primary" data-v122-detail="${x.id}">Chi tiết →</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Chưa có bài kiểm tra.</td></tr>'}</tbody></table></div>`}
function finalTable(items){return `<div class="toolbar"><span class="hint">Đề cuối kỳ chỉ dùng Ngân hàng đề thi – bảo mật.</span><button id="v122CreateFinal" class="primary">+ Tạo đề thi cuối kỳ</button></div><div class="panel table-wrap"><table><thead><tr><th>Hồ sơ đề</th><th>Nguồn câu</th><th>Cập nhật</th><th>Trạng thái</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${esc2(x.title||x.metadata?.title||'Đề thi cuối kỳ')}</b></td><td>Ngân hàng đề thi – bảo mật</td><td>${fmt(x.updated_at||x.created_at)}</td><td><span class="badge ${x.status==='locked'?'green':''}">${esc2(x.status==='locked'?'Đã khóa':x.status==='generated'?'Đã sinh đề':x.status==='reviewing'?'Đang rà soát':'Bản nháp')}</span></td><td><button type="button" class="secondary" data-v122-final="${x.id}">Chi tiết →</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Chưa có hồ sơ đề thi cuối kỳ.</td></tr>'}</tbody></table></div>`}
async function teacherExamList(c){const [items,finals]=await Promise.all([fetchExams(),fetchFinalPackages()]);const counts=await fetchAttemptCounts(items.map(x=>x.id));let active=sessionStorage.getItem(`aiclo:v122:assessment-tab:${subjectId()}`)||'online';if(!['online','final'].includes(active))active='online';const renderTab=tab=>{active=tab;sessionStorage.setItem(`aiclo:v122:assessment-tab:${subjectId()}`,tab);c.innerHTML=`${topTabs(tab)}<div id="v122AssessmentBody">${tab==='online'?onlineTable(items,counts):finalTable(finals)}</div>`;$$1('[data-v122-tab]',c).forEach(b=>b.onclick=()=>renderTab(b.dataset.v122Tab));if(tab==='online')bindOnlineList(c,items);else bindFinalList(c)};renderTab(active)}
function bindOnlineList(root,items){$$1('[data-v122-detail]',root).forEach(b=>b.onclick=()=>{const x=items.find(v=>v.id===b.dataset.v122Detail);if(x)openExamDetail(x)});const add=$1('#v122CreateExam',root);if(add)add.onclick=()=>openExamBuilder(null)}
function bindFinalList(root){const add=$1('#v122CreateFinal',root);if(add)add.onclick=()=>notify('Bước sau sẽ nối Builder đề thi cuối kỳ V12.2 vào nút này.');$$1('[data-v122-final]',root).forEach(b=>b.onclick=()=>notify('Bước sau sẽ nối trang Chi tiết đề cuối kỳ V12.2.'))}

async function setStatus(exam,next){const label=next==='active'?(exam.status==='closed'?'Mở lại':'Phát hành'):'Tạm dừng';const message=next==='closed'?'Sinh viên sẽ không thể bắt đầu lượt mới. Lượt đang làm vẫn được phép tiếp tục.':next==='active'?'Bài sẽ cho phép sinh viên bắt đầu lượt mới theo thời gian mở/đóng đã cấu hình.':'';if(!await ask(label,message,label))return false;const payload={status:next};if(next==='active'&&!exam.published_at)payload.published_at=new Date().toISOString();const {data,error}=await db.from('exams').update(payload).eq('id',exam.id).select('*').single();if(error)throw error;if(!data||data.status!==next)throw new Error(`Supabase chưa đổi trạng thái sang ${next}`);Object.assign(exam,data);notify(label==='Tạm dừng'?'Đã tạm dừng bài kiểm tra':label==='Mở lại'?'Đã mở lại bài kiểm tra':'Đã phát hành bài kiểm tra');return true}
async function deleteExam(exam){const {count,error}=await db.from('exam_attempts').select('id',{count:'exact',head:true}).eq('exam_id',exam.id);if(error)throw error;if(count>0)return notify('Bài đã có lượt làm nên không thể xóa.',true);if(!await ask('Xóa bài kiểm tra',`Xóa “${exam.title||'Bài kiểm tra'}”? Thao tác này không thể hoàn tác.`,'Xóa'))return;const r=await db.from('exams').delete().eq('id',exam.id);if(r.error)throw r.error;notify('Đã xóa bài kiểm tra');await exams($1('#content'))}
function detailActions(exam){if(exam.status==='draft')return `<button id="v122Edit" class="secondary">Chỉnh sửa</button><button id="v122Publish" class="primary">Phát hành</button><button id="v122Delete" class="danger">Xóa</button>`;if(exam.status==='closed')return `<button id="v122Edit" class="secondary">Chỉnh sửa</button><button id="v122Reopen" class="primary">Mở lại</button>`;return `<button id="v122Edit" class="secondary">Chỉnh sửa</button><button id="v122Pause" class="secondary">Tạm dừng</button>`}
async function openExamDetail(examOrId){try{let exam=typeof examOrId==='string'?null:examOrId;if(!exam){const {data,error}=await db.from('exams').select('*').eq('id',examOrId).single();if(error)throw error;exam=data}const {count,error}=await db.from('exam_attempts').select('id',{count:'exact',head:true}).eq('exam_id',exam.id);if(error)throw error;const c=$1('#content');if(!c)return;const s=statusMeta(exam);c.innerHTML=`<div class="assessment-detail-v122"><div class="subpage-head"><div><button id="v122Back" class="secondary compact">← Quay lại</button><small>BÀI KIỂM TRA TRỰC TUYẾN</small><h3>${esc2(exam.title||'Bài kiểm tra')}</h3><p>${esc2(exam.description||'')}</p></div><span class="badge ${s.className}">${s.label}</span></div><section class="panel"><div class="panel-head"><div><h3>Thông tin bài kiểm tra</h3><p class="hint">Một nguồn trạng thái duy nhất từ bảng exams.</p></div><div class="assessment-detail-actions">${detailActions(exam)}</div></div><div class="detail-grid"><div><small>Số câu</small><b>${Number(exam.total_questions||0)}</b></div><div><small>Thời gian</small><b>${exam.duration_minutes||'—'} phút</b></div><div><small>Số lần làm</small><b>${exam.max_attempts||1}</b></div><div><small>Lượt đã tạo</small><b>${count||0}</b></div><div><small>Rút câu</small><b>${esc2(modeLabel(exam.question_mode))}</b></div><div><small>Cấu trúc</small><b>${esc2(structureLabel(exam.structure_mode))}</b></div></div></section><section class="panel"><div class="panel-head"><div><h3>Quản lý bài</h3><p class="hint">Cấu trúc và bộ câu được lưu đồng thời bằng RPC V12.2.</p></div></div><div id="v122DesignSummary"></div></section></div>`;$1('#v122Back')?.addEventListener('click',()=>exams(c));$1('#v122Edit')?.addEventListener('click',()=>openExamBuilder(exam));$1('#v122Publish')?.addEventListener('click',async()=>{try{if(await setStatus(exam,'active'))await openExamDetail(exam)}catch(e){showError(e)}});$1('#v122Pause')?.addEventListener('click',async()=>{try{if(await setStatus(exam,'closed'))await openExamDetail(exam)}catch(e){showError(e)}});$1('#v122Reopen')?.addEventListener('click',async()=>{try{if(await setStatus(exam,'active'))await openExamDetail(exam)}catch(e){showError(e)}});$1('#v122Delete')?.addEventListener('click',async()=>{try{await deleteExam(exam)}catch(e){showError(e)}});await renderDesignSummary(exam)}catch(e){showError(e)}}
async function renderDesignSummary(exam){const box=$1('#v122DesignSummary');if(!box)return;const {data,error}=await db.from('exam_question_pool').select('question_id,chapter_name,topic_name,clo_code').eq('exam_id',exam.id);if(error){box.innerHTML='<p class="hint">Chưa đọc được snapshot bộ câu.</p>';return}const rows=data||[],clo={};for(const r of rows)clo[r.clo_code||'—']=(clo[r.clo_code||'—']||0)+1;box.innerHTML=`<div class="detail-grid"><div><small>Pool đóng băng</small><b>${rows.length} câu</b></div><div><small>CLO trong pool</small><b>${Object.entries(clo).map(([k,v])=>`${esc2(k)}: ${v}`).join(' · ')||'—'}</b></div></div>`}

function defaultBuilder(exam){return {examId:exam?.id||null,exam,settings:{title:exam?.title||'',description:exam?.description||'',duration_minutes:+exam?.duration_minutes||30,max_attempts:+exam?.max_attempts||1,question_mode:exam?.question_mode||'common_fixed',score_policy:exam?.score_policy||'highest',opens_at:localInput(exam?.opens_at),closes_at:localInput(exam?.closes_at),show_answers:!!exam?.show_answers,shuffle_questions:exam?.shuffle_questions!==false,shuffle_options:exam?.shuffle_options!==false,allow_ai_feedback:exam?.allow_ai_feedback!==false,counts_toward_grade:exam?.counts_toward_grade!==false},structureMode:exam?.structure_mode||'topic_clo',selectedChapters:new Set(exam?.chapter_ids||[]),selectedTopics:new Set(exam?.topic_ids||[]),matrix:{...(exam?.question_blueprint?.matrix||{})},selected:[],locked:false,sets:null}}
function matrixKey(mode,rowId,cloId){return `${mode==='chapter_pool'?'c':'t'}:${rowId}:${cloId}`}
function selectedTopicsFor(ctx,chapterId){return ctx.sets.topics.filter(t=>t.chapter_id===chapterId&&ctx.selectedTopics.has(t.id))}
function eligibleForCell(ctx,rowId,cloId){return ctx.sets.questions.filter(q=>q.clo_id===cloId&&(ctx.structureMode==='topic_clo'?q.topic_id===rowId:(q.chapter_id===rowId&&ctx.selectedTopics.has(q.topic_id))))}
function matrixTotal(ctx){return Object.values(ctx.matrix).reduce((s,v)=>s+(+v||0),0)}
function cloCounts(ctx){const out={};for(const c of ctx.sets.clos)out[c.code]=0;for(const [key,n] of Object.entries(ctx.matrix)){const cloId=key.split(':').at(-1),code=byId(ctx.sets.clos,cloId)?.code||cloId;out[code]=(out[code]||0)+(+n||0)}return out}
function designPool(ctx){return ctx.sets.questions.filter(q=>ctx.selectedChapters.has(q.chapter_id)&&ctx.selectedTopics.has(q.topic_id))}
function drawSelection(ctx){const chosen=[],used=new Set();if(ctx.structureMode==='topic_clo'){for(const t of ctx.sets.topics.filter(x=>ctx.selectedTopics.has(x.id))){for(const clo of ctx.sets.clos){const need=+ctx.matrix[matrixKey(ctx.structureMode,t.id,clo.id)]||0;if(!need)continue;const candidates=shuf(eligibleForCell(ctx,t.id,clo.id).filter(q=>!used.has(q.id)));if(candidates.length<need)throw new Error(`Không đủ câu ${clo.code} ở ${t.name}: cần ${need}, có ${candidates.length}`);for(const q of candidates.slice(0,need)){chosen.push(q);used.add(q.id)}}}}else{for(const ch of ctx.sets.chapters.filter(x=>ctx.selectedChapters.has(x.id))){for(const clo of ctx.sets.clos){const need=+ctx.matrix[matrixKey(ctx.structureMode,ch.id,clo.id)]||0;if(!need)continue;const candidates=shuf(eligibleForCell(ctx,ch.id,clo.id).filter(q=>!used.has(q.id)));if(candidates.length<need)throw new Error(`Không đủ câu ${clo.code} ở ${ch.name}: cần ${need}, có ${candidates.length}`);for(const q of candidates.slice(0,need)){chosen.push(q);used.add(q.id)}}}}return chosen}
function validateBuilder(ctx){if(!ctx.settings.title.trim())throw new Error('Cần nhập tên bài kiểm tra');if(!ctx.selectedChapters.size)throw new Error('Cần chọn ít nhất một chương');if(!ctx.selectedTopics.size)throw new Error('Cần chọn ít nhất một mục');const total=matrixTotal(ctx);if(total<1)throw new Error('Ma trận cần ít nhất một câu');for(const [key,n] of Object.entries(ctx.matrix)){if((+n||0)<0)throw new Error('Số câu trong ma trận không hợp lệ');if(!n)continue;const [,rowId,cloId]=key.split(':');const available=eligibleForCell(ctx,rowId,cloId).length;if(available<+n){const clo=byId(ctx.sets.clos,cloId)?.code||'CLO';throw new Error(`${clo}: yêu cầu ${n} nhưng ngân hàng chỉ có ${available} câu phù hợp`)}}return total}
async function openExamBuilder(exam){try{const ctx=defaultBuilder(exam);ctx.sets=await loadPracticeSets();if(!ctx.sets.chapters.length||!ctx.sets.clos.length)return notify('Học phần cần có Chương và CLO trước khi tạo bài.',true);if(!ctx.sets.questions.length)return notify('Ngân hàng luyện tập chưa có câu hỏi được duyệt.',true);if(exam){const {count,error}=await db.from('exam_attempts').select('id',{count:'exact',head:true}).eq('exam_id',exam.id);if(error)throw error;ctx.locked=(count||0)>0;const {data:chosen,error:qe}=await db.from('exam_questions').select('question_id,question_order').eq('exam_id',exam.id).order('question_order');if(qe)throw qe;ctx.selected=(chosen||[]).map(x=>byId(ctx.sets.questions,x.question_id)).filter(Boolean)}renderBuilder(ctx)}catch(e){showError(e)}}
function renderBuilder(ctx){const c=$1('#content');if(!c)return;const total=matrixTotal(ctx);c.innerHTML=`<div class="assessment-builder-v122"><div class="subpage-head"><div><button id="v122BuilderBack" class="secondary compact">← Quay lại</button><small>${ctx.examId?'CHỈNH SỬA':'TẠO'} BÀI KIỂM TRA</small><h3>${esc2(ctx.settings.title||'Bài kiểm tra mới')}</h3><p>Ngân hàng luyện tập – kiểm tra · ${ctx.locked?'Cấu trúc đã khóa vì có lượt làm':'Cấu trúc được lưu atomic cùng pool đóng băng'}</p></div><span class="badge">${total} câu</span></div>${builderInfo(ctx)}${builderStructure(ctx)}${builderQuestions(ctx)}<div class="form-actions assessment-builder-footer"><button id="v122BuilderCancel" class="secondary">Hủy</button><button id="v122Draw" class="secondary" ${ctx.locked?'disabled':''}>Rút câu hỏi</button><button id="v122Save" class="primary">${ctx.examId?'Lưu thay đổi':'Tạo bài kiểm tra'}</button></div></div>`;bindBuilder(ctx)}
function builderInfo(ctx){const s=ctx.settings,dis=ctx.locked?'disabled':'';return `<section class="panel"><div class="panel-head"><div><h3>1. Thông tin</h3><p class="hint">Các trường vận hành vẫn có thể sửa sau khi có lượt làm; cấu trúc đo lường thì không.</p></div></div><div class="form-grid"><label class="field wide">Tên bài<input data-v122-setting="title" value="${esc2(s.title)}" required></label><label class="field wide">Mô tả<textarea data-v122-setting="description">${esc2(s.description)}</textarea></label><label class="field">Thời gian (phút)<input type="number" min="1" max="300" data-v122-setting="duration_minutes" value="${s.duration_minutes}" ${dis}></label><label class="field">Số lần làm<input type="number" min="1" max="20" data-v122-setting="max_attempts" value="${s.max_attempts}"></label><label class="field">Cách rút câu<select data-v122-setting="question_mode" ${dis}><option value="common_fixed" ${s.question_mode==='common_fixed'?'selected':''}>Đề chung cố định</option><option value="student_fixed" ${s.question_mode==='student_fixed'?'selected':''}>Đề riêng theo sinh viên</option><option value="attempt_random" ${s.question_mode==='attempt_random'?'selected':''}>Rút lại mỗi lần làm</option></select></label><label class="field">Cách ghi nhận<select data-v122-setting="score_policy"><option value="highest" ${s.score_policy==='highest'?'selected':''}>Điểm cao nhất</option><option value="latest" ${s.score_policy==='latest'?'selected':''}>Lần cuối</option><option value="average" ${s.score_policy==='average'?'selected':''}>Trung bình</option></select></label><label class="field">Mở từ<input type="datetime-local" data-v122-setting="opens_at" value="${s.opens_at}" ${dis}></label><label class="field">Đóng lúc<input type="datetime-local" data-v122-setting="closes_at" value="${s.closes_at}"></label><div class="field wide assessment-options"><label><input type="checkbox" data-v122-check="show_answers" ${s.show_answers?'checked':''}> Cho xem đáp án sau khi nộp</label><label><input type="checkbox" data-v122-check="shuffle_questions" ${s.shuffle_questions?'checked':''} ${dis}> Trộn thứ tự câu</label><label><input type="checkbox" data-v122-check="shuffle_options" ${s.shuffle_options?'checked':''} ${dis}> Trộn đáp án</label><label><input type="checkbox" data-v122-check="allow_ai_feedback" ${s.allow_ai_feedback?'checked':''}> Cho phép AI nhận xét</label><label><input type="checkbox" data-v122-check="counts_toward_grade" ${s.counts_toward_grade?'checked':''}> Tính vào kết quả CLO học phần</label></div></div></section>`}
function builderStructure(ctx){const chapterRows=ctx.sets.chapters.map(ch=>{const topics=ctx.sets.topics.filter(t=>t.chapter_id===ch.id);return `<div class="v122-scope-chapter"><label><input type="checkbox" data-v122-chapter="${ch.id}" ${ctx.selectedChapters.has(ch.id)?'checked':''} ${ctx.locked?'disabled':''}> <b>${esc2(ch.order_index)}. ${esc2(ch.name)}</b></label><div class="v122-topic-list">${topics.map(t=>`<label><input type="checkbox" data-v122-topic="${t.id}" data-chapter="${ch.id}" ${ctx.selectedTopics.has(t.id)?'checked':''} ${ctx.locked?'disabled':''}> ${esc2(t.name)}</label>`).join('')}</div></div>`}).join('');return `<section class="panel"><div class="panel-head"><div><h3>2. Cấu trúc</h3><p class="hint">Chọn chương và từng mục. Tổng số câu được suy ra trực tiếp từ ma trận.</p></div></div><div class="v122-structure-mode"><label><input type="radio" name="v122StructureMode" value="topic_clo" ${ctx.structureMode==='topic_clo'?'checked':''} ${ctx.locked?'disabled':''}> CLO cho mỗi mục</label><label><input type="radio" name="v122StructureMode" value="chapter_pool" ${ctx.structureMode==='chapter_pool'?'checked':''} ${ctx.locked?'disabled':''}> CLO chung các mục trong chương</label></div><div class="v122-scope">${chapterRows}</div>${matrixEditor(ctx)}</section>`}
function matrixEditor(ctx){if(!ctx.selectedTopics.size)return '<div class="empty"><b>Chưa chọn mục</b><span>Chọn ít nhất một mục để tạo ma trận.</span></div>';let rows='';if(ctx.structureMode==='topic_clo'){for(const ch of ctx.sets.chapters.filter(x=>ctx.selectedChapters.has(x.id))){const ts=selectedTopicsFor(ctx,ch.id);if(!ts.length)continue;rows+=`<tr class="matrix-chapter"><td colspan="${ctx.sets.clos.length+2}"><b>${esc2(ch.order_index)}. ${esc2(ch.name)}</b></td></tr>`+ts.map(t=>`<tr><td>${esc2(t.name)}</td>${ctx.sets.clos.map(clo=>matrixCell(ctx,t.id,clo)).join('')}<td><b>${ctx.sets.clos.reduce((n,clo)=>n+(+ctx.matrix[matrixKey(ctx.structureMode,t.id,clo.id)]||0),0)}</b></td></tr>`).join('')}}else{rows=ctx.sets.chapters.filter(ch=>ctx.selectedChapters.has(ch.id)&&selectedTopicsFor(ctx,ch.id).length).map(ch=>`<tr><td><b>${esc2(ch.order_index)}. ${esc2(ch.name)}</b><small>${selectedTopicsFor(ctx,ch.id).map(t=>esc2(t.name)).join(', ')}</small></td>${ctx.sets.clos.map(clo=>matrixCell(ctx,ch.id,clo)).join('')}<td><b>${ctx.sets.clos.reduce((n,clo)=>n+(+ctx.matrix[matrixKey(ctx.structureMode,ch.id,clo.id)]||0),0)}</b></td></tr>`).join('')}return `<div class="table-wrap"><table class="exam-matrix"><thead><tr><th>${ctx.structureMode==='topic_clo'?'Mục':'Chương'}</th>${ctx.sets.clos.map(c=>`<th>${esc2(c.code)}</th>`).join('')}<th>Tổng</th></tr></thead><tbody>${rows}<tr class="matrix-grand"><td><b>TỔNG</b></td>${ctx.sets.clos.map(c=>`<td><b>${Object.entries(ctx.matrix).filter(([k])=>k.endsWith(`:${c.id}`)).reduce((n,[,v])=>n+(+v||0),0)}</b></td>`).join('')}<td><b>${matrixTotal(ctx)}</b></td></tr></tbody></table></div>`}
function matrixCell(ctx,rowId,clo){const key=matrixKey(ctx.structureMode,rowId,clo.id),n=+ctx.matrix[key]||0,available=eligibleForCell(ctx,rowId,clo.id).length;return `<td><input class="v122-matrix-input" type="number" min="0" max="200" value="${n}" data-key="${key}" ${ctx.locked?'disabled':''}><small>${available} có sẵn</small></td>`}
function builderQuestions(ctx){return `<section class="panel"><div class="panel-head"><div><h3>3. Bộ câu mẫu</h3><p class="hint">Rút câu chỉ ở trình tạo/chỉnh sửa. Lưu sẽ đóng băng toàn bộ pool và bộ câu trong cùng một RPC.</p></div></div>${ctx.selected.length?`<div class="v122-selected-summary"><b>${ctx.selected.length}/${matrixTotal(ctx)} câu đã rút</b> · ${Object.entries(cloCountsFromQuestions(ctx.selected,ctx.sets)).map(([k,v])=>`${esc2(k)}: ${v}`).join(' · ')}</div><ol class="v122-selected-list">${ctx.selected.map(q=>`<li>${esc2(q.content).slice(0,140)} <span class="badge">${esc2(byId(ctx.sets.clos,q.clo_id)?.code||'—')}</span></li>`).join('')}</ol>`:'<div class="empty"><b>Chưa rút câu</b><span>Hoàn tất ma trận rồi nhấn “Rút câu hỏi”.</span></div>'}</section>`}
function cloCountsFromQuestions(rows,sets){const out={};for(const q of rows){const code=byId(sets.clos,q.clo_id)?.code||'—';out[code]=(out[code]||0)+1}return out}
function bindBuilder(ctx){const c=$1('#content');$1('#v122BuilderBack',c).onclick=()=>ctx.examId?openExamDetail(ctx.examId):exams(c);$1('#v122BuilderCancel',c).onclick=()=>ctx.examId?openExamDetail(ctx.examId):exams(c);$$1('[data-v122-setting]',c).forEach(el=>el.oninput=()=>{const k=el.dataset.v122Setting;ctx.settings[k]=el.type==='number'?+el.value:el.value});$$1('[data-v122-check]',c).forEach(el=>el.onchange=()=>ctx.settings[el.dataset.v122Check]=el.checked);$$1('[data-v122-chapter]',c).forEach(el=>el.onchange=()=>{const id=el.dataset.v122Chapter,topics=ctx.sets.topics.filter(t=>t.chapter_id===id);if(el.checked){ctx.selectedChapters.add(id);topics.forEach(t=>ctx.selectedTopics.add(t.id))}else{ctx.selectedChapters.delete(id);topics.forEach(t=>ctx.selectedTopics.delete(t.id))}ctx.selected=[];cleanMatrix(ctx);renderBuilder(ctx)});$$1('[data-v122-topic]',c).forEach(el=>el.onchange=()=>{const id=el.dataset.v122Topic,ch=el.dataset.chapter;if(el.checked)ctx.selectedTopics.add(id);else ctx.selectedTopics.delete(id);const any=ctx.sets.topics.some(t=>t.chapter_id===ch&&ctx.selectedTopics.has(t.id));if(any)ctx.selectedChapters.add(ch);else ctx.selectedChapters.delete(ch);ctx.selected=[];cleanMatrix(ctx);renderBuilder(ctx)});$$1('input[name="v122StructureMode"]',c).forEach(el=>el.onchange=()=>{ctx.structureMode=el.value;ctx.matrix={};ctx.selected=[];renderBuilder(ctx)});$$1('.v122-matrix-input',c).forEach(el=>el.onchange=()=>{ctx.matrix[el.dataset.key]=Math.max(0,+el.value||0);ctx.selected=[];renderBuilder(ctx)});$1('#v122Draw',c).onclick=()=>{try{validateBuilder(ctx);ctx.selected=drawSelection(ctx);renderBuilder(ctx);notify(`Đã rút ${ctx.selected.length} câu phù hợp ma trận`)}catch(e){showError(e)}};$1('#v122Save',c).onclick=()=>saveBuilder(ctx)}
function cleanMatrix(ctx){for(const key of Object.keys(ctx.matrix)){const [,rowId]=key.split(':');if(ctx.structureMode==='topic_clo'&&!ctx.selectedTopics.has(rowId))delete ctx.matrix[key];if(ctx.structureMode==='chapter_pool'&&!ctx.selectedChapters.has(rowId))delete ctx.matrix[key]}}
async function saveBuilder(ctx){let createdId=null,saveBtn=$1('#v122Save');try{if(!ctx.settings.title.trim())throw new Error('Cần nhập tên bài kiểm tra');if(ctx.settings.opens_at&&ctx.settings.closes_at&&new Date(ctx.settings.closes_at)<=new Date(ctx.settings.opens_at))throw new Error('Thời gian đóng phải sau thời gian mở');const total=ctx.locked?(+ctx.exam?.total_questions||0):validateBuilder(ctx);if(!ctx.locked&&ctx.selected.length!==total)throw new Error('Cần nhấn “Rút câu hỏi” sau lần chỉnh ma trận cuối cùng');if(saveBtn){saveBtn.disabled=true;saveBtn.textContent='Đang lưu…'}const settings={title:ctx.settings.title.trim(),description:ctx.settings.description.trim()||null,duration_minutes:+ctx.settings.duration_minutes||30,max_attempts:+ctx.settings.max_attempts||1,question_mode:ctx.settings.question_mode,score_policy:ctx.settings.score_policy,opens_at:iso(ctx.settings.opens_at),closes_at:iso(ctx.settings.closes_at),show_answers:!!ctx.settings.show_answers,shuffle_questions:!!ctx.settings.shuffle_questions,shuffle_options:!!ctx.settings.shuffle_options,allow_ai_feedback:!!ctx.settings.allow_ai_feedback,counts_toward_grade:!!ctx.settings.counts_toward_grade};let examId=ctx.examId;if(!examId){const payload={...settings,subject_id:subjectId(),status:'draft',exam_type:'chapter_test',created_by:state.user.id,total_questions:total,chapter_ids:[...ctx.selectedChapters],topic_ids:[...ctx.selectedTopics],clo_counts:cloCounts(ctx),structure_mode:ctx.structureMode,question_blueprint:{version:1,source:'v12.2',matrix:{...ctx.matrix}}};const r=await db.from('exams').insert(payload).select('*').single();if(r.error)throw r.error;examId=r.data.id;createdId=examId}else{const r=await db.from('exams').update(settings).eq('id',examId).select('*').single();if(r.error)throw r.error}if(!ctx.locked){const pool=designPool(ctx).map(q=>poolSnapshot(q,ctx.sets)),blueprint={version:1,source:'v12.2',matrix:{...ctx.matrix}},r=await db.rpc('replace_exam_design',{p_exam_id:examId,p_structure_mode:ctx.structureMode,p_blueprint:blueprint,p_chapter_ids:[...ctx.selectedChapters],p_topic_ids:[...ctx.selectedTopics],p_clo_counts:cloCounts(ctx),p_total_questions:total,p_pool:pool,p_selected:ctx.selected.map(q=>q.id)});if(r.error)throw r.error}notify(ctx.examId?'Đã lưu thay đổi':'Đã tạo bài kiểm tra');await openExamDetail(examId)}catch(e){if(createdId){try{await db.from('exams').delete().eq('id',createdId)}catch{}}showError(e);if(saveBtn){saveBtn.disabled=false;saveBtn.textContent=ctx.examId?'Lưu thay đổi':'Tạo bài kiểm tra'}}}

async function studentExamList(c){try{const [items,{data:attempts,error}]=await Promise.all([fetchExams(),db.from('exam_attempts').select('*').eq('student_id',state.user.id).order('created_at',{ascending:false})]);if(error)throw error;const visible=items.filter(x=>x.status==='active'||(attempts||[]).some(a=>a.exam_id===x.id&&!a.submitted_at));c.innerHTML=`<div class="student-exam-grid">${visible.map(x=>{const mine=(attempts||[]).filter(a=>a.exam_id===x.id),open=mine.find(a=>!a.submitted_at),s=statusMeta(x);return `<article class="student-exam-card"><div class="student-exam-head"><span class="badge ${s.className}">${s.label}</span><span>${mine.filter(a=>a.submitted_at).length}/${x.max_attempts||1} lượt đã nộp</span></div><h3>${esc2(x.title||'Bài kiểm tra')}</h3><p>${esc2(x.description||'')}</p><div class="student-exam-meta"><span><b>${x.total_questions||0}</b> câu</span><span><b>${x.duration_minutes||'—'}</b> phút</span></div><div class="student-exam-actions">${open?`<button class="primary" data-v122-resume="${x.id}">Tiếp tục làm bài</button>`:x.status==='active'?`<button class="primary" data-v122-start="${x.id}">Làm bài</button>`:'<button class="secondary" disabled>Đang tạm dừng</button>'}</div></article>`}).join('')||'<div class="panel empty">Hiện chưa có bài kiểm tra nào.</div>'}</div>`;$$1('[data-v122-start],[data-v122-resume]',c).forEach(b=>b.onclick=()=>notify('Bước Student Attempt sẽ được nối sau khi Builder ổn định.'))}catch(e){showError(e)}}
async function exams(c){if(!subjectId()){c?.replaceChildren?.(typeof empty==='function'?empty():document.createTextNode('Chưa chọn học phần'));return}if(!await schemaReady())return migrationNotice(c);return isTeacher()?teacherExamList(c):studentExamList(c)}
async function results(c){c.innerHTML='<div class="panel"><h3>Kết quả CLO</h3><p class="hint">Sẽ được nối lại trong bước xử lý score_policy.</p></div>'}
async function teacherClassList(c){return results(c)}
async function openStudentAttemptResult(){notify('Kết quả lượt làm sẽ được nối ở bước Student Attempt.')}
window.exams=exams;
window.results=results;
window.AICLO_ASSESSMENT=Object.freeze({exams,results,teacherClassList,openStudentAttemptResult,openExamDetail,version:VERSION});
})();