/* AI-CLO PTITHCM v10.2 — Gemini fallback, bulk bank import, final-exam workflow. */
(() => {
'use strict';
const onlineExams = exams;
let finalCtx = null;
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').trim().toLowerCase().replace(/\s+/g,' ');
const shuf=a=>{let x=[...a];for(let i=x.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const opts=q=>Object.fromEntries((q.question_options||[]).map(o=>[o.option_key,o.content]));
const today=()=>new Date().toISOString().slice(0,10);
const fileSafe=s=>String(s||'de-thi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'de-thi';
const download=(data,name,type='application/octet-stream')=>{let a=document.createElement('a'),blob=data instanceof Blob?data:new Blob([data],{type});a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)};

window.v102CloForm=function(clo){
 clo=clo||{};
 modal(clo.id?'Sửa CLO':'Tạo CLO',`<form id="v102CloForm" class="form-grid"><label class="field">Mã CLO<input name="code" required value="${esc(clo.code||'')}"></label><label class="field wide">Mô tả đầy đủ <small>Dùng cho Gemini và phân tích học tập</small><textarea name="description" required>${esc(clo.description||'')}</textarea></label><label class="field wide">Mô tả ngắn BM08 <small>Ngắn gọn, dùng trong “Nội dung đánh giá” của BM08</small><textarea name="short_description" required>${esc(clo.short_description||'')}</textarea></label><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary">Lưu CLO</button></div></form>`);
 $('#v102CloForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));let r=clo.id?await db.from('clos').update(v).eq('id',clo.id):await db.from('clos').insert({...v,subject_id:state.subjectId});if(r.error)return err(r.error);closeModal();toast('Đã lưu CLO');render()};
};

function bulkTemplate(sets){
 const sample=[{'Chương':sets.ch[0]?.name||'Chương 1','Chủ đề':sets.topics.find(t=>t.chapter_id===sets.ch[0]?.id)?.name||'Mục 1.1','CLO':sets.clos[0]?.code||'CLO1','Nội dung':'Nội dung câu hỏi','A':'Phương án A','B':'Phương án B','C':'Phương án C','D':'Phương án D','Đáp án':'A','Lời giải':'Giải thích ngắn','Nhóm sử dụng':'practice','Trạng thái':'draft'}];
 const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(sample),'Cau_hoi');
 const ref=[];for(let ch of sets.ch)for(let t of sets.topics.filter(x=>x.chapter_id===ch.id))ref.push({'Chương':ch.name,'Chủ đề':t.name});XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(ref),'Chuong_Chu_de');
 XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(sets.clos.map(c=>({'CLO':c.code,'Mô tả':c.description,'Mô tả ngắn BM08':c.short_description||''}))),'CLO');
 XLSX.writeFile(wb,`Mau-nhap-cau-hoi-${fileSafe(activeSubject()?.name)}.xlsx`);
}
function parseBulkRow(r,sets,rowNo){
 const get=(...names)=>{for(let n of names)if(r[n]!=null)return String(r[n]).trim();return''};
 let chText=get('Chương','Chuong'),topicText=get('Chủ đề','Chu de','Chủ đề/Mục'),cloText=get('CLO').toUpperCase();
 let chapter=sets.ch.find(c=>norm(c.name)===norm(chText)||String(c.order_index)===chText.replace(/\D/g,''));
 let topic=sets.topics.find(t=>t.chapter_id===chapter?.id&&norm(t.name)===norm(topicText));
 let clo=sets.clos.find(c=>String(c.code).toUpperCase()===cloText);
 let content=get('Nội dung','Noi dung'),correct=get('Đáp án','Dap an').toUpperCase().replace(/[^ABCD]/g,'').slice(0,1),options={A:get('A'),B:get('B'),C:get('C'),D:get('D')};
 let errors=[];if(!chapter)errors.push('không tìm thấy Chương');if(!topic)errors.push('không tìm thấy Chủ đề');if(!clo)errors.push('CLO không hợp lệ');if(!content)errors.push('thiếu nội dung');for(let k of ['A','B','C','D'])if(!options[k])errors.push(`thiếu ${k}`);if(!correct)errors.push('đáp án phải A–D');
 let scope=norm(get('Nhóm sử dụng','Nhom su dung')).includes('de thi')||get('Nhóm sử dụng','Nhom su dung')==='secure_exam'?'secure_exam':'practice',ap=get('Trạng thái','Trang thai').toLowerCase();if(!['draft','pending','approved'].includes(ap))ap='draft';
 return {rowNo,chapter,topic,clo,content,options,correct_answer:correct,explanation:get('Lời giải','Loi giai')||null,question_scope:scope,approval_status:ap,errors};
}
window.v102BulkImportQuestions=function(sets){
 modal('Nhập hàng loạt câu hỏi',`<div class="v102-import"><p>Ưu tiên file <b>.xlsx</b>. Mỗi dòng là một câu, có Chương, Chủ đề, CLO, nội dung, A–D và đáp án.</p><div class="v102-import-actions"><button id="downloadBulkTemplate" class="secondary">↓ Tải Excel mẫu</button><label class="file-button">Chọn file Excel<input id="bulkQuestionFile" type="file" accept=".xlsx,.xls" hidden></label></div><div id="bulkPreview"><p class="hint">Hệ thống sẽ kiểm tra trước, chưa lưu ngay vào ngân hàng.</p></div></div>`);
 $('#downloadBulkTemplate').onclick=()=>bulkTemplate(sets);
 $('#bulkQuestionFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}),parsed=rows.filter(r=>Object.values(r).some(v=>String(v).trim())).map((r,i)=>parseBulkRow(r,sets,i+2)),bad=parsed.filter(x=>x.errors.length);$('#bulkPreview').innerHTML=`<div class="import-summary"><b>Đã đọc ${parsed.length} câu</b><span class="badge green">Hợp lệ ${parsed.length-bad.length}</span><span class="badge ${bad.length?'red':''}">Có lỗi ${bad.length}</span></div><div class="table-wrap"><table><thead><tr><th>Dòng</th><th>Chương · Chủ đề</th><th>CLO</th><th>Nội dung</th><th>Kiểm tra</th></tr></thead><tbody>${parsed.map(x=>`<tr class="${x.errors.length?'import-bad':''}"><td>${x.rowNo}</td><td>${esc(x.chapter?.name||'—')}<br><small>${esc(x.topic?.name||'—')}</small></td><td>${esc(x.clo?.code||'—')}</td><td>${esc(x.content.slice(0,100))}</td><td>${x.errors.length?esc(x.errors.join('; ')):'✓ Hợp lệ'}</td></tr>`).join('')}</tbody></table></div><div class="form-actions"><button id="confirmBulkImport" class="primary" ${parsed.length===bad.length?'disabled':''}>Nhập ${parsed.length-bad.length} câu hợp lệ</button></div>`;
 $('#confirmBulkImport').onclick=async()=>{let good=parsed.filter(x=>!x.errors.length);if(!good.length)return;let b=$('#confirmBulkImport');b.disabled=true;b.textContent='Đang nhập…';let ok=0;for(let x of good){let approval=x.approval_status,{data:qrow,error:qerr}=await db.from('questions').insert({subject_id:state.subjectId,chapter_id:x.chapter.id,topic_id:x.topic.id,clo_id:x.clo.id,content:x.content,correct_answer:x.correct_answer,explanation:x.explanation,created_by:state.user.id,status:approval==='approved'?'active':'draft',question_scope:x.question_scope,approval_status:approval,approved_by:approval==='approved'?state.user.id:null,approved_at:approval==='approved'?new Date().toISOString():null}).select().single();if(qerr){console.warn(qerr);continue}let {error:oerr}=await db.from('question_options').insert(['A','B','C','D'].map(k=>({question_id:qrow.id,option_key:k,content:x.options[k]})));if(!oerr)ok++}closeModal();toast(`Đã nhập ${ok}/${good.length} câu`);render()};
 }catch(ex){err(ex)}};
};

async function finalSets(){let sets=await v96QuestionSets();sets.items=sets.items.filter(q=>q.approval_status==='approved'&&q.status==='active');return sets}
function matrixHtml(sets){return `<div class="v102-matrix table-wrap"><table><thead><tr><th>Chương / Mục</th>${sets.clos.map(c=>`<th>${esc(c.code)}</th>`).join('')}<th>Tổng</th></tr></thead><tbody>${sets.ch.map(ch=>{let ts=sets.topics.filter(t=>t.chapter_id===ch.id);return `<tr class="matrix-chapter"><td colspan="${sets.clos.length+2}"><b>${esc(ch.order_index)}. ${esc(ch.name)}</b></td></tr>${ts.map(t=>`<tr><td>${esc(t.name)}</td>${sets.clos.map(c=>`<td><input class="matrix-count" type="number" min="0" max="200" value="0" data-chapter="${ch.id}" data-topic="${t.id}" data-clo="${c.id}"></td>`).join('')}<td class="matrix-row-total">0</td></tr>`).join('')}`}).join('')}<tr class="matrix-grand"><td><b>TỔNG ĐỀ</b></td>${sets.clos.map(c=>`<td data-clo-total="${c.id}"><b>0</b></td>`).join('')}<td id="matrixGrandTotal"><b>0</b></td></tr></tbody></table></div>`}
function readMatrix(){return $$('.matrix-count').map(i=>({chapter_id:i.dataset.chapter,topic_id:i.dataset.topic,clo_id:i.dataset.clo,count:+i.value||0})).filter(x=>x.count>0)}
function updateMatrixTotals(){let grand=0,clos={};$$('.v102-matrix tbody tr').forEach(tr=>{let inputs=$$('.matrix-count',tr);if(inputs.length){let n=inputs.reduce((s,i)=>s+(+i.value||0),0);tr.querySelector('.matrix-row-total').textContent=n;grand+=n;inputs.forEach(i=>clos[i.dataset.clo]=(clos[i.dataset.clo]||0)+(+i.value||0))}});for(let [id,n] of Object.entries(clos))$(`[data-clo-total="${id}"] b`).textContent=n;$('#matrixGrandTotal b').textContent=grand}
function metadataFromForm(f){let v=Object.fromEntries(new FormData(f));v.variant_codes=String(v.variant_codes||'101,102,103,104').split(/[,;\s]+/).filter(Boolean);v.duration_minutes=+v.duration_minutes||0;return v}
async function finalExamWizard(){
 let sets=await finalSets();finalCtx={sets,selected:[],metadata:null,matrix:[],source:'secure_exam'};
 questionWorkspace('Tạo đề thi cuối kỳ','BM06 → duyệt câu hỏi → chốt → tạo 4 BM07/BM08 và đáp án CLO.',`<form id="finalExamForm" class="v102-final-form"><section class="panel"><div class="panel-head"><h3>1. Thông tin hồ sơ đề thi</h3></div><div class="form-grid"><label class="field wide">Tên bộ đề<input name="title" required value="Đề thi kết thúc học phần ${esc(activeSubject()?.name||'')}"></label><label class="field">Mã học phần<input name="course_code"></label><label class="field">Số tín chỉ<input name="credits" type="number" min="0"></label><label class="field">Kỳ thi<input name="semester" value="${esc(activeSubject()?.semester||'')}"></label><label class="field">Năm học<input name="academic_year" value="${esc(activeSubject()?.academic_year||'')}"></label><label class="field">Ngày thi<input name="exam_date" type="date"></label><label class="field">Ca thi<input name="shift"></label><label class="field">Thời gian (phút)<input name="duration_minutes" type="number" min="1" value="80"></label><label class="field">Nhóm thi<input name="exam_groups" placeholder="D25CQDT01-N_09, ..."></label><label class="field">Khoa<input name="faculty" value="CƠ BẢN 2"></label><label class="field">Bộ môn<input name="department" value="TOÁN"></label><label class="field">Giảng viên ra đề<input name="lecturer" value="${esc(state.profile?.full_name||'')}"></label><label class="field">Trưởng bộ môn<input name="head_of_department"></label><label class="field">Mã đề<input name="variant_codes" value="101, 102, 103, 104"></label><label class="field">Nguồn câu hỏi<select name="source_scope"><option value="secure_exam">Chỉ Ngân hàng đề thi</option><option value="practice">Chỉ Ngân hàng luyện tập</option><option value="both">Cả hai ngân hàng</option></select></label></div></section><section class="panel"><div class="panel-head"><h3>2. Ma trận BM06 chi tiết theo Chương · Mục · CLO</h3><span class="hint">Nhập số câu vào từng ô.</span></div>${matrixHtml(sets)}<div id="matrixAvailability" class="bank-check"></div></section><div class="form-actions"><button type="button" id="cancelFinal" class="secondary">Hủy</button><button class="primary">Rút câu và chuyển sang duyệt</button></div></form>`);
 $$('.matrix-count').forEach(i=>i.oninput=()=>{updateMatrixTotals();checkAvailability()});$('#finalExamForm [name=source_scope]').onchange=checkAvailability;$('#cancelFinal').onclick=()=>render();
 function checkAvailability(){let source=$('#finalExamForm [name=source_scope]').value,req=readMatrix(),rows=req.map(r=>{let pool=sets.items.filter(q=>q.topic_id===r.topic_id&&q.clo_id===r.clo_id&&(source==='both'||q.question_scope===source));return {...r,available:pool.length}}),ok=rows.every(x=>x.available>=x.count)&&rows.reduce((s,x)=>s+x.count,0)>0;$('#matrixAvailability').innerHTML=`<div class="bank-check-head ${ok?'ok':'warn'}"><b>${ok?'✓ Ngân hàng đủ câu':'! Có ô ma trận chưa đủ câu'}</b><span>${rows.reduce((s,x)=>s+x.count,0)} câu</span></div><div class="bank-check-items">${rows.map(x=>{let t=sets.topics.find(z=>z.id===x.topic_id),c=sets.clos.find(z=>z.id===x.clo_id);return `<span class="${x.available<x.count?'bad':''}">${esc(t?.name)} · ${esc(c?.code)}: cần ${x.count} / có ${x.available}</span>`}).join('')}</div>`;return ok}
 updateMatrixTotals();checkAvailability();
 $('#finalExamForm').onsubmit=e=>{e.preventDefault();if(!checkAvailability())return toast('Ngân hàng chưa đủ câu theo ma trận',true);let meta=metadataFromForm(e.target),matrix=readMatrix(),source=meta.source_scope,selected=[];for(let r of matrix){let pool=shuf(sets.items.filter(q=>q.topic_id===r.topic_id&&q.clo_id===r.clo_id&&(source==='both'||q.question_scope===source)));selected.push(...pool.slice(0,r.count))}finalCtx={sets,selected,metadata:meta,matrix,source};reviewFinalQuestions()};
}
function qCard(q,i,sets){let o=opts(q),ch=sets.ch.find(x=>x.id===q.chapter_id),t=sets.topics.find(x=>x.id===q.topic_id),c=sets.clos.find(x=>x.id===q.clo_id);return `<article class="v102-review-card" data-review-index="${i}"><div class="review-card-head"><div><b>Câu ${i+1}</b><span class="badge red">${esc(c?.code||'')}</span><span class="badge">${esc(ch?.name||'')}</span><span class="badge">${esc(t?.name||'')}</span>${String(q.id).startsWith('ai:')?'<span class="badge ai-badge">Gemini mới</span>':''}</div><div><button class="secondary" data-replace="${i}">Đổi câu</button><button class="ai-btn" data-gemini="${i}">✦ Gemini sinh câu này</button></div></div><div class="detail-question">${esc(q.content)}</div><div class="detail-options">${['A','B','C','D'].map(k=>`<div class="${q.correct_answer===k?'correct':''}"><b>${k}</b><span>${esc(o[k]||'')}</span></div>`).join('')}</div></article>`}
function reviewFinalQuestions(){let {sets,selected,matrix}=finalCtx,summary=sets.clos.map(c=>[c.code,selected.filter(q=>q.clo_id===c.id).length]);questionWorkspace('Duyệt đề gốc trước khi tạo 4 mã đề',`${selected.length} câu · giảng viên quyết định cuối cùng.`,`<div class="v102-review-summary"><b>Đề gốc: ${selected.length} câu</b>${summary.map(([c,n])=>`<span class="badge">${esc(c)}: ${n}</span>`).join('')}<span class="hint">Đổi câu luôn giữ đúng Mục + CLO + nguồn của ô ma trận.</span></div><div id="finalReviewList">${selected.map((q,i)=>qCard(q,i,sets)).join('')}</div><div class="sticky-final-actions"><button id="backMatrix" class="secondary">← Quay lại ma trận</button><button id="approveFinalBase" class="primary">✓ Duyệt đề gốc và tạo 4 mã đề</button></div>`);renderMath($('#finalReviewList'));$('#backMatrix').onclick=finalExamWizard;$('#finalReviewList').onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.replace!=null)replaceFinalQuestion(+b.dataset.replace);if(b.dataset.gemini!=null)geminiFinalQuestion(+b.dataset.gemini,b)};$('#approveFinalBase').onclick=finalizeVariants}
async function replaceFinalQuestion(i){let old=finalCtx.selected[i],pool=finalCtx.sets.items.filter(q=>q.topic_id===old.topic_id&&q.clo_id===old.clo_id&&(finalCtx.source==='both'||q.question_scope===finalCtx.source)&&!finalCtx.selected.some(s=>s.id===q.id));if(!pool.length)return toast('Không còn câu khác phù hợp trong ngân hàng',true);finalCtx.selected[i]=shuf(pool)[0];toast(`Đã đổi Câu ${i+1}`);reviewFinalQuestions()}
async function geminiFinalQuestion(i,button){let old=finalCtx.selected[i];button.disabled=true;button.textContent='✦ Đang sinh…';try{let {data,error}=await db.functions.invoke('generate-one-question',{body:{subject_id:state.subjectId,chapter_id:old.chapter_id,topic_id:old.topic_id,clo_id:old.clo_id}});if(error){let x;try{x=await error.context?.json()}catch{}throw new Error(x?.error||error.message)}if(!data?.success)throw new Error(data?.error||'Gemini không tạo được câu');let g=data.question;modal(`Gemini đề xuất cho Câu ${i+1}`,`<div class="v102-ai-preview"><div class="detail-question">${esc(g.content)}</div><div class="detail-options">${['A','B','C','D'].map(k=>`<div class="${g.correct_answer===k?'correct':''}"><b>${k}</b><span>${esc(g.options[k])}</span></div>`).join('')}</div><p><b>Lời giải:</b> ${esc(g.explanation||'')}</p><label><input id="saveGeneratedBank" type="checkbox"> Lưu câu này vào Ngân hàng đề thi sau khi dùng</label><small>Model thực tế: ${esc(data.model||'Gemini')}</small><div class="form-actions"><button id="cancelGenerated" class="secondary">Hủy</button><button id="regenerateOne" class="secondary">Sinh lại</button><button id="useGenerated" class="primary">Dùng câu này</button></div></div>`);renderMath($('#modalBody'));$('#cancelGenerated').onclick=()=>{closeModal();reviewFinalQuestions()};$('#regenerateOne').onclick=()=>{closeModal();geminiFinalQuestion(i,button)};$('#useGenerated').onclick=async()=>{let q={id:`ai:${crypto.randomUUID()}`,subject_id:state.subjectId,chapter_id:old.chapter_id,topic_id:old.topic_id,clo_id:old.clo_id,content:g.content,correct_answer:g.correct_answer,explanation:g.explanation,question_scope:'secure_exam',approval_status:'approved',question_options:['A','B','C','D'].map(k=>({option_key:k,content:g.options[k]}))};if($('#saveGeneratedBank').checked){let {data:saved,error:qe}=await db.from('questions').insert({subject_id:state.subjectId,chapter_id:q.chapter_id,topic_id:q.topic_id,clo_id:q.clo_id,content:q.content,correct_answer:q.correct_answer,explanation:q.explanation,created_by:state.user.id,status:'active',question_scope:'secure_exam',approval_status:'approved',approved_by:state.user.id,approved_at:new Date().toISOString()}).select().single();if(qe)return err(qe);let {error:oe}=await db.from('question_options').insert(q.question_options.map(o=>({...o,question_id:saved.id})));if(oe)return err(oe);q={...q,id:saved.id}}finalCtx.selected[i]=q;closeModal();reviewFinalQuestions()}}catch(ex){err(ex);button.disabled=false;button.textContent='✦ Gemini sinh câu này'}}
function makeVariants(){let codes=finalCtx.metadata.variant_codes?.length?finalCtx.metadata.variant_codes:['101','102','103','104'];return codes.map(code=>({code,questions:shuf(finalCtx.selected).map(q=>{let old=opts(q),oldKeys=shuf(['A','B','C','D']),newKeys=['A','B','C','D'],options={},correct='';oldKeys.forEach((ok,j)=>{options[newKeys[j]]=old[ok];if(ok===q.correct_answer)correct=newKeys[j]});return {source_question_id:q.id,content:q.content,options,correct_answer:correct,clo_id:q.clo_id,chapter_id:q.chapter_id,topic_id:q.topic_id,explanation:q.explanation||''}})}))}
async function finalizeVariants(){if(!await confirmAction('Chốt đề thi',`Tạo ${finalCtx.metadata.variant_codes.length||4} mã đề từ ${finalCtx.selected.length} câu đã duyệt?`,{confirmLabel:'Tạo mã đề'}))return;let variants=makeVariants(),payload={subject_id:state.subjectId,title:finalCtx.metadata.title,metadata:finalCtx.metadata,matrix:finalCtx.matrix,source_scope:finalCtx.source,selected_questions:finalCtx.selected,variants,status:'generated',created_by:state.user.id,updated_at:new Date().toISOString()},{data:pack,error}=await db.from('final_exam_packages').insert(payload).select().single();if(error){if(/final_exam_packages/i.test(error.message||''))return toast('Hãy chạy supabase/v10.2-upgrade.sql trước',true);return err(error)}finalCtx.package=pack;finalCtx.variants=variants;showGeneratedPackage()}
function bm06Html(ctx){let m=ctx.metadata,sets=ctx.sets,total=ctx.selected.length,point=total?10/total:0,rows=sets.ch.map(ch=>{let qs=ctx.selected.filter(q=>q.chapter_id===ch.id),cloCells=sets.clos.map(c=>{let n=qs.filter(q=>q.clo_id===c.id).length;return `${n} Câu<br>${(n*point).toFixed(2).replace('.',',')} điểm<br>${(n*100/total).toFixed(1).replace('.',',')} %`});return `<tr><td>Chương ${esc(ch.order_index)}. ${esc(ch.name)}</td><td>${qs.length} Câu<br>${(qs.length*point).toFixed(2).replace('.',',')} điểm<br>${(qs.length*100/total).toFixed(1).replace('.',',')} %</td>${cloCells.map(x=>`<td>${x}</td>`).join('')}<td>${qs.length} Câu</td></tr>`}).join('');return `<!doctype html><meta charset="utf-8"><style>body{font-family:"Times New Roman";font-size:12pt}table{border-collapse:collapse;width:100%}td,th{border:1px solid #000;padding:6px;text-align:center}td:first-child{text-align:left}h2{text-align:center}</style><p><b>KHOA ${esc(m.faculty||'')}</b><br><b>BỘ MÔN ${esc(m.department||'')}</b></p><h2>MA TRẬN ĐỀ THI</h2><p>Kỳ thi: ${esc(m.semester||'')} &nbsp; Năm học: ${esc(m.academic_year||'')}<br>Tên học phần: ${esc(activeSubject()?.name||'')} &nbsp; Mã học phần: ${esc(m.course_code||'')}<br>Ngày thi: ${esc(m.exam_date||'')} &nbsp; Ca thi: ${esc(m.shift||'')} &nbsp; Thời gian: ${m.duration_minutes||''} phút</p><table><tr><th>Tên chương/bài/chủ đề</th><th>Phân phối tỉ lệ</th>${sets.clos.map(c=>`<th>${esc(c.code)}</th>`).join('')}<th>Cộng</th></tr>${rows}<tr><th>TỔNG CỘNG</th><th>${total} Câu<br>10 điểm<br>100%</th>${sets.clos.map(c=>{let n=ctx.selected.filter(q=>q.clo_id===c.id).length;return `<th>${n} Câu<br>${(n*point).toFixed(2).replace('.',',')} điểm<br>${(n*100/total).toFixed(1).replace('.',',')}%</th>`}).join('')}<th>${total} Câu</th></tr></table><p style="text-align:center;margin-top:40px"><b>TRƯỞNG BỘ MÔN</b><br><br><br>${esc(m.head_of_department||'')}</p>`}
const latexHeader=s=>String(s||'').replace(/([%&_#])/g,'\\$1');
function bm07Tex(ctx,v){let m=ctx.metadata,total=v.questions.length,point=total?10/total:0;return `\\documentclass[12pt,a4paper]{article}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T5]{fontenc}\n\\usepackage[vietnamese]{babel}\n\\usepackage{amsmath,amssymb,geometry,enumitem,fancyhdr}\n\\geometry{margin=1.7cm}\n\\pagestyle{fancy}\\fancyhf{}\\fancyfoot[L]{Mã đề ${latexHeader(v.code)}}\\fancyfoot[R]{Trang \\thepage}\n\\begin{document}\n\\begin{center}{\\bfseries HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG\\\\CƠ SỞ TẠI THÀNH PHỐ HỒ CHÍ MINH\\\\KHOA: ${latexHeader(m.faculty)} \\quad BỘ MÔN: ${latexHeader(m.department)}}\\vspace{3mm}\\\\{\\Large\\bfseries ĐỀ THI KẾT THÚC HỌC PHẦN}\\\\(Hình thức trắc nghiệm)\\end{center}\n\\noindent Kỳ thi: ${latexHeader(m.semester)} \\hfill Năm học: ${latexHeader(m.academic_year)}\\\\Học phần: ${latexHeader(activeSubject()?.name)} \\quad Mã học phần: ${latexHeader(m.course_code)}\\\\Ngày thi: ${latexHeader(m.exam_date)} \\quad Ca thi: ${latexHeader(m.shift)} \\quad Thời gian: ${m.duration_minutes} phút\\\\Nhóm thi: ${latexHeader(m.exam_groups)}\\\\\\textbf{Đề số: ${latexHeader(v.code)}}\\vspace{3mm}\n${v.questions.map((q,i)=>{let c=ctx.sets.clos.find(x=>x.id===q.clo_id);return `\\noindent\\textbf{Câu ${i+1}.} (${latexHeader(c?.code)}: ${point.toFixed(2).replace('.',',')}đ) ${q.content}\n\\begin{enumerate}[label=\\Alph*.,leftmargin=1.1cm,itemsep=1mm]${['A','B','C','D'].map(k=>`\\item ${q.options[k]}`).join('\n')}\\end{enumerate}`}).join('\n')}\n\\begin{center}-- Hết --\\end{center}\n\\noindent Họ tên SV: \\dotfill \\quad Lớp: \\dotfill \\quad Phòng thi: \\dotfill\\\\Ký tên: \\dotfill\\vspace{12mm}\n\\begin{minipage}{.48\\textwidth}\\centering\\textbf{TRƯỞNG BỘ MÔN DUYỆT ĐỀ THI}\\\\(Ký và ghi rõ họ tên)\\vspace{15mm}\\\\${latexHeader(m.head_of_department)}\\end{minipage}\\hfill\\begin{minipage}{.48\\textwidth}\\centering\\textbf{GIẢNG VIÊN RA ĐỀ}\\\\(Ký và ghi rõ họ tên)\\vspace{15mm}\\\\${latexHeader(m.lecturer)}\\end{minipage}\n\\end{document}`}
function bm08Html(ctx,v){let m=ctx.metadata,total=v.questions.length,point=total?10/total:0,first=v.questions.slice(0,20),second=v.questions.slice(20),ansBlock=arr=>`<tr><th>Câu</th>${arr.map((q,i)=>`<td>${v.questions.indexOf(q)+1}</td>`).join('')}</tr><tr><th>Đáp án</th>${arr.map(q=>`<td>${q.correct_answer}</td>`).join('')}</tr>`,cloRows=ctx.sets.clos.map(c=>{let nums=v.questions.map((q,i)=>q.clo_id===c.id?i+1:null).filter(Boolean),n=nums.length;return `<tr><td>${esc(c.code)}</td><td>${esc(c.short_description||c.description||'')}</td><td>Câu ${nums.join(', ')}</td><td>${(n*100/total).toFixed(1).replace('.',',')}%</td><td>${(n*point).toFixed(2).replace('.',',')}</td><td>…</td><td></td></tr>`}).join('');return `<!doctype html><meta charset="utf-8"><style>body{font-family:"Times New Roman";font-size:12pt}table{border-collapse:collapse;width:100%;margin:8px 0}td,th{border:1px solid #000;padding:5px;text-align:center}</style><h3>Mẫu BM08<br>Mẫu đáp án/hướng dẫn chấm (phiếu chấm theo CLO)-Mã đề ${esc(v.code)}</h3><p>Tên học phần: ${esc(activeSubject()?.name||'')}<br>Mã học phần: ${esc(m.course_code||'')}<br>Số tín chỉ: ${esc(m.credits||'')}<br>Học kỳ/Năm học: ${esc(m.semester||'')}/${esc(m.academic_year||'')}<br>Giảng viên ra đề: ${esc(m.lecturer||'')}<br>Ngày thi: ${esc(m.exam_date||'')} &nbsp; Ca thi: ${esc(m.shift||'')}</p><b>1. Đáp án & Thang điểm:</b><p>Mỗi câu ${point.toFixed(2).replace('.',',')} điểm.</p><table>${ansBlock(first)}${second.length?ansBlock(second):''}</table><b>2. Phiếu chấm theo CLO</b><table><tr><th>CLO</th><th>Nội dung đánh giá</th><th>Câu hỏi liên quan</th><th>Trọng số (%)</th><th>Điểm tối đa</th><th>Điểm đạt được</th><th>Nhận xét</th></tr>${cloRows}</table><p>Tổng điểm: ……/10</p><p><b>3. Ghi chú cho giảng viên chấm thi</b></p><p>Điểm làm tròn đến 0,1.</p>`}
function answerWorkbook(ctx){let wb=XLSX.utils.book_new(),codes=ctx.variants.map(v=>v.code),n=Math.max(...ctx.variants.map(v=>v.questions.length)),rows=[];for(let i=0;i<n;i++){let r={'Câu':i+1};for(let v of ctx.variants){let q=v.questions[i],c=ctx.sets.clos.find(x=>x.id===q?.clo_id);r[v.code]=q?.correct_answer||'';r[`CLO_${v.code}`]=c?.code||''}rows.push(r)}let ws=XLSX.utils.json_to_sheet(rows,{header:['Câu',...codes.flatMap(c=>[c,`CLO_${c}`])]});XLSX.utils.book_append_sheet(wb,ws,'Doc');let horizontal=[];for(let v of ctx.variants){let ans={'Mã đề':v.code},clo={'Mã đề':`${v.code}_CLO`};v.questions.forEach((q,i)=>{ans[`Câu ${i+1}`]=q.correct_answer;clo[`Câu ${i+1}`]=ctx.sets.clos.find(c=>c.id===q.clo_id)?.code||''});horizontal.push(ans,clo)}XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(horizontal),'Ngang');return wb}
async function exportPackageZip(ctx){if(!window.JSZip)return toast('Không tải được thư viện ZIP',true);let zip=new JSZip(),m=ctx.metadata;zip.file('BM06_Ma_tran_de_thi.doc',bm06Html(ctx));for(let v of ctx.variants){zip.file(`BM07/De_${v.code}.tex`,bm07Tex(ctx,v));zip.file(`BM08/BM08_${v.code}.doc`,bm08Html(ctx,v))}let ab=XLSX.write(answerWorkbook(ctx),{bookType:'xlsx',type:'array'});zip.file('Dap_an_CLO.xlsx',ab);zip.file('README.txt','AI-CLO PTITHCM V10.2\nBM06: ma trận đề thi\nBM07: đề thi TeX theo từng mã đề\nBM08: đáp án/phiếu chấm theo CLO; phần Nội dung đánh giá dùng clos.short_description.\nDap_an_CLO.xlsx: dùng trực tiếp cho ứng dụng chấm thi CLO.');download(await zip.generateAsync({type:'blob'}),`Ho-so-de-thi-${fileSafe(activeSubject()?.name)}-${today()}.zip`)}
function showGeneratedPackage(){let ctx=finalCtx;questionWorkspace('Đã tạo bộ đề cuối kỳ',`${ctx.variants.length} mã đề · ${ctx.selected.length} câu · đã chốt.`,`<section class="panel v102-generated"><div class="panel-head"><h3>${esc(ctx.metadata.title)}</h3><span class="badge green">Đã tạo ${ctx.variants.length} mã đề</span></div><div class="variant-grid">${ctx.variants.map(v=>`<article><b>Mã đề ${esc(v.code)}</b><span>${v.questions.length} câu</span><button class="secondary" data-tex="${v.code}">Tải TeX BM07</button><button class="secondary" data-bm08="${v.code}">Tải BM08</button></article>`).join('')}</div><div class="form-actions"><button id="downloadBM06" class="secondary">BM06</button><button id="downloadAnswers" class="secondary">Dap_an_CLO.xlsx</button><button id="downloadFinalZip" class="primary">Tải toàn bộ hồ sơ ZIP</button></div><p class="hint">BM08 lấy mô tả CLO từ trường <code>short_description</code>. File Excel đáp án được sinh từ đúng cấu trúc 4 đề đã trộn.</p></section>`);$$('[data-tex]').forEach(b=>b.onclick=()=>{let v=ctx.variants.find(x=>x.code===b.dataset.tex);download(bm07Tex(ctx,v),`BM07_De_${v.code}.tex`,'text/plain;charset=utf-8')});$$('[data-bm08]').forEach(b=>b.onclick=()=>{let v=ctx.variants.find(x=>x.code===b.dataset.bm08);download(bm08Html(ctx,v),`BM08_${v.code}.doc`,'application/msword')});$('#downloadBM06').onclick=()=>download(bm06Html(ctx),'BM06_Ma_tran_de_thi.doc','application/msword');$('#downloadAnswers').onclick=()=>XLSX.writeFile(answerWorkbook(ctx),'Dap_an_CLO.xlsx');$('#downloadFinalZip').onclick=()=>exportPackageZip(ctx)}
async function reopenPackage(id){let {data,error}=await db.from('final_exam_packages').select('*').eq('id',id).single();if(error)return err(error);let sets=await finalSets();finalCtx={sets,selected:data.selected_questions||[],metadata:data.metadata||{},matrix:data.matrix||[],source:data.source_scope,variants:data.variants||[],package:data};showGeneratedPackage()}

exams=async function(c){
 if(!canTeach())return onlineExams(c);
 await onlineExams(c);
 let toolbar=c.querySelector('.toolbar');if(toolbar){let b=document.createElement('button');b.id='createFinalExam';b.className='ai-btn';b.textContent='✎ Tạo đề thi cuối kỳ';toolbar.appendChild(b);b.onclick=finalExamWizard}
 let section=document.createElement('section');section.className='panel v102-final-list';section.innerHTML='<div class="panel-head"><h3>Hồ sơ đề thi cuối kỳ</h3><span class="hint">BM06 · BM07 · BM08 · đáp án CLO</span></div><div id="finalPackageRows"><p class="hint">Đang tải…</p></div>';c.appendChild(section);
 let {data,error}=await db.from('final_exam_packages').select('id,title,status,created_at,metadata').eq('subject_id',state.subjectId).order('created_at',{ascending:false});if(error){$('#finalPackageRows').innerHTML=`<p class="hint">Chưa bật chức năng V10.2. Chạy <code>supabase/v10.2-upgrade.sql</code> để dùng đề cuối kỳ.</p>`;return}$('#finalPackageRows').innerHTML=(data||[]).map(x=>`<div class="final-package-row"><div><b>${esc(x.title)}</b><small>${new Date(x.created_at).toLocaleString('vi-VN')} · Mã đề ${(x.metadata?.variant_codes||[]).join(', ')}</small></div><span class="badge green">${esc(x.status)}</span><button class="secondary" data-open-final="${x.id}">Mở / Xuất</button></div>`).join('')||'<p class="hint">Chưa có bộ đề cuối kỳ.</p>';$$('[data-open-final]').forEach(b=>b.onclick=()=>reopenPackage(b.dataset.openFinal));
};

// Hiển thị model thực tế trong lịch sử AI nếu giao diện cũ đã tải dữ liệu model.
const oldHistory=window.aiHistory;
if(oldHistory){window.aiHistory=async function(){await oldHistory();setTimeout(()=>{},0)}}
})();
