/* AI-CLO PTITHCM v10.5 — two question-bank tabs, persistent filters, secure exam-bank separation. */
let v105QuestionBankTab='practice';
const v105ScopeLabel=v=>v==='secure_exam'?'Đề thi - bảo mật':v==='both'?'Cả hai ngân hàng':'Luyện tập - kiểm tra';
const v105BankTitle=v=>v==='secure_exam'?'Ngân hàng đề thi - bảo mật':'Ngân hàng luyện tập - kiểm tra';
function v105QuestionInBank(scope,bank){return bank==='both'?['practice','secure_exam','both'].includes(scope):(scope===bank||scope==='both')}
window.v105QuestionInBank=v105QuestionInBank;
window.AICLO_V105={version:'10.5',activeBank:()=>v105QuestionBankTab,inBank:v105QuestionInBank};

function v105ScopeChooser(value='practice',name='question_scope'){
 value=['practice','secure_exam','both'].includes(value)?value:'practice';
 return `<fieldset class="v105-scope-chooser wide"><legend>Nơi lưu câu hỏi</legend><div class="v105-scope-options">
  <label class="v105-scope-option"><input type="radio" name="${name}" value="practice" ${value==='practice'?'checked':''}><span><b>Luyện tập - kiểm tra</b><small>Dùng cho luyện tập và bài kiểm tra trực tuyến.</small></span></label>
  <label class="v105-scope-option secure"><input type="radio" name="${name}" value="secure_exam" ${value==='secure_exam'?'checked':''}><span><b>🔒 Ngân hàng đề thi</b><small>Bảo mật, chỉ dùng cho đề thi cuối kỳ/chính thức.</small></span></label>
  <label class="v105-scope-option both"><input type="radio" name="${name}" value="both" ${value==='both'?'checked':''}><span><b>Cả hai</b><small>Hiển thị ở cả hai ngân hàng; được dùng cho kiểm tra và đề thi.</small></span></label>
 </div></fieldset>`;
}

captureQuestionFilters=function(){
 if(!$('#qsearch'))return;
 let search=String($('#qsearch').value||'').trim();if(search.toLowerCase()==='all')search='';
 v94QuestionFilters={search,chapter:$('#qchapterFilter')?.value||'all',topic:$('#qtopicFilter')?.value||'all',clo:$('#qcloFilter')?.value||'all',approval:$('#qapprovalFilter')?.value||'all',creator:$('#qcreatorFilter')?.value||'all',bank:v105QuestionBankTab,scrollY:window.scrollY||0};
};
backToQuestionList=async function(){
 state.view='questions';let f=v94QuestionFilters||{};v105QuestionBankTab=f.bank==='secure_exam'?'secure_exam':'practice';await render();
 let search=String(f.search||'');if(search.toLowerCase()==='all')search='';
 if($('#qsearch'))$('#qsearch').value=search;
 if($('#qchapterFilter')){$('#qchapterFilter').value=f.chapter||'all';$('#qchapterFilter').dispatchEvent(new Event('change'))}
 if($('#qtopicFilter'))$('#qtopicFilter').value=f.topic||'all';
 if($('#qcloFilter'))$('#qcloFilter').value=f.clo||'all';
 if($('#qapprovalFilter'))$('#qapprovalFilter').value=f.approval||'all';
 if($('#qcreatorFilter'))$('#qcreatorFilter').value=f.creator||'all';
 $('#qsearch')?.dispatchEvent(new Event('input'));
 requestAnimationFrame(()=>window.scrollTo({top:Number(f.scrollY)||0,behavior:'auto'}));
};

questions=async function(c){
 if(!canTeach()){c.innerHTML='<div class="panel">Sinh viên không được truy cập ngân hàng câu hỏi.</div>';return}
 if(!state.subjectId){c.replaceChildren(empty());return}
 let sets;try{sets=await v96QuestionSets()}catch(ex){if(/question_scope|approval_status/i.test(ex.message||'')){c.innerHTML='<div class="panel migration-panel"><h3>Cần cập nhật Supabase V10.5</h3><p>Chạy <code>supabase/v10.5-upgrade.sql</code>, sau đó tải lại trang.</p></div>';return}throw ex}
 let {items,ch,topics,clos}=sets,creators=[];try{let ids=[...new Set(items.map(x=>x.created_by).filter(Boolean))];if(ids.length)creators=await q('profiles','id,full_name,email',x=>x.in('id',ids).order('full_name'))}catch{}
 const practiceCount=items.filter(x=>v105QuestionInBank(x.question_scope,'practice')).length,secureCount=items.filter(x=>v105QuestionInBank(x.question_scope,'secure_exam')).length;
 c.innerHTML=`<div class="v105-bank-tabs" role="tablist" aria-label="Loại ngân hàng câu hỏi">
   <button type="button" class="v105-bank-tab ${v105QuestionBankTab==='practice'?'active':''}" data-bank-tab="practice"><span>Luyện tập - kiểm tra</span><b>${practiceCount}</b></button>
   <button type="button" class="v105-bank-tab secure ${v105QuestionBankTab==='secure_exam'?'active':''}" data-bank-tab="secure_exam"><span>🔒 Ngân hàng đề thi - bảo mật</span><b>${secureCount}</b></button>
  </div>
  <div id="v105BankNote" class="v105-bank-note"></div>
  <div class="question-tools v96-question-tools v105-question-tools"><input id="qsearch" placeholder="Tìm theo mã hoặc nội dung…"><select id="qchapterFilter"><option value="all">Tất cả chương</option>${ch.map(x=>`<option value="${x.id}">${esc(x.order_index)}. ${esc(x.name)}</option>`).join('')}</select><select id="qtopicFilter"><option value="all">Tất cả chủ đề</option></select><select id="qcloFilter"><option value="all">Tất cả CLO</option>${clos.map(x=>`<option value="${x.id}">${esc(x.code)}</option>`).join('')}</select><select id="qapprovalFilter"><option value="all">Mọi trạng thái duyệt</option><option value="draft">Bản nháp</option><option value="pending">Chờ duyệt</option><option value="approved">Đã duyệt</option><option value="archived">Lưu trữ</option></select><select id="qcreatorFilter"><option value="all">Tất cả người tạo</option><option value="mine">Câu hỏi của tôi</option>${creators.filter(x=>x.id!==state.user.id).map(x=>`<option value="${x.id}">${esc(x.full_name||x.email)}</option>`).join('')}</select></div>
  <div class="toolbar bank-actions"><span id="questionCount" class="hint"></span><button id="scanDuplicates" class="secondary">Kiểm tra trùng</button><button id="aiHistory" class="secondary">Phiên AI</button><button id="generateAI" class="ai-btn">✦ Tạo bằng Gemini</button><button id="bulkImportQ" class="secondary">⇧ Nhập hàng loạt</button><button id="addQ" class="primary">+ Thêm câu hỏi</button></div>
  <div id="bulkQuestionBar" class="bulk-question-bar hidden"><b><span id="selectedQuestionCount">0</span> câu đã chọn</b><button data-bulk-scope="practice" class="secondary">Lưu ở Luyện tập</button><button data-bulk-scope="secure_exam" class="secondary">Lưu ở Đề thi</button><button data-bulk-scope="both" class="secondary">Lưu ở Cả hai</button><button id="clearQuestionSelection" class="secondary">Bỏ chọn</button></div>
  <div class="panel table-wrap question-table v105-question-table"><table><thead><tr><th class="select-col"></th><th>Mã câu</th><th>Nội dung</th><th>Chương · Chủ đề</th><th>Phân loại</th><th></th></tr></thead><tbody id="qrows"></tbody></table></div>`;
 const selected=new Set();
 const note=()=>{$('#v105BankNote').innerHTML=v105QuestionBankTab==='secure_exam'?`<b>🔒 Ngân hàng đề thi - bảo mật</b><span>Câu hỏi tại đây dành cho đề thi cuối kỳ/chính thức. Câu chỉ thuộc ngân hàng này <strong>không thể dùng cho bài kiểm tra trực tuyến</strong>.</span>`:`<b>Ngân hàng luyện tập - kiểm tra</b><span>Câu hỏi tại đây có thể dùng cho luyện tập và bài kiểm tra trực tuyến. Câu được lưu “Cả hai” cũng xuất hiện tại đây.</span>`};
 const fillTopics=()=>{let cid=$('#qchapterFilter').value,allowed=cid==='all'?topics:topics.filter(t=>t.chapter_id===cid),old=$('#qtopicFilter').value;$('#qtopicFilter').innerHTML='<option value="all">Tất cả chủ đề</option>'+allowed.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(allowed.some(x=>x.id===old))$('#qtopicFilter').value=old};
 const updateBulk=()=>{$('#selectedQuestionCount').textContent=selected.size;$('#bulkQuestionBar').classList.toggle('hidden',!selected.size)};
 const filtered=()=>{let search=String($('#qsearch').value||'').trim().toLowerCase();if(search==='all'){search='';$('#qsearch').value=''}let cid=$('#qchapterFilter').value,tid=$('#qtopicFilter').value,cloid=$('#qcloFilter').value,approval=$('#qapprovalFilter').value,creator=$('#qcreatorFilter').value;return items.filter(x=>v105QuestionInBank(x.question_scope,v105QuestionBankTab)&&(!search||String(x.content||'').toLowerCase().includes(search)||questionCode(x.id).toLowerCase().includes(search))&&(cid==='all'||x.chapter_id===cid)&&(tid==='all'||x.topic_id===tid)&&(cloid==='all'||x.clo_id===cloid)&&(approval==='all'||x.approval_status===approval)&&(creator==='all'||x.created_by===(creator==='mine'?state.user.id:creator)))};
 const draw=()=>{note();$$('[data-bank-tab]').forEach(b=>b.classList.toggle('active',b.dataset.bankTab===v105QuestionBankTab));let bankTotal=items.filter(x=>v105QuestionInBank(x.question_scope,v105QuestionBankTab)).length,list=filtered();$('#questionCount').textContent=`Hiển thị ${list.length}/${bankTotal} câu`;$('#qrows').innerHTML=list.map(x=>{let chapter=ch.find(z=>z.id===x.chapter_id),topic=topics.find(z=>z.id===x.topic_id),clo=clos.find(z=>z.id===x.clo_id),manage=v96CanManage(x),scope=v105ScopeLabel(x.question_scope);return `<tr><td class="select-col">${manage?`<input type="checkbox" data-select-question="${x.id}" ${selected.has(x.id)?'checked':''} aria-label="Chọn ${questionCode(x.id)}">`:''}</td><td class="q-code-cell"><button class="question-code" data-detail="${x.id}">${questionCode(x.id)}</button>${v105QuestionBankTab==='secure_exam'?'<span class="secure-lock" title="Ngân hàng đề thi bảo mật">🔒</span>':''}<br><span class="badge red question-clo">${esc(clo?.code||'—')}</span></td><td class="q-content-cell"><button class="question-summary" data-detail="${x.id}">${esc(x.content)}</button></td><td class="q-structure-cell"><b>${esc(chapter?.name||'—')}</b><small>${esc(topic?.name||'—')}</small></td><td class="q-class-cell"><span class="badge ${x.question_scope==='secure_exam'?'secure':x.question_scope==='both'?'both-bank':''}">${x.question_scope==='secure_exam'?'🔒 ':''}${esc(scope)}</span><br><span class="badge ${x.approval_status==='approved'?'green':x.approval_status==='archived'?'':'red'} approval-badge">${esc(v96ApprovalLabel(x.approval_status))}</span></td><td class="row-actions"><button data-detail="${x.id}">Chi tiết</button><button data-analysis="${x.id}">Phân tích</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">Không có câu hỏi phù hợp.</td></tr>';renderMath($('#qrows'));updateBulk()};
 fillTopics();draw();
 $('#qsearch').oninput=draw;$('#qchapterFilter').onchange=()=>{fillTopics();draw()};['#qtopicFilter','#qcloFilter','#qapprovalFilter','#qcreatorFilter'].forEach(s=>$(s).onchange=draw);
 $$('[data-bank-tab]').forEach(b=>b.onclick=()=>{captureQuestionFilters();v105QuestionBankTab=b.dataset.bankTab;selected.clear();if(v94QuestionFilters)v94QuestionFilters.bank=v105QuestionBankTab;draw()});
 $('#qrows').onclick=e=>{let check=e.target.closest('[data-select-question]');if(check){check.checked?selected.add(check.dataset.selectQuestion):selected.delete(check.dataset.selectQuestion);updateBulk();return}let b=e.target.closest('button');if(!b)return;let item=items.find(x=>x.id===(b.dataset.detail||b.dataset.analysis));if(b.dataset.detail)v96QuestionDetail(item,sets);if(b.dataset.analysis)v95QuestionAnalysis(item)};
 $('#clearQuestionSelection').onclick=()=>{selected.clear();draw()};
 $$('[data-bulk-scope]').forEach(b=>b.onclick=async()=>{if(!selected.size)return;if(!await confirmAction('Đổi nơi lưu câu hỏi',`Cập nhật ${selected.size} câu thành “${v105ScopeLabel(b.dataset.bulkScope)}”?`,{confirmLabel:'Cập nhật'}))return;let {error}=await db.from('questions').update({question_scope:b.dataset.bulkScope,updated_at:new Date().toISOString()}).in('id',[...selected]);if(error)return err(error);toast('Đã cập nhật nơi lưu câu hỏi');render()});
 $('#addQ').onclick=()=>v96QuestionForm(null,sets);$('#bulkImportQ').onclick=()=>window.v102BulkImportQuestions?.(sets);$('#generateAI').onclick=()=>aiGenerateForm(sets);$('#aiHistory').onclick=aiHistory;$('#scanDuplicates').onclick=()=>v96ScanDuplicates(items.filter(x=>v105QuestionInBank(x.question_scope,v105QuestionBankTab)));
};

v96QuestionForm=async function(x={},sets){
 x=x||{};captureQuestionFilters();let opts=Object.fromEntries((x.question_options||[]).map(o=>[o.option_key,o.content])),manage=!x.id||v96CanManage(x);if(!manage)return toast('Chỉ người tạo hoặc Admin được sửa câu hỏi. Hãy gửi đề nghị chỉnh sửa.',true);
 let initialScope=x.question_scope||v105QuestionBankTab;
 questionWorkspace(x.id?'Sửa câu hỏi':'Thêm câu hỏi',x.id?'Bản hiện tại sẽ được lưu vào lịch sử trước khi cập nhật.':'Chọn rõ ngân hàng lưu câu hỏi trước khi xác nhận.',`<div class="question-edit-page"><form id="qForm" class="form-grid"><label class="field wide">Nội dung<textarea name="content" required>${esc(x.content||'')}</textarea></label><label class="field">Chương<select name="chapter_id" id="qchapter" required>${sets.ch.map(v=>`<option value="${v.id}" ${v.id===x.chapter_id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label class="field">Chủ đề<select name="topic_id" id="qtopic" required></select></label><label class="field">CLO<select name="clo_id" required>${sets.clos.map(v=>`<option value="${v.id}" ${v.id===x.clo_id?'selected':''}>${esc(v.code)} — ${esc(v.description)}</option>`).join('')}</select></label><label class="field">Đáp án đúng<select name="correct_answer">${['A','B','C','D'].map(v=>`<option ${v===x.correct_answer?'selected':''}>${v}</option>`).join('')}</select></label><label class="field">Trạng thái duyệt<select name="approval_status"><option value="draft">Bản nháp</option><option value="pending" ${x.approval_status==='pending'?'selected':''}>Chờ duyệt</option><option value="approved" ${x.approval_status==='approved'?'selected':''}>Đã duyệt</option><option value="archived" ${x.approval_status==='archived'?'selected':''}>Lưu trữ</option></select></label>${v105ScopeChooser(initialScope)}<div class="wide option-grid">${['A','B','C','D'].map(v=>`<label class="field">Phương án ${v}<input name="opt_${v}" required value="${esc(opts[v]||'')}"></label>`).join('')}</div><label class="field wide">Lời giải<textarea name="explanation">${esc(x.explanation||'')}</textarea></label><div class="form-actions"><button id="cancelQuestionEdit" class="secondary" type="button">Hủy</button><button class="primary" id="saveQuestion">Lưu câu hỏi</button></div></form></div>`);
 const topicSelect=()=>{$('#qtopic').innerHTML=sets.topics.filter(t=>t.chapter_id===$('#qchapter').value).map(t=>`<option value="${t.id}" ${t.id===x.topic_id?'selected':''}>${esc(t.name)}</option>`).join('')};topicSelect();$('#qchapter').onchange=topicSelect;$('#cancelQuestionEdit').onclick=backToQuestionList;
 $('#qForm').onsubmit=async e=>{e.preventDefault();let btn=$('#saveQuestion'),v=Object.fromEntries(new FormData(e.target)),optionRows=['A','B','C','D'].map(k=>({option_key:k,content:String(v['opt_'+k]||'').trim()}));['A','B','C','D'].forEach(k=>delete v['opt_'+k]);btn.disabled=true;btn.textContent='Đang kiểm tra…';try{let {data:similar,error:similarError}=await db.rpc('find_similar_questions',{p_subject_id:state.subjectId,p_content:v.content,p_exclude_id:x.id||null,p_limit:3});if(similarError)throw similarError;if(similar?.length&&similar[0].similarity_score>=.72){let top=similar[0];if(!await confirmAction('Phát hiện câu hỏi tương tự',`${top.code} có độ tương đồng ${Math.round(top.similarity_score*100)}%. Bạn vẫn muốn lưu?`,{confirmLabel:'Vẫn lưu'})){btn.disabled=false;btn.textContent='Lưu câu hỏi';return}}v.status=v.approval_status==='approved'?'active':'draft';v.updated_at=new Date().toISOString();if(v.approval_status==='approved'){v.approved_by=state.user.id;v.approved_at=new Date().toISOString()}else{v.approved_by=null;v.approved_at=null}let id=x.id;if(id){let archived=await db.rpc('archive_question_revision',{p_question_id:id});if(archived.error)throw archived.error;let r=await db.from('questions').update(v).eq('id',id).select().single();if(r.error)throw r.error;let d=await db.from('question_options').delete().eq('question_id',id);if(d.error)throw d.error}else{Object.assign(v,{subject_id:state.subjectId,created_by:state.user.id});let r=await db.from('questions').insert(v).select().single();if(r.error)throw r.error;id=r.data.id}let o=await db.from('question_options').insert(optionRows.map(z=>({...z,question_id:id})));if(o.error)throw o.error;window.logActivity?.(x.id?'update':'create','question',id,(x.id?'Cập nhật: ':'Tạo: ')+v.content.slice(0,120));if(v94QuestionFilters){v94QuestionFilters.bank=v.question_scope==='secure_exam'?'secure_exam':v.question_scope==='practice'?'practice':v105QuestionBankTab}toast(x.id?'Đã cập nhật câu hỏi':'Đã tạo câu hỏi');await backToQuestionList()}catch(ex){err(ex);btn.disabled=false;btn.textContent='Lưu câu hỏi'}};
};

v96QuestionDetail=async function(x,sets){
 captureQuestionFilters();let opts=Object.fromEntries((x.question_options||[]).map(o=>[o.option_key,o.content])),chapter=sets.ch.find(v=>v.id===x.chapter_id),topic=sets.topics.find(v=>v.id===x.topic_id),clo=sets.clos.find(v=>v.id===x.clo_id),manage=v96CanManage(x);
 questionWorkspace(`${questionCode(x.id)} · Chi tiết câu hỏi`,'Xem nội dung, nơi lưu, người tạo và lịch sử cập nhật.',`<div id="v105Detail" class="question-detail"><div class="detail-meta"><span class="badge red">${esc(clo?.code||'—')}</span><span class="badge">${esc(chapter?.name||'—')}</span><span class="badge">${esc(topic?.name||'—')}</span><span class="badge ${x.question_scope==='secure_exam'?'secure':x.question_scope==='both'?'both-bank':''}">${x.question_scope==='secure_exam'?'🔒 ':''}${esc(v105ScopeLabel(x.question_scope))}</span><span class="badge ${x.approval_status==='approved'?'green':'red'}">${esc(v96ApprovalLabel(x.approval_status))}</span></div><div id="v105Audit" class="question-audit"><div><small>Người tạo</small><b>Đang tải…</b></div><div><small>Ngày tạo</small><b>${v96Date(x.created_at)}</b></div><div><small>Cập nhật gần nhất</small><b>${v96Date(x.updated_at||x.created_at)}</b></div></div><div class="detail-question">${esc(x.content)}</div><div class="detail-options">${['A','B','C','D'].map(k=>`<div class="${x.correct_answer===k?'correct':''}"><b>${k}</b><span>${esc(opts[k]||'')}</span></div>`).join('')}</div><div class="detail-explanation"><b>Lời giải</b><p>${esc(x.explanation||'Chưa có lời giải.')}</p></div>${manage?`<section class="classification-box v105-classification"><h4>Quản lý câu hỏi</h4><label class="field">Nơi lưu<select id="detailScope"><option value="practice" ${x.question_scope==='practice'?'selected':''}>Luyện tập - kiểm tra</option><option value="secure_exam" ${x.question_scope==='secure_exam'?'selected':''}>🔒 Ngân hàng đề thi</option><option value="both" ${x.question_scope==='both'?'selected':''}>Cả hai ngân hàng</option></select></label><label class="field">Trạng thái duyệt<select id="detailApproval"><option value="draft">Bản nháp</option><option value="pending" ${x.approval_status==='pending'?'selected':''}>Chờ duyệt</option><option value="approved" ${x.approval_status==='approved'?'selected':''}>Đã duyệt</option><option value="archived" ${x.approval_status==='archived'?'selected':''}>Lưu trữ</option></select></label><button id="saveClassification" class="secondary">Cập nhật phân loại</button></section>`:''}<h4>Đề nghị chỉnh sửa</h4><div id="v105Requests"><p class="hint">Đang tải…</p></div><h4>Lịch sử chỉnh sửa</h4><div id="v105Revisions"><p class="hint">Đang tải…</p></div><div class="account-actions">${manage?'<button id="detailDeleteQuestion" class="danger">Xóa câu hỏi</button><button id="detailEditQuestion" class="primary">Sửa câu hỏi</button>':'<span class="hint">Chỉ người tạo hoặc Admin được sửa/xóa.</span>'}</div></div>`);
 $('#detailEditQuestion')?.addEventListener('click',()=>v96QuestionForm(x,sets));$('#detailDeleteQuestion')?.addEventListener('click',async()=>{if(await confirmAction('Xóa câu hỏi',`Xóa ${questionCode(x.id)}?`,{confirmLabel:'Xóa',danger:true}))await removeQuestion(x.id)});$('#saveClassification')?.addEventListener('click',async()=>{let approval=$('#detailApproval').value,scope=$('#detailScope').value;if(x.question_scope==='secure_exam'&&['practice','both'].includes(scope)&&!await confirmAction('Cho phép dùng trong kiểm tra','Câu hỏi sẽ xuất hiện trong Ngân hàng luyện tập - kiểm tra và có thể được dùng cho bài kiểm tra trực tuyến.',{confirmLabel:'Cập nhật'}))return;let {error}=await db.from('questions').update({question_scope:scope,approval_status:approval,status:approval==='approved'?'active':'draft',approved_by:approval==='approved'?state.user.id:null,approved_at:approval==='approved'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',x.id);if(error)return err(error);toast('Đã cập nhật phân loại');backToQuestionList()});renderMath($('#v105Detail'));
 try{let [revisions,requests,members]=await Promise.all([q('question_revisions','revision_no,changed_at,changed_by',z=>z.eq('question_id',x.id).order('revision_no',{ascending:false})),q('question_edit_requests','id,requested_by,assigned_to,message,status,created_at',z=>z.eq('question_id',x.id).order('created_at',{ascending:false})),q('subject_members','user_id,role',z=>z.eq('subject_id',state.subjectId))]),teacherIds=members.filter(m=>['teacher','lecturer','giangvien'].includes(m.role)).map(m=>m.user_id),profiles=await v10Profiles([x.created_by,...teacherIds,...revisions.map(r=>r.changed_by),...requests.flatMap(r=>[r.requested_by,r.assigned_to])]),creator=profiles.get(x.created_by),colleagues=teacherIds.map(id=>profiles.get(id)).filter(Boolean);$('#v105Audit').innerHTML=`<div><small>Người tạo</small><b>${esc(creator?.full_name||creator?.email||'Chưa xác định')}</b></div><div><small>Ngày tạo</small><b>${v96Date(x.created_at)}</b></div><div><small>Cập nhật gần nhất</small><b>${v96Date(x.updated_at||x.created_at)}</b></div>`;$('#v105Requests').innerHTML=`<form id="editRequestForm" class="edit-request-form"><select name="assigned_to"><option value="">Gửi chung cho đồng nghiệp</option>${colleagues.filter(p=>p.id!==state.user.id).map(p=>`<option value="${p.id}">${esc(p.full_name||p.email)}</option>`).join('')}</select><textarea name="message" required maxlength="1200" placeholder="Ghi đề nghị đồng nghiệp xem và chỉnh sửa…"></textarea><button class="secondary">Gửi đề nghị</button></form><div class="request-list">${requests.map(r=>{let a=profiles.get(r.requested_by),to=profiles.get(r.assigned_to);return `<article><div><b>${esc(a?.full_name||a?.email||'Người dùng')}</b><span class="badge">${esc(r.status)}</span></div><p>${esc(r.message)}</p><small>${v96Date(r.created_at)}${to?' · Gửi '+esc(to.full_name||to.email):''}</small></article>`}).join('')||'<p class="hint">Chưa có đề nghị chỉnh sửa.</p>'}</div>`;$('#v105Revisions').innerHTML=`<div class="revision-list">${revisions.map(r=>{let p=profiles.get(r.changed_by);return `<div class="revision-row"><b>Lần ${r.revision_no}</b><span>${esc(p?.full_name||p?.email||'Người dùng')}</span><small>${v96Date(r.changed_at)}</small></div>`}).join('')||'<p class="hint">Chưa có lịch sử chỉnh sửa.</p>'}</div>`;$('#editRequestForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target)),{error}=await db.from('question_edit_requests').insert({question_id:x.id,requested_by:state.user.id,assigned_to:v.assigned_to||null,message:v.message.trim()});if(error)return err(error);toast('Đã gửi đề nghị chỉnh sửa');v96QuestionDetail(x,sets)}}catch(ex){console.warn(ex);$('#v105Requests').innerHTML='<p class="hint">Chưa tải được đề nghị chỉnh sửa.</p>';$('#v105Revisions').innerHTML='<p class="hint">Chưa tải được lịch sử chỉnh sửa.</p>'}
};

/* Gemini review: teacher chooses the destination bank for every approved draft. */
showDraft=function(batch,drafts,d,pos){
 let approved=drafts.filter(x=>x.review_status==='approved').length,rejected=drafts.filter(x=>x.review_status==='rejected').length,defaultScope=v105QuestionBankTab;
 questionWorkspace('Duyệt câu hỏi Gemini',`Câu ${pos+1}/${drafts.length} · chỉnh sửa và chọn nơi lưu trước khi xác nhận.`,`<div class="review-wrap v10-review-page"><div class="review-progress"><b>Câu ${pos+1}/${drafts.length}</b><span>Đã lưu: ${approved} · Bỏ qua: ${rejected} · Chờ duyệt: ${drafts.length-approved-rejected}</span></div><div class="review-tags"><span class="badge red">${esc(batch.clos?.code)}</span><span class="badge">${esc(batch.chapters?.name)}</span><span class="badge ${d.review_status==='approved'?'green':''}">${esc(d.review_status)}</span></div><div class="ai-note"><b>Xem trước công thức</b><div>${esc(d.content)}</div>${['A','B','C','D'].map(k=>`<div><b>${k}.</b> ${esc(d.options?.[k]||'')}</div>`).join('')}${d.explanation?`<div><b>Giải thích:</b> ${esc(d.explanation)}</div>`:''}</div><label class="field">Nội dung<textarea id="draftContent">${esc(d.content)}</textarea></label><div class="review-options">${['A','B','C','D'].map(k=>`<label class="${d.correct_answer===k?'correct':''}"><b>${k}</b><input id="draft${k}" value="${esc(d.options?.[k])}"></label>`).join('')}</div><label class="field">Đáp án đúng<select id="draftCorrect">${['A','B','C','D'].map(k=>`<option ${d.correct_answer===k?'selected':''}>${k}</option>`).join('')}</select></label><label class="field">Giải thích<textarea id="draftExplanation">${esc(d.explanation||'')}</textarea></label>${v105ScopeChooser(defaultScope,'draft_scope')}<div class="review-actions"><button class="secondary" id="prevDraft" ${pos===0?'disabled':''}>← Trước</button><button class="danger" id="rejectDraft">Bỏ qua</button><button class="primary" id="approveDraft">Xác nhận và lưu</button><button class="secondary" id="nextDraft" ${pos===drafts.length-1?'disabled':''}>Sau →</button></div></div>`);
 $('#prevDraft').onclick=()=>showDraft(batch,drafts,drafts[pos-1],pos-1);$('#nextDraft').onclick=()=>showDraft(batch,drafts,drafts[pos+1],pos+1);$('#rejectDraft').onclick=async()=>{let {error}=await db.from('ai_question_drafts').update({review_status:'rejected',reviewed_by:state.user.id,reviewed_at:new Date().toISOString()}).eq('id',d.id);if(error)return err(error);d.review_status='rejected';toast('Đã bỏ qua câu hỏi');advanceReview(batch,drafts,pos)};
 $('#approveDraft').onclick=async()=>{let btn=$('#approveDraft');btn.disabled=true;try{let scope=document.querySelector('input[name="draft_scope"]:checked')?.value||'practice',qrow={subject_id:batch.subject_id,chapter_id:batch.chapter_id,topic_id:d.topic_id||batch.topic_id,clo_id:batch.clo_id,content:$('#draftContent').value.trim(),explanation:$('#draftExplanation').value.trim()||null,correct_answer:$('#draftCorrect').value,created_by:state.user.id,status:'active',question_scope:scope,approval_status:'approved',approved_by:state.user.id,approved_at:new Date().toISOString()};if(!qrow.content||!qrow.topic_id)throw new Error('Câu hỏi cần có nội dung và chủ đề');let {data:question,error:qerr}=await db.from('questions').insert(qrow).select().single();if(qerr)throw qerr;let options=['A','B','C','D'].map(k=>({question_id:question.id,option_key:k,content:$('#draft'+k).value.trim()})),{error:oerr}=await db.from('question_options').insert(options);if(oerr)throw oerr;let {error:derr}=await db.from('ai_question_drafts').update({content:qrow.content,options:Object.fromEntries(options.map(o=>[o.option_key,o.content])),correct_answer:qrow.correct_answer,explanation:qrow.explanation,review_status:'approved',approved_question_id:question.id,reviewed_by:state.user.id,reviewed_at:new Date().toISOString()}).eq('id',d.id);if(derr)throw derr;d.review_status='approved';toast(`Đã lưu vào ${v105ScopeLabel(scope)}`);advanceReview(batch,drafts,pos)}catch(ex){err(ex);btn.disabled=false}};renderMath($('#content'));
};

document.addEventListener('DOMContentLoaded',()=>{document.documentElement.dataset.aicloVersion='10.5'});
