/* AI-CLO PTITHCM v9.2 — inline workflows, notifications and six-month audit log */
titles.notifications=['Thông báo','Bài kiểm tra, hoạt động và nhắc cải thiện'];
titles.activity=['Nhật ký hoạt động','Theo dõi các thao tác trong 6 tháng gần nhất'];

const viTime=v=>v?new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const inputTime=v=>v?new Date(new Date(v).getTime()-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const activityLabels={login:'Đăng nhập',logout:'Đăng xuất',create:'Tạo mới',update:'Cập nhật',delete:'Xóa',ai_generate:'Sinh câu hỏi AI',ai_approve:'Duyệt câu hỏi AI',ai_reject:'Bỏ qua câu hỏi AI',export:'Xuất dữ liệu',read_notification:'Đọc thông báo'};
let notificationRefreshAt=0;

window.logActivity=async function(action,entityType='system',entityId=null,summary='',status='success',subjectId=null,metadata={}){
 try{
  const uid=state.user?.id||(await db.auth.getUser()).data.user?.id;
  if(!uid)return;
  await db.from('activity_logs').insert({user_id:uid,subject_id:subjectId||state.subjectId||null,action,entity_type:entityType,entity_id:entityId||null,summary:summary.slice(0,500),status,metadata});
 }catch(e){console.warn('Không ghi được nhật ký',e)}
};

function inlinePage(title,subtitle,html,backView=state.view){
 const c=$('#content');
 c.innerHTML=`<section class="panel inline-page"><div class="inline-head"><button id="inlineBack" class="secondary">← Quay lại</button><div><h3>${esc(title)}</h3><p>${esc(subtitle||'')}</p></div></div>${html}</section>`;
 $('#inlineBack').onclick=()=>{state.view=backView;render()};
 window.scrollTo({top:0,behavior:'smooth'});
}

async function refreshNotificationData(force=false){
 if(!state.user)return;
 if(force||Date.now()-notificationRefreshAt>300000){
  notificationRefreshAt=Date.now();
  try{await db.rpc('refresh_my_notifications')}catch(e){console.warn('Chưa thể làm mới thông báo',e)}
 }
 try{
  const {count,error}=await db.from('notifications').select('id',{count:'exact',head:true}).eq('user_id',state.user.id).is('read_at',null).or(`expires_at.is.null,expires_at.gt.${new Date().toISOString()}`);
  if(error)throw error;
  const badge=$('#notificationCount');badge.textContent=count||0;badge.hidden=!count;
 }catch(e){console.warn('Chưa thể đếm thông báo',e)}
}

const v91Dashboard=dashboard;
dashboard=async function(c){
 await v91Dashboard(c);
 try{
  await refreshNotificationData();
  let items=await q('notifications','*',x=>x.eq('user_id',state.user.id).is('read_at',null).order('created_at',{ascending:false}).limit(5));
  const box=document.createElement('section');box.className='panel task-center';
  box.innerHTML=`<div class="panel-head"><h3>Việc cần xử lý</h3><button id="allNotices" class="secondary">Xem tất cả</button></div>${items.length?items.map(notificationCard).join(''):'<p class="hint">Hiện không có việc mới cần xử lý.</p>'}`;
  c.append(box);$('#allNotices').onclick=()=>navigate('notifications');box.querySelectorAll('[data-notice]').forEach(b=>b.onclick=()=>openNotification(b.dataset.notice));
 }catch(e){console.warn(e)}
};

const originalRender=render;
render=async function(){
 let c=$('#content');c.innerHTML='<div class="panel">Đang tải dữ liệu…</div>';
 try{await ({dashboard,subjects,structure,questions,exams,results,notifications,activity,users}[state.view]||dashboard)(c);refreshNotificationData()}catch(e){c.innerHTML=`<div class="panel"><b>Không thể tải dữ liệu</b><p>${esc(e.message)}</p></div>`;err(e)}
};

$('#notificationBell').onclick=()=>navigate('notifications');

function subjectForm(s={}){
 inlinePage(s.id?'Sửa học phần':'Tạo học phần','Thông tin được lưu trực tiếp vào hệ thống.',`<form id="subjectForm" class="form-grid inline-form"><label class="field wide">Tên học phần<input name="name" required value="${esc(s.name)}"></label><label class="field">Học kỳ<input name="semester" required value="${esc(s.semester||'Học kỳ 1')}"></label><label class="field">Năm học<input name="academic_year" required value="${esc(s.academic_year||'2026-2027')}"></label><div class="form-actions"><button type="button" class="secondary" id="cancelInline">Hủy</button><button class="primary">Lưu học phần</button></div></form>`,'subjects');
 $('#cancelInline').onclick=()=>render();
 $('#subjectForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target)),r=s.id?await db.from('subjects').update(v).eq('id',s.id):await db.from('subjects').insert(v).select().single();if(r.error)return err(r.error);await logActivity(s.id?'update':'create','subject',s.id||r.data?.id,s.id?'Cập nhật học phần':'Tạo học phần');toast('Đã lưu học phần');await boot(state.user)};
}

function simpleForm(title,fields,save){
 inlinePage(title,'Nhập thông tin và lưu để quay lại cấu trúc học phần.',`<form id="simpleForm" class="form-grid inline-form">${fields.map(f=>`<label class="field wide">${f[1]}<input name="${f[0]}" type="${f[2]||'text'}" required></label>`).join('')}<div class="form-actions"><button type="button" class="secondary" id="cancelInline">Hủy</button><button class="primary">Lưu</button></div></form>`,'structure');
 $('#cancelInline').onclick=()=>render();
 $('#simpleForm').onsubmit=async e=>{e.preventDefault();let r=await save(Object.fromEntries(new FormData(e.target)));if(r.error)return err(r.error);await logActivity('create','course_structure',null,title);toast('Đã lưu');render()};
}

function questionForm(x={},sets){
 x=x||{};let opts=Object.fromEntries((x.question_options||[]).map(o=>[o.option_key,o.content]));
 inlinePage(x.id?'Sửa câu hỏi':'Thêm câu hỏi','Biên soạn đầy đủ nội dung, phương án và chuẩn đầu ra.',`<form id="qForm" class="form-grid inline-form"><label class="field wide">Nội dung<textarea name="content" required>${esc(x.content)}</textarea></label><label class="field">Chương<select name="chapter_id" id="qchapter" required>${sets.ch.map(v=>`<option value="${v.id}" ${v.id===x.chapter_id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label class="field">Chủ đề<select name="topic_id" id="qtopic" required></select></label><label class="field">CLO<select name="clo_id" required>${sets.clos.map(v=>`<option value="${v.id}" ${v.id===x.clo_id?'selected':''}>${esc(v.code)} — ${esc(v.description)}</option>`).join('')}</select></label><label class="field">Đáp án đúng<select name="correct_answer">${['A','B','C','D'].map(v=>`<option ${v===x.correct_answer?'selected':''}>${v}</option>`).join('')}</select></label><div class="wide option-grid">${['A','B','C','D'].map(v=>`<label class="field">Phương án ${v}<input name="opt_${v}" required value="${esc(opts[v])}"></label>`).join('')}</div><label class="field wide">Giải thích<textarea name="explanation">${esc(x.explanation)}</textarea></label><label class="field">Trạng thái<select name="status"><option value="active">Đang dùng</option><option value="draft" ${x.status==='draft'?'selected':''}>Bản nháp</option></select></label><div class="form-actions"><button type="button" class="secondary" id="cancelInline">Hủy</button><button class="primary">Lưu câu hỏi</button></div></form>`,'questions');
 const topicSelect=()=>{$('#qtopic').innerHTML=sets.topics.filter(t=>t.chapter_id===$('#qchapter').value).map(t=>`<option value="${t.id}" ${t.id===x.topic_id?'selected':''}>${esc(t.name)}</option>`).join('')};topicSelect();$('#qchapter').onchange=topicSelect;$('#cancelInline').onclick=()=>render();
 $('#qForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target)),optionRows=['A','B','C','D'].map(k=>({option_key:k,content:v['opt_'+k]}));['A','B','C','D'].forEach(k=>delete v['opt_'+k]);Object.assign(v,{subject_id:state.subjectId,created_by:state.user.id});let r=x.id?await db.from('questions').update(v).eq('id',x.id).select().single():await db.from('questions').insert(v).select().single();if(r.error)return err(r.error);let id=x.id||r.data.id;if(x.id){let d=await db.from('question_options').delete().eq('question_id',id);if(d.error)return err(d.error)}let o=await db.from('question_options').insert(optionRows.map(z=>({...z,question_id:id})));if(o.error)return err(o.error);await logActivity(x.id?'update':'create','question',id,(x.id?'Cập nhật: ':'Tạo: ')+v.content.slice(0,120));toast('Đã lưu câu hỏi');render()};
}

function aiGenerateForm(sets){
 if(!sets.ch.length||!sets.clos.length)return toast('Học phần cần có chương và CLO trước khi tạo câu hỏi',true);
 inlinePage('Tạo câu hỏi bằng Gemini','Gemini tạo bản nháp; giảng viên duyệt trước khi đưa vào ngân hàng.',`<form id="aiForm" class="form-grid inline-form"><div class="ai-note wide"><b>Giảng viên là người quyết định cuối cùng.</b><span>Có thể sửa nội dung, phương án và giải thích khi duyệt.</span></div><label class="field">Chương<select name="chapter_id" id="aiChapter" required>${sets.ch.map(v=>`<option value="${v.id}">${esc(v.order_index)}. ${esc(v.name)}</option>`).join('')}</select></label><label class="field">Chủ đề<select name="topic_id" id="aiTopic"><option value="">Tất cả chủ đề trong chương</option></select></label><label class="field">CLO<select name="clo_id" id="aiClo" required>${sets.clos.map(v=>`<option value="${v.id}">${esc(v.code)}</option>`).join('')}</select></label><label class="field">Số câu<select name="count"><option>5</option><option selected>10</option></select></label><div id="cloDescription" class="clo-description wide"></div><label class="field wide">Yêu cầu bổ sung<textarea name="additional_requirements" placeholder="Không bắt buộc"></textarea></label><div class="form-actions"><button type="button" class="secondary" id="cancelInline">Hủy</button><button class="ai-btn" id="aiSubmit">✦ Sinh câu hỏi</button></div></form>`,'questions');
 const fillTopics=()=>{$('#aiTopic').innerHTML='<option value="">Tất cả chủ đề trong chương</option>'+sets.topics.filter(t=>t.chapter_id===$('#aiChapter').value).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')};const showClo=()=>{let x=sets.clos.find(c=>c.id===$('#aiClo').value);$('#cloDescription').innerHTML=`<b>${esc(x?.code||'')}</b><span>${esc(x?.description||'')}</span>`};fillTopics();showClo();$('#aiChapter').onchange=fillTopics;$('#aiClo').onchange=showClo;$('#cancelInline').onclick=()=>render();
 $('#aiForm').onsubmit=async e=>{e.preventDefault();let btn=$('#aiSubmit'),v=Object.fromEntries(new FormData(e.target));btn.disabled=true;btn.textContent='Gemini đang tạo…';try{let {data,error}=await db.functions.invoke('generate-questions',{body:{subject_id:state.subjectId,chapter_id:v.chapter_id,topic_id:v.topic_id||null,clo_id:v.clo_id,count:+v.count,additional_requirements:v.additional_requirements}});if(error)throw error;if(!data?.success)throw new Error(data?.error||'Không tạo được câu hỏi');await logActivity('ai_generate','ai_batch',data.batch_id,`Sinh ${data.total} câu hỏi chờ duyệt`,'success',state.subjectId,{count:data.total,clo_id:v.clo_id,chapter_id:v.chapter_id});toast(`Đã tạo ${data.total} câu chờ duyệt`);await reviewBatch(data.batch_id,0)}catch(ex){await logActivity('ai_generate','ai_batch',null,'Sinh câu hỏi thất bại','failed',state.subjectId,{error:ex.message});err(ex);btn.disabled=false;btn.textContent='✦ Sinh câu hỏi'}};
}

async function aiHistory(){
 try{let batches=await q('ai_generation_batches','*, chapters(name), clos(code)',x=>x.eq('subject_id',state.subjectId).order('created_at',{ascending:false}).limit(30));inlinePage('Các phiên tạo câu hỏi AI','Mở lại phiên còn chờ để tiếp tục duyệt.',`<div class="history-list inline-history">${batches.map(b=>`<button data-batch="${b.id}"><span><b>${esc(b.clos?.code)} · ${esc(b.chapters?.name)}</b><small>${viTime(b.created_at)} · ${b.generated_count}/${b.requested_count} câu</small></span><span class="badge ${b.status==='completed'?'green':'red'}">${esc(b.status)}</span></button>`).join('')||'<div class="empty">Chưa có phiên AI nào.</div>'}</div>`,'questions');$$('.history-list [data-batch]').forEach(b=>b.onclick=()=>reviewBatch(b.dataset.batch,0))}catch(ex){err(ex)}
}

function showDraft(batch,drafts,d,pos){
 let approved=drafts.filter(x=>x.review_status==='approved').length,rejected=drafts.filter(x=>x.review_status==='rejected').length;
 inlinePage('Duyệt câu hỏi Gemini',`Câu ${pos+1}/${drafts.length} · Đã lưu ${approved} · Bỏ qua ${rejected}`,`<div class="review-wrap inline-review"><div class="review-tags"><span class="badge red">${esc(batch.clos?.code)}</span><span class="badge">${esc(batch.chapters?.name)}</span><span class="badge ${d.review_status==='approved'?'green':''}">${esc(d.review_status)}</span></div><label class="field">Nội dung<textarea id="draftContent">${esc(d.content)}</textarea></label><div class="review-options">${['A','B','C','D'].map(k=>`<label class="${d.correct_answer===k?'correct':''}"><b>${k}</b><input id="draft${k}" value="${esc(d.options?.[k])}"></label>`).join('')}</div><label class="field">Đáp án đúng<select id="draftCorrect">${['A','B','C','D'].map(k=>`<option ${d.correct_answer===k?'selected':''}>${k}</option>`).join('')}</select></label><label class="field">Giải thích<textarea id="draftExplanation">${esc(d.explanation)}</textarea></label><div class="review-actions"><button class="secondary" id="prevDraft" ${pos===0?'disabled':''}>← Trước</button><button class="danger" id="rejectDraft">Bỏ qua</button><button class="primary" id="approveDraft">Xác nhận và lưu</button><button class="secondary" id="nextDraft" ${pos===drafts.length-1?'disabled':''}>Sau →</button></div></div>`,'questions');
 $('#prevDraft').onclick=()=>showDraft(batch,drafts,drafts[pos-1],pos-1);$('#nextDraft').onclick=()=>showDraft(batch,drafts,drafts[pos+1],pos+1);
 $('#rejectDraft').onclick=async()=>{let {error}=await db.from('ai_question_drafts').update({review_status:'rejected',reviewed_by:state.user.id,reviewed_at:new Date().toISOString()}).eq('id',d.id);if(error)return err(error);d.review_status='rejected';await logActivity('ai_reject','ai_draft',d.id,'Bỏ qua câu hỏi AI');toast('Đã bỏ qua câu hỏi');advanceReview(batch,drafts,pos)};
 $('#approveDraft').onclick=async()=>{let btn=$('#approveDraft');btn.disabled=true;try{let qrow={subject_id:batch.subject_id,chapter_id:batch.chapter_id,topic_id:d.topic_id||batch.topic_id,clo_id:batch.clo_id,content:$('#draftContent').value.trim(),explanation:$('#draftExplanation').value.trim()||null,correct_answer:$('#draftCorrect').value,created_by:state.user.id,status:'active'};if(!qrow.content)throw new Error('Nội dung câu hỏi không được để trống');if(!qrow.topic_id)throw new Error('Câu hỏi chưa được gắn chủ đề');let {data:question,error:qerr}=await db.from('questions').insert(qrow).select().single();if(qerr)throw qerr;let options=['A','B','C','D'].map(k=>({question_id:question.id,option_key:k,content:$('#draft'+k).value.trim()}));let {error:oerr}=await db.from('question_options').insert(options);if(oerr){await db.from('questions').delete().eq('id',question.id);throw oerr}let {error:derr}=await db.from('ai_question_drafts').update({content:qrow.content,options:Object.fromEntries(options.map(o=>[o.option_key,o.content])),correct_answer:qrow.correct_answer,explanation:qrow.explanation,review_status:'approved',approved_question_id:question.id,reviewed_by:state.user.id,reviewed_at:new Date().toISOString()}).eq('id',d.id);if(derr)throw derr;d.review_status='approved';await logActivity('ai_approve','question',question.id,'Duyệt và lưu câu hỏi AI');toast('Đã lưu câu hỏi vào ngân hàng');advanceReview(batch,drafts,pos)}catch(ex){err(ex);btn.disabled=false}};
}

async function advanceReview(batch,drafts,pos){let pending=drafts.findIndex((x,i)=>i>pos&&x.review_status==='pending');if(pending<0)pending=drafts.findIndex(x=>x.review_status==='pending');if(pending>=0)return showDraft(batch,drafts,drafts[pending],pending);let {error}=await db.from('ai_generation_batches').update({status:'completed',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',batch.id);if(error)return err(error);toast('Đã duyệt xong phiên câu hỏi');state.view='questions';render()}

function examForm(x={}){
 inlinePage(x.id?'Sửa bài kiểm tra':'Tạo bài kiểm tra','Thiết lập thời gian để hệ thống tạo thông báo đúng hạn.',`<form id="examForm" class="form-grid inline-form"><label class="field wide">Tên đề<input name="title" required value="${esc(x.title)}"></label><label class="field wide">Mô tả<textarea name="description">${esc(x.description)}</textarea></label><label class="field">Loại đề<select name="exam_type"><option value="chapter_test">Luyện tập theo chương</option><option value="clo_assessment" ${x.exam_type==='clo_assessment'?'selected':''}>Đánh giá CLO</option><option value="final_exam" ${x.exam_type==='final_exam'?'selected':''}>Thi cuối kỳ</option></select></label><label class="field">Số câu<input name="total_questions" type="number" min="1" required value="${esc(x.total_questions||'')}"></label><label class="field">Thời gian làm bài (phút)<input name="duration_minutes" type="number" min="1" value="${esc(x.duration_minutes||'')}"></label><label class="field">Trạng thái<select name="status"><option value="draft">Bản nháp</option><option value="active" ${x.status==='active'?'selected':''}>Đang hoạt động</option></select></label><label class="field">Thời điểm mở<input name="opens_at" type="datetime-local" value="${inputTime(x.opens_at)}"></label><label class="field">Hạn làm bài<input name="closes_at" type="datetime-local" value="${inputTime(x.closes_at)}"></label><div class="form-actions"><button type="button" class="secondary" id="cancelInline">Hủy</button><button class="primary">${x.id?'Lưu thay đổi':'Tạo bài kiểm tra'}</button></div></form>`,'exams');
 $('#cancelInline').onclick=()=>render();$('#examForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));Object.assign(v,{subject_id:state.subjectId,created_by:state.user.id,total_questions:+v.total_questions,duration_minutes:v.duration_minutes?+v.duration_minutes:null,is_clo_assessment:v.exam_type==='clo_assessment',opens_at:v.opens_at?new Date(v.opens_at).toISOString():null,closes_at:v.closes_at?new Date(v.closes_at).toISOString():null});let r=x.id?await db.from('exams').update(v).eq('id',x.id):await db.from('exams').insert(v).select().single();if(r.error)return err(r.error);await logActivity(x.id?'update':'create','exam',x.id||r.data?.id,(x.id?'Cập nhật: ':'Tạo: ')+v.title);toast(x.id?'Đã cập nhật bài kiểm tra':'Đã tạo bài kiểm tra');render()};
}

function notificationCard(n){return `<button class="notice-card ${n.read_at?'read':''}" data-notice="${n.id}"><span class="notice-icon">${n.severity==='warning'?'!':'●'}</span><span><b>${esc(n.title)}</b><small>${esc(n.message)}</small><em>${viTime(n.created_at)}</em></span></button>`}
async function notifications(c){
 await refreshNotificationData(true);let items=await q('notifications','*',x=>x.eq('user_id',state.user.id).order('created_at',{ascending:false}).limit(200));
 c.innerHTML=`<div class="toolbar"><select id="noticeFilter"><option value="all">Tất cả</option><option value="unread">Chưa đọc</option><option value="exam">Bài kiểm tra</option><option value="clo">CLO</option><option value="activity">Hoạt động</option><option value="ai">Phiên AI</option></select><button id="readAll" class="secondary">Đánh dấu tất cả đã đọc</button></div><section class="panel notice-list" id="noticeList"></section>`;
 const draw=()=>{let f=$('#noticeFilter').value,list=items.filter(n=>f==='all'||(f==='unread'?!n.read_at:n.category===f));$('#noticeList').innerHTML=list.length?list.map(notificationCard).join(''):'<div class="empty">Không có thông báo phù hợp.</div>';$('#noticeList').querySelectorAll('[data-notice]').forEach(b=>b.onclick=()=>openNotification(b.dataset.notice,items))};draw();$('#noticeFilter').onchange=draw;
 $('#readAll').onclick=async()=>{let {error}=await db.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',state.user.id).is('read_at',null);if(error)return err(error);items.forEach(n=>n.read_at=n.read_at||new Date().toISOString());toast('Đã đánh dấu tất cả là đã đọc');draw();refreshNotificationData(true)};
}
async function openNotification(id,items=null){let n=items?.find(x=>x.id===id);if(!n){let {data}=await db.from('notifications').select('*').eq('id',id).single();n=data}if(!n)return;if(!n.read_at)await db.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);await logActivity('read_notification','notification',id,'Đọc thông báo');if(n.target_view&&titles[n.target_view])navigate(n.target_view);else navigate('notifications')}

async function activity(c){
 if(!canTeach()){c.innerHTML='<div class="panel">Chỉ Admin và giảng viên được xem nhật ký hoạt động.</div>';return}
 let rows=await q('activity_logs','*, profiles:user_id(full_name,email,role), subjects:subject_id(name)',x=>x.order('created_at',{ascending:false}).limit(5000));
 c.innerHTML=`<div class="toolbar activity-filter"><input id="logSearch" placeholder="Tìm người dùng hoặc hoạt động…"><select id="logAction"><option value="">Mọi hoạt động</option>${[...new Set(rows.map(x=>x.action))].map(x=>`<option value="${esc(x)}">${esc(activityLabels[x]||x)}</option>`).join('')}</select><select id="logStatus"><option value="">Mọi trạng thái</option><option value="success">Thành công</option><option value="failed">Thất bại</option></select><input id="logFrom" type="date"><input id="logTo" type="date"><button id="exportLogs" class="primary">Xuất nhật ký Excel</button></div><div class="panel table-wrap"><p class="hint">Nhật ký được lưu trong 6 tháng kể từ thời điểm phát sinh.</p><table><thead><tr><th>Thời gian</th><th>Người dùng</th><th>Vai trò</th><th>Học phần</th><th>Hoạt động</th><th>Nội dung tóm tắt</th><th>Trạng thái</th></tr></thead><tbody id="logRows"></tbody></table></div>`;
 let current=[];const draw=()=>{let s=$('#logSearch').value.toLowerCase(),a=$('#logAction').value,st=$('#logStatus').value,from=$('#logFrom').value?new Date($('#logFrom').value):null,to=$('#logTo').value?new Date($('#logTo').value+'T23:59:59'):null;current=rows.filter(x=>(!s||`${x.profiles?.full_name} ${x.profiles?.email} ${x.summary}`.toLowerCase().includes(s))&&(!a||x.action===a)&&(!st||x.status===st)&&(!from||new Date(x.created_at)>=from)&&(!to||new Date(x.created_at)<=to));$('#logRows').innerHTML=current.map(x=>`<tr><td>${viTime(x.created_at)}</td><td><b>${esc(x.profiles?.full_name||'—')}</b><br><small>${esc(x.profiles?.email||'')}</small></td><td>${esc(x.profiles?.role||'—')}</td><td>${esc(x.subjects?.name||'—')}</td><td>${esc(activityLabels[x.action]||x.action)}</td><td>${esc(x.summary)}</td><td><span class="badge ${x.status==='success'?'green':'red'}">${x.status==='success'?'Thành công':'Thất bại'}</span></td></tr>`).join('')||'<tr><td colspan="7">Không có dữ liệu phù hợp.</td></tr>'};draw();$$('#logSearch,#logAction,#logStatus,#logFrom,#logTo').forEach(x=>x.oninput=draw);
 $('#exportLogs').onclick=()=>exportActivityExcel(current);
}
function exportActivityExcel(rows){
 if(!window.XLSX)return toast('Không tải được thư viện xuất Excel',true);
 const data=rows.map((x,i)=>({'STT':i+1,'Thời gian':viTime(x.created_at),'Họ tên':x.profiles?.full_name||'','Email':x.profiles?.email||'','Vai trò':x.profiles?.role||'','Học phần':x.subjects?.name||'','Hoạt động':activityLabels[x.action]||x.action,'Đối tượng':x.entity_type||'','Nội dung tóm tắt':x.summary||'','Trạng thái':x.status==='success'?'Thành công':'Thất bại'}));let ws=XLSX.utils.json_to_sheet(data);ws['!cols']=[{wch:6},{wch:20},{wch:24},{wch:30},{wch:14},{wch:25},{wch:22},{wch:16},{wch:50},{wch:14}];let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Nhật ký hoạt động');let d=new Date().toISOString().slice(0,10);XLSX.writeFile(wb,`Nhat-ky-hoat-dong_${d}.xlsx`);logActivity('export','activity_logs',null,`Xuất ${rows.length} dòng nhật ký`);toast('Đã tạo file nhật ký Excel')
}

const v91Remove=remove;
remove=async function(table,id,label){if(!confirm(`Xóa ${label} này? Dữ liệu liên quan có thể khiến thao tác bị từ chối.`))return;let {error}=await db.from(table).delete().eq('id',id);if(error)return err(error);await logActivity('delete',table,id,`Xóa ${label}`);toast(`Đã xóa ${label}`);if(table==='subjects')await boot(state.user);else render()};
removeQuestion=async function(id){if(!confirm('Xóa câu hỏi và các phương án?'))return;let a=await db.from('question_options').delete().eq('question_id',id);if(a.error)return err(a.error);let b=await db.from('questions').delete().eq('id',id);if(b.error)return err(b.error);await logActivity('delete','question',id,'Xóa câu hỏi và các phương án');toast('Đã xóa câu hỏi');render()};

document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshNotificationData(true)});

/* Extended administrator controls */
structure=async function(c){
 if(!state.subjectId){c.replaceChildren(empty());return}
 let [ch,topics,clos]=await Promise.all([q('chapters','*',x=>x.eq('subject_id',state.subjectId).order('order_index')),q('topics'),q('clos','*',x=>x.eq('subject_id',state.subjectId).order('code'))]),relevantTopics=topics.filter(t=>ch.some(x=>x.id===t.chapter_id));
 c.innerHTML=`<div class="grid2"><section class="panel"><div class="panel-head"><h3>Chương và chủ đề</h3>${canTeach()?'<button id="addChapter" class="primary">+ Chương</button>':''}</div><div id="chapterList">${ch.map(x=>`<div style="padding:12px 0;border-bottom:1px solid var(--line)"><b>${x.order_index}. ${esc(x.name)}</b>${canTeach()?`<button data-topic="${x.id}" style="float:right">+ Chủ đề</button>`:''}<div>${relevantTopics.filter(t=>t.chapter_id===x.id).map(t=>`<span class="badge">${esc(t.name)}</span> `).join('')||'<small>Chưa có chủ đề</small>'}</div></div>`).join('')||'<p>Chưa có chương.</p>'}</div></section><section class="panel"><div class="panel-head"><h3>Chuẩn đầu ra CLO</h3>${role()==='admin'?'<button id="addClo" class="primary">+ CLO</button>':''}</div><div id="cloList">${clos.map(x=>`<div style="padding:12px 0;border-bottom:1px solid var(--line)"><span class="badge red">${esc(x.code)}</span> ${esc(x.description)}${role()==='admin'?`<button class="danger" data-del-clo="${x.id}" style="float:right">Xóa</button>`:''}</div>`).join('')||'<p>Chưa có CLO.</p>'}</div></section></div>`;
 $('#addChapter')?.addEventListener('click',()=>simpleForm('Tạo chương',[['name','Tên chương'],['order_index','Thứ tự','number']],async v=>db.from('chapters').insert({...v,order_index:+v.order_index,subject_id:state.subjectId})));
 $('#addClo')?.addEventListener('click',()=>simpleForm('Tạo CLO',[['code','Mã CLO'],['description','Mô tả']],async v=>db.from('clos').insert({...v,subject_id:state.subjectId})));
 $('#chapterList').onclick=e=>{let b=e.target.closest('[data-topic]');if(b)simpleForm('Tạo chủ đề',[['name','Tên chủ đề'],['order_index','Thứ tự','number']],async v=>db.from('topics').insert({...v,order_index:+v.order_index,chapter_id:b.dataset.topic}))};
 $('#cloList').onclick=async e=>{let b=e.target.closest('[data-del-clo]');if(!b)return;if(!confirm('Xóa CLO này? Nếu CLO đã được dùng trong câu hỏi hoặc đề thi, hệ thống sẽ từ chối để bảo vệ dữ liệu.'))return;let {error}=await db.from('clos').delete().eq('id',b.dataset.delClo);if(error)return err(error);await logActivity('delete','clo',b.dataset.delClo,'Xóa CLO');toast('Đã xóa CLO');render()};
};

exams=async function(c){
 if(!state.subjectId){c.replaceChildren(empty());return}
 let items=await q('exams','*',x=>x.eq('subject_id',state.subjectId).order('created_at',{ascending:false})),ids=items.map(x=>x.id),attempts=ids.length?await q('exam_attempts','id,exam_id',x=>x.in('exam_id',ids)):[];
 c.innerHTML=`<div class="toolbar"><span></span>${canTeach()?'<button id="addExam" class="primary">+ Tạo bài kiểm tra</button>':''}</div><div class="panel table-wrap"><table><thead><tr><th>Tên đề</th><th>Loại</th><th>Số câu</th><th>Lịch</th><th>Lượt làm</th><th>Trạng thái</th><th></th></tr></thead><tbody id="examRows">${items.map(x=>{let n=attempts.filter(a=>a.exam_id===x.id).length;return `<tr><td><b>${esc(x.title)}</b><br><small>${esc(x.description||'')}</small></td><td>${esc(x.exam_type)}</td><td>${x.total_questions}</td><td><small>Mở: ${viTime(x.opens_at)}<br>Đóng: ${viTime(x.closes_at)}</small></td><td><b>${n}</b></td><td><span class="badge green">${esc(x.status)}</span></td><td class="row-actions">${canTeach()?`<button data-edit="${x.id}">Sửa</button><button data-del="${x.id}" data-attempts="${n}">Xóa</button>`:''}</td></tr>`}).join('')}</tbody></table></div>`;
 $('#addExam')?.addEventListener('click',()=>examForm());$('#examRows').onclick=e=>{let b=e.target.closest('button');if(!b)return;let x=items.find(i=>i.id===(b.dataset.edit||b.dataset.del));if(b.dataset.edit)examForm(x);if(b.dataset.del)deleteExamAdminAware(x,+b.dataset.attempts)};
};
async function deleteExamAdminAware(exam,attemptCount){
 if(attemptCount&&role()!=='admin')return toast('Bài kiểm tra đã có lượt làm. Chỉ Admin được phép xóa.',true);
 let warning=attemptCount?`Bài kiểm tra đã có ${attemptCount} lượt làm. Xóa sẽ xóa cả câu trả lời và kết quả liên quan. Tiếp tục?`:'Xóa bài kiểm tra này?';if(!confirm(warning))return;
 if(attemptCount&&!confirm('Xác nhận lần cuối: dữ liệu lượt làm đã xóa không thể phục hồi.'))return;
 let error;if(attemptCount){({error}=await db.rpc('admin_delete_exam',{p_exam_id:exam.id}))}else({error}=await db.from('exams').delete().eq('id',exam.id));if(error)return err(error);await logActivity('delete','exam',exam.id,`Xóa bài kiểm tra ${exam.title} và ${attemptCount} lượt làm`);toast('Đã xóa bài kiểm tra');render();
}

results=async function(c){
 let examsList=state.subjectId?await q('exams','id,title',x=>x.eq('subject_id',state.subjectId)):[],ids=examsList.map(x=>x.id),attempts=ids.length?await q('exam_attempts','*, profiles:student_id(full_name,mssv)',x=>x.in('exam_id',ids).order('created_at',{ascending:false})):[],avg=attempts.filter(x=>x.score!=null).reduce((a,b)=>a+Number(b.score),0)/(attempts.filter(x=>x.score!=null).length||1);
 c.innerHTML=`<div class="stats"><div class="stat"><small>Lượt làm bài</small><b>${attempts.length}</b></div><div class="stat"><small>Đã nộp</small><b>${attempts.filter(x=>x.submitted_at).length}</b></div><div class="stat"><small>Điểm trung bình</small><b>${avg.toFixed(2)}</b></div><div class="stat"><small>Đề có dữ liệu</small><b>${new Set(attempts.map(x=>x.exam_id)).size}</b></div></div><div class="panel table-wrap"><table><thead><tr><th>Sinh viên</th><th>Đề thi</th><th>Lần</th><th>Điểm</th><th>Trạng thái</th>${role()==='admin'?'<th>Quản trị</th>':''}</tr></thead><tbody id="attemptRows">${attempts.map(x=>`<tr><td>${esc(x.profiles?.full_name||x.student_id)}<br><small>${esc(x.profiles?.mssv||'')}</small></td><td>${esc(examsList.find(e=>e.id===x.exam_id)?.title)}</td><td>${x.attempt_number}</td><td><b>${x.score??'—'}</b></td><td><span class="badge ${x.submitted_at?'green':''}">${x.submitted_at?'Đã nộp':'Đang làm'}</span></td>${role()==='admin'?`<td><button class="danger" data-del-attempt="${x.id}">Xóa lượt làm</button></td>`:''}</tr>`).join('')}</tbody></table></div>`;
 if(role()==='admin')$('#attemptRows').onclick=async e=>{let b=e.target.closest('[data-del-attempt]');if(!b)return;let a=attempts.find(x=>x.id===b.dataset.delAttempt);if(!confirm('Xóa lượt làm này và toàn bộ câu trả lời liên quan?'))return;if(!confirm('Xác nhận lần cuối: thao tác không thể phục hồi.'))return;let {error}=await db.rpc('admin_delete_attempt',{p_attempt_id:a.id});if(error)return err(error);await logActivity('delete','exam_attempt',a.id,'Admin xóa lượt làm của sinh viên');toast('Đã xóa lượt làm');render()};
};

users=async function(c){
 if(role()!=='admin'){c.innerHTML='<div class="panel">Chỉ quản trị viên được truy cập.</div>';return}
 let [profiles,members]=await Promise.all([q('profiles','*',x=>x.order('full_name')),q('subject_members','*')]);
 c.innerHTML=`<div class="toolbar"><input id="userSearch" placeholder="Tìm tên, email hoặc MSSV…"><button id="addUser" class="primary">+ Tạo người dùng</button></div><div class="panel table-wrap"><table><thead><tr><th>Họ tên</th><th>Email / MSSV</th><th>Vai trò</th><th>Học phần</th><th>Trạng thái</th><th></th></tr></thead><tbody id="userRows"></tbody></table></div>`;
 const draw=(list=profiles)=>{$('#userRows').innerHTML=list.map(p=>`<tr><td><b>${esc(p.full_name)}</b></td><td>${esc(p.email)}<br><small>${esc(p.mssv||'')}</small></td><td><span class="badge red">${esc(p.role)}</span></td><td>${members.filter(m=>m.user_id===p.id).length}</td><td><span class="status-dot ${p.is_active===false?'off':''}"></span>${p.is_active===false?'Đã khóa':'Hoạt động'}</td><td class="admin-actions"><button data-toggle="${p.id}" data-active="${p.is_active!==false}">${p.is_active===false?'Mở khóa':'Khóa'}</button>${p.id!==state.user.id?`<button class="danger" data-del-user="${p.id}">Xóa</button>`:''}</td></tr>`).join('')};draw();$('#userSearch').oninput=e=>{let s=e.target.value.toLowerCase();draw(profiles.filter(p=>`${p.full_name} ${p.email} ${p.mssv||''}`.toLowerCase().includes(s)))};$('#addUser').onclick=userCreateForm;
 $('#userRows').onclick=async e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.toggle){let active=b.dataset.active==='true',{data,error}=await db.functions.invoke('admin-users',{body:{action:'set_active',user_id:b.dataset.toggle,is_active:!active}});if(error||!data?.success)return err(error||new Error(data?.error));await logActivity('update','user',b.dataset.toggle,active?'Khóa tài khoản':'Mở khóa tài khoản');toast(active?'Đã khóa tài khoản':'Đã mở khóa tài khoản');render()}if(b.dataset.delUser){if(!confirm('Xóa tài khoản này khỏi hệ thống?'))return;if(!confirm('Xác nhận lần cuối: tài khoản đăng nhập sẽ bị xóa.'))return;let {data,error}=await db.functions.invoke('admin-users',{body:{action:'delete',user_id:b.dataset.delUser}});if(error||!data?.success)return err(error||new Error(data?.error));await logActivity('delete','user',b.dataset.delUser,'Xóa người dùng');toast('Đã xóa người dùng');render()}};
}
function userCreateForm(){
 inlinePage('Tạo người dùng','Admin tạo tài khoản và cung cấp mật khẩu ban đầu cho người dùng.',`<form id="userForm" class="form-grid inline-form"><label class="field wide">Họ và tên<input name="full_name" required></label><label class="field">Email<input name="email" type="email" required></label><label class="field">MSSV<input name="mssv" placeholder="Để trống nếu là giảng viên"></label><label class="field">Vai trò<select name="role"><option value="student">Sinh viên</option><option value="teacher">Giảng viên</option><option value="admin">Admin</option></select></label><label class="field">Mật khẩu ban đầu<input name="password" type="password" minlength="8" required></label><label class="field wide">Gán vào học phần<select name="subject_id"><option value="">Chưa gán</option>${state.subjects.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.semester)}</option>`).join('')}</select></label><div class="form-actions"><button type="button" class="secondary" id="cancelInline">Hủy</button><button class="primary">Tạo tài khoản</button></div></form>`,'users');$('#cancelInline').onclick=()=>render();$('#userForm').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target)),btn=e.submitter;btn.disabled=true;let {data,error}=await db.functions.invoke('admin-users',{body:{action:'create',...v}});btn.disabled=false;if(error||!data?.success)return err(error||new Error(data?.error));await logActivity('create','user',data.user_id,`Tạo người dùng ${v.full_name} (${v.role})`);toast('Đã tạo tài khoản');state.view='users';render()};
}
