/* AI-CLO PTITHCM v9.4 — fixed sidebar and in-page question workflow. */
let v94QuestionFilters=null;
const v94Time=v=>v?new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
function captureQuestionFilters(){if(!$('#qsearch'))return;v94QuestionFilters={search:$('#qsearch').value,chapter:$('#qchapterFilter').value,topic:$('#qtopicFilter').value,clo:$('#qcloFilter').value,status:$('#qstatusFilter').value}}
async function backToQuestionList(){state.view='questions';await render();if(!v94QuestionFilters)return;let f=v94QuestionFilters;if($('#qsearch'))$('#qsearch').value=f.search||'';if($('#qchapterFilter')){$('#qchapterFilter').value=f.chapter||'all';$('#qchapterFilter').dispatchEvent(new Event('change'))}if($('#qtopicFilter'))$('#qtopicFilter').value=f.topic||'all';if($('#qcloFilter'))$('#qcloFilter').value=f.clo||'all';if($('#qstatusFilter'))$('#qstatusFilter').value=f.status||'all';$('#qsearch')?.dispatchEvent(new Event('input'))}
function questionWorkspace(title,subtitle,body){closeModal();closeDrawer();let c=$('#content');c.innerHTML=`<section class="panel question-workspace"><div class="workspace-head"><button id="questionBack" class="workspace-back">← Quay lại ngân hàng</button><div><h3>${esc(title)}</h3><p>${esc(subtitle||'')}</p></div></div><div class="workspace-body">${body}</div></section>`;$('#questionBack').onclick=backToQuestionList;window.scrollTo({top:0,behavior:'smooth'});renderMath(c)}

questionDetail=async function(x,sets){
 captureQuestionFilters();try{
  let [creatorRows,revisions]=await Promise.all([
   x.created_by?q('profiles','id,full_name,email',z=>z.eq('id',x.created_by).limit(1)):[],
   q('question_revisions','revision_no,changed_at,changed_by,profiles:changed_by(full_name,email)',z=>z.eq('question_id',x.id).order('revision_no',{ascending:false}))
  ]),creator=creatorRows[0],opts=Object.fromEntries((x.question_options||[]).map(o=>[o.option_key,o.content])),chapter=sets.ch.find(v=>v.id===x.chapter_id),topic=sets.topics.find(v=>v.id===x.topic_id),clo=sets.clos.find(v=>v.id===x.clo_id);
  questionWorkspace(`${questionCode(x.id)} · Chi tiết câu hỏi`,'Nội dung, người tạo và lịch sử cập nhật',`<div class="question-detail"><div class="detail-meta"><span class="badge red">${esc(clo?.code||'—')}</span><span class="badge">${esc(chapter?.name||'—')}</span><span class="badge">${esc(topic?.name||'—')}</span><span class="badge ${x.status==='active'?'green':''}">${x.status==='active'?'Đang dùng':'Bản nháp'}</span></div><div class="question-audit"><div><small>Người tạo</small><b>${esc(creator?.full_name||creator?.email||'Chưa xác định')}</b></div><div><small>Ngày tạo</small><b>${v94Time(x.created_at)}</b></div><div><small>Cập nhật gần nhất</small><b>${v94Time(x.updated_at||x.created_at)}</b></div></div><div class="detail-question">${esc(x.content)}</div><div class="detail-options">${['A','B','C','D'].map(k=>`<div class="${x.correct_answer===k?'correct':''}"><b>${k}</b><span>${esc(opts[k]||'')}</span></div>`).join('')}</div><div class="detail-explanation"><b>Lời giải</b><p>${esc(x.explanation||'Chưa có lời giải.')}</p></div><h4>Lịch sử chỉnh sửa (${revisions.length})</h4><div class="revision-list">${revisions.map(r=>`<div class="revision-row"><b>Lần ${r.revision_no}</b><span>${esc(r.profiles?.full_name||r.profiles?.email||'Người dùng không còn tồn tại')}</span><small>${v94Time(r.changed_at)}</small></div>`).join('')||'<p class="hint">Câu hỏi chưa từng được chỉnh sửa kể từ khi bật lịch sử v9.4.</p>'}</div><div class="account-actions"><button id="detailDeleteQuestion" class="danger">Xóa câu hỏi</button><button id="detailEditQuestion" class="primary">Sửa câu hỏi</button></div></div>`);$('#detailEditQuestion').onclick=()=>questionForm(x,sets);$('#detailDeleteQuestion').onclick=async()=>{if(!await confirmAction('Xóa câu hỏi',`Xóa ${questionCode(x.id)}?`,{confirmLabel:'Xóa',danger:true}))return;await removeQuestion(x.id)}
 }catch(ex){if(/question_revisions/i.test(ex.message||''))return err(new Error('Chưa có bảng lịch sử câu hỏi. Hãy chạy SQL v9.4 trước.'));err(ex)}
};

questionForm=function(x={},sets){
 captureQuestionFilters();x=x||{};let opts=Object.fromEntries((x.question_options||[]).map(o=>[o.option_key,o.content]));
 questionWorkspace(x.id?'Sửa câu hỏi':'Thêm câu hỏi',x.id?'Bản hiện tại sẽ được lưu vào lịch sử trước khi cập nhật.':'Biên soạn câu hỏi trực tiếp trong trang.',`<div class="question-edit-page"><form id="qForm" class="form-grid"><label class="field wide">Nội dung<textarea name="content" required>${esc(x.content||'')}</textarea></label><label class="field">Chương<select name="chapter_id" id="qchapter" required>${sets.ch.map(v=>`<option value="${v.id}" ${v.id===x.chapter_id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label class="field">Chủ đề<select name="topic_id" id="qtopic" required></select></label><label class="field">CLO<select name="clo_id" required>${sets.clos.map(v=>`<option value="${v.id}" ${v.id===x.clo_id?'selected':''}>${esc(v.code)} — ${esc(v.description)}</option>`).join('')}</select></label><label class="field">Đáp án đúng<select name="correct_answer">${['A','B','C','D'].map(v=>`<option ${v===x.correct_answer?'selected':''}>${v}</option>`).join('')}</select></label><div class="wide option-grid">${['A','B','C','D'].map(v=>`<label class="field">Phương án ${v}<input name="opt_${v}" required value="${esc(opts[v]||'')}"></label>`).join('')}</div><label class="field wide">Lời giải<textarea name="explanation">${esc(x.explanation||'')}</textarea></label><label class="field">Trạng thái<select name="status"><option value="active">Đang dùng</option><option value="draft" ${x.status==='draft'?'selected':''}>Bản nháp</option></select></label><div class="form-actions"><button id="cancelQuestionEdit" class="secondary" type="button">Hủy</button><button class="primary" id="saveQuestion">Lưu câu hỏi</button></div></form></div>`);
 const topicSelect=()=>{$('#qtopic').innerHTML=sets.topics.filter(t=>t.chapter_id===$('#qchapter').value).map(t=>`<option value="${t.id}" ${t.id===x.topic_id?'selected':''}>${esc(t.name)}</option>`).join('')};topicSelect();$('#qchapter').onchange=topicSelect;$('#cancelQuestionEdit').onclick=backToQuestionList;
 $('#qForm').onsubmit=async e=>{e.preventDefault();let btn=$('#saveQuestion'),v=Object.fromEntries(new FormData(e.target)),optionRows=['A','B','C','D'].map(k=>({option_key:k,content:v['opt_'+k]}));['A','B','C','D'].forEach(k=>delete v['opt_'+k]);btn.disabled=true;btn.textContent='Đang lưu…';try{let id=x.id;if(x.id){let archived=await db.rpc('archive_question_revision',{p_question_id:x.id});if(archived.error)throw archived.error;v.updated_at=new Date().toISOString();let r=await db.from('questions').update(v).eq('id',x.id).select().single();if(r.error)throw r.error;let d=await db.from('question_options').delete().eq('question_id',x.id);if(d.error)throw d.error}else{Object.assign(v,{subject_id:state.subjectId,created_by:state.user.id,updated_at:new Date().toISOString()});let r=await db.from('questions').insert(v).select().single();if(r.error)throw r.error;id=r.data.id}let o=await db.from('question_options').insert(optionRows.map(z=>({...z,question_id:id})));if(o.error)throw o.error;window.logActivity?.(x.id?'update':'create','question',id,(x.id?'Cập nhật: ':'Tạo: ')+v.content.slice(0,120));toast(x.id?'Đã cập nhật và lưu lịch sử':'Đã tạo câu hỏi');await backToQuestionList()}catch(ex){err(ex);btn.disabled=false;btn.textContent='Lưu câu hỏi'}};
};
