import {auth,call} from './api.js';
import {dashboard,evidenceLinks,csv} from './core.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const now=new Date(),state={year:now.getFullYear(),month:now.getMonth()+1,manager:false,data:null,panel:'overview',busy:false,loading:false};
const fmt=n=>n===null||n===undefined?'—':new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(n);
const labels={sum:'Cộng dồn',people:'Người duy nhất',stock:'Đang thực hiện',ratio:'Tỷ lệ gần nhất'};
const statuses={pending:'Chờ duyệt',approved:'Đã duyệt',rejected:'Không duyệt',archived:'Lưu trữ'};
const actionNames={metric:'Sửa danh mục KPI',plan:'Sửa chỉ tiêu năm',month:'Nhập số liệu tháng',record:'Sửa / duyệt hồ sơ',settings:'Sửa kết nối',delegate:'Cấp / thu hồi quyền'};
let editHandler=null,requestId=0;
$('year').value=state.year;$('month').innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}">Tháng ${i+1}</option>`).join('');$('month').value=state.month;
function notice(message,error=false){$('notice').textContent=message;$('notice').className=error?'error':'';$('notice').hidden=false;}
function closeAll(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
function locked(){requestId++;state.data=null;state.manager=false;state.panel='overview';$('workspace').hidden=true;$('gate').hidden=false;sessionStorage.removeItem('kpi-view');$('viewCode').value='';$('kpiRows').replaceChildren();['recordList','metricList','managerList','auditList','summary','detailBody','editFields'].forEach(id=>$(id).replaceChildren());closeAll();}
function links(value){return evidenceLinks(value).map((url,i)=>`<a class="evidence" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Minh chứng ${i+1} ↗</a>`).join('')||'<span class="muted">Chưa có link minh chứng</span>';}
function openWorkspace(){
 $('gate').hidden=true;$('workspace').hidden=false;document.querySelectorAll('.manager-only').forEach(el=>el.hidden=!state.manager);$('identity').textContent=state.manager?(state.data.owner?'Admin':'Cán bộ nhập liệu'):'Chế độ xem';
 const url=state.data.settings.form_url;$('formLink').href=/^https:\/\/(docs\.google\.com\/forms\/|forms\.gle\/)/.test(url)?url:'#';render();switchPanel(state.panel);
}
async function load(){
 const serial=++requestId,year=state.year;state.loading=true;
 try{const data=await call(state.manager?'load':'view',{year,token:sessionStorage.getItem('kpi-view')},state.manager);if(serial!==requestId)return;state.data=data;openWorkspace();}
 catch(e){if(serial!==requestId)return;if(!state.manager&&e.status===401){locked();$('gateError').textContent=e.message;}else throw e;}
 finally{if(serial===requestId)state.loading=false;}
}
function switchPanel(panel){if(panel!=='overview'&&!state.manager)return;state.panel=panel;['overview','records','metrics','settings','audit'].forEach(id=>$(id).hidden=id!==panel);document.querySelectorAll('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===panel));$('panelTitle').textContent={overview:'Bảng theo dõi KPI',records:'Hồ sơ & phê duyệt',metrics:'Danh mục KPI',settings:'Thiết lập & phân quyền',audit:'Lịch sử thay đổi'}[panel];$('month').closest('label').hidden=panel!=='overview';}
function render(){
 if(!state.data)return;const data=state.data,rows=dashboard(data,state.year,state.month);$('monthHeading').textContent='Tháng '+state.month;
 $('summary').innerHTML=`<div><strong>${rows.length}</strong>KPI theo dõi</div><div><strong>${rows.filter(r=>r.plan.target!==null).length}</strong>Đã giao chỉ tiêu</div><div><strong>${rows.filter(r=>r.percent!==null&&r.percent>=100).length}</strong>Đạt chỉ tiêu</div>`;
 $('kpiRows').innerHTML=rows.map(r=>{const status=r.plan.target===null?'Chưa giao chỉ tiêu':r.cumulative===null?'Chưa có số liệu':r.percent!==null&&r.percent>=100?'Đạt chỉ tiêu':'Đang thực hiện';return `<tr><td>${esc(r.code)}${!r.visible?'<br><span class="pill dim">Đang ẩn</span>':''}</td><td>${esc(r.name)}<br><small class="muted">${labels[r.method]}</small></td><td>${esc(r.unit)}</td><td class="number">${r.plan.target===null?'Chưa giao':fmt(r.plan.target)}</td><td class="number">${fmt(r.cumulative)}</td><td class="number">${fmt(r.current)}</td><td class="number">${r.percent===null?'—':fmt(r.percent)+'%'}</td><td><span class="pill ${status==='Đạt chỉ tiêu'?'good':status==='Đang thực hiện'?'warn':'dim'}">${status}</span></td><td>${esc(r.plan.deadline||'—')}</td><td><button data-detail="${r.id}">Chi tiết</button>${state.manager?`<button data-plan="${r.id}">Chỉ tiêu</button><button data-month="${r.id}">Số liệu tháng</button>`:''}</td></tr>`;}).join('')||'<tr><td colspan="10">Chưa có KPI theo dõi trong năm này.</td></tr>';
 if(!state.manager)return;
 $('pendingCount').textContent=data.records.filter(r=>r.status==='pending').length||'';
 $('syncStatus').textContent=data.settings.sync_error?'Đồng bộ lỗi: '+data.settings.sync_error:data.settings.synced_at?'Đồng bộ: '+new Date(data.settings.synced_at).toLocaleString('vi-VN'):'Chưa đồng bộ';
 renderRecords();$('metricList').innerHTML=data.metrics.map(m=>`<div class="metric-card"><h3>${esc(m.code)} · ${esc(m.name)}</h3><span class="pill ${m.archived?'dim':m.visible?'good':'warn'}">${m.archived?'Lưu trữ':m.visible?'Hiển thị':'Tạm ẩn'}</span> <span class="muted">${labels[m.method]} · Thứ tự ${m.position}</span><div class="toolbar"><button data-metric="${m.id}">Sửa mục</button><button data-plan="${m.id}">Chỉ tiêu / Theo dõi năm</button></div></div>`).join('');
 $('pinStatus').textContent=data.owner&&data.current_code?'Mã xem hiện tại: '+data.current_code:data.pin_set?'Đã thiết lập mã xem.'+(data.owner?' Lưu lại mã để hiển thị mã hiện tại.':''):'Chưa thiết lập mã. Trang xem sẽ được khóa cho đến khi bạn lưu mã.';
 const form=$('settingsForm');['sheet_id','sheet_name','form_url','sync_minutes'].forEach(k=>form.elements[k].value=data.settings[k]);form.elements.auto_sync.checked=data.settings.auto_sync;
 $('googleConnection').textContent=data.google_email?'Chia sẻ Sheet quyền Người xem cho: '+data.google_email:'Chưa cấu hình tài khoản kết nối Google ở máy chủ.';
 $('delegationPanel').hidden=!data.owner;$('managerList').innerHTML=data.managers.map(p=>`<div class="metric-card"><strong>${esc(p.name||p.email)}</strong> <span class="muted">${esc(p.email)}</span><div class="toolbar"><button data-delegate="${p.id}" data-enabled="${!p.assigned}">${p.assigned?'Thu hồi quyền':'Bổ nhiệm cán bộ'}</button></div></div>`).join('')||'<p class="muted">Chưa có tài khoản giảng viên đang hoạt động.</p>';
 $('auditList').innerHTML=data.audit.map(a=>`<div class="audit-item"><strong>${esc(actionNames[a.action]||a.action)}</strong> · ${esc(a.actor_name)}<small>${new Date(a.created_at).toLocaleString('vi-VN')}${a.object_id?' · '+esc(a.object_id):''}</small></div>`).join('')||'<p class="muted">Chưa có thay đổi.</p>';
}
function renderRecords(){const status=$('recordStatus').value,query=$('recordSearch').value.toLocaleLowerCase('vi');$('recordList').innerHTML=state.data.records.filter(r=>(status==='all'||r.status===status)&&[r.effective.title,r.effective.reporter,r.effective.type].join(' ').toLocaleLowerCase('vi').includes(query)).map(r=>`<article class="record-card"><h3>${esc(r.effective.title)}</h3><span class="pill ${r.status==='approved'?'good':r.status==='pending'?'warn':'dim'}">${statuses[r.status]}</span> ${r.source_changed?'<span class="pill warn">Nguồn đã đổi · cần rà soát</span>':''}<p class="muted">${esc(r.effective.type)} · ${esc(r.effective.reporter)} · ${r.month}/${r.year}</p><p>${esc(r.effective.info)}</p>${links(r.effective.evidence)}<div class="toolbar"><button data-record="${r.id}">Mở / chỉnh sửa / duyệt</button></div></article>`).join('')||'<p class="muted">Không có hồ sơ phù hợp.</p>';}
function field(name,title,value='',type='text',extra=''){return `<label ${extra.includes('wide')?'class="wide"':''}>${title}<input name="${name}" type="${type}" value="${esc(value??'')}" ${extra.replace('wide','')}></label>`;}
function select(name,title,value,options){return `<label>${title}<select name="${name}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;}
function textarea(name,title,value){return `<label class="wide">${title}<textarea name="${name}">${esc(value??'')}</textarea></label>`;}
function check(name,title,value){return `<label class="check"><input name="${name}" type="checkbox" ${value?'checked':''}>${title}</label>`;}
function edit(title,html,handler){$('editTitle').textContent=title;$('editFields').innerHTML=html;$('editForm').querySelector('.dialog-error').textContent='';editHandler=handler;$('editDialog').showModal();}
function values(form){return Object.fromEntries(new FormData(form));}
async function save(action,payload){await call(action,payload,true);await load();notice('Đã lưu thay đổi.');}
function editMetric(id){const m=state.data.metrics.find(x=>x.id===id)??{code:'',name:'',unit:'Hồ sơ',method:'sum',position:state.data.metrics.length*10+10,visible:true,archived:false};edit(id?'Chỉnh sửa KPI':'Thêm KPI',field('code','Mã KPI',m.code,'text','required maxlength="50"')+field('name','Tên nội dung',m.name,'text','required maxlength="500"')+field('unit','Đơn vị',m.unit)+select('method','Cách tính',m.method,Object.entries(labels))+field('position','Thứ tự',m.position,'number','required')+check('visible','Hiện trên trang xem',m.visible)+check('archived','Lưu trữ mục (giữ lịch sử)',m.archived),async form=>save('metric',{...values(form),id,visible:form.elements.visible.checked,archived:form.elements.archived.checked}));}
function editPlan(id){const m=state.data.metrics.find(x=>x.id===id),p=state.data.plans.find(x=>x.metric_id===id)??{target:null,active:true};edit('Chỉ tiêu '+state.year+' · '+m.code,field('target','Chỉ tiêu năm (để trống nếu chưa giao)',p.target,'number','min="0" step="any"')+field('deadline','Hạn hoàn thành',p.deadline,'date')+check('active','Theo dõi trong năm này',p.active),async form=>save('plan',{...values(form),year:state.year,metric_id:id,active:form.elements.active.checked}));}
function editMonth(id){const m=state.data.metrics.find(x=>x.id===id),v=state.data.months.find(x=>x.metric_id===id&&x.month===state.month)??{};edit('Số liệu tháng '+state.month+'/'+state.year+' · '+m.code,field('month','Tháng',state.month,'number','min="1" max="12" required')+field('value',m.method==='ratio'?'Tỷ lệ % (hoặc dùng tử / mẫu)':'Số liệu thay thế tháng (để trống để dùng hồ sơ)',v.value,'number',`min="0" ${m.method==='ratio'?'max="100"':''} step="any"`)+(m.method==='ratio'?field('numerator','Tử số',v.numerator,'number','min="0" step="any"')+field('denominator','Mẫu số',v.denominator,'number','min="0.000001" step="any"'):'')+textarea('reason','Nguồn số liệu / lý do điều chỉnh',v.reason),async form=>save('month',{...values(form),year:state.year,metric_id:id}));}
function editRecord(id){const r=state.data.records.find(x=>x.id===id)??{effective:{title:'',quantity:1},year:state.year,month:state.month,status:'pending'},e=r.effective;const original=r.source_key?`<details class="wide"><summary>Bản gốc từ Google Form${r.source_changed?' (đã thay đổi)':''}</summary><pre>${esc(JSON.stringify(r.source_data,null,2))}</pre></details>`:'';
 edit('Rà soát hồ sơ',original+field('title','Tên nội dung / kết quả',e.title,'text','wide required maxlength="1000"')+field('type','Loại nội dung',e.type)+field('reporter','Người khai báo / tác giả',e.reporter)+textarea('info','Thông tin thêm',e.info)+textarea('evidence','Link minh chứng (mỗi link một dòng)',e.evidence)+select('metric_id','Ghi nhận vào KPI',r.metric_id??'',[['','Chưa phân loại'],...state.data.metrics.filter(m=>!m.archived&&!['V.1','V.2','VII.5'].includes(m.code)&&m.method!=='ratio').map(m=>[m.id,m.code+' · '+m.name])])+field('quantity','Số lượng',e.quantity??1,'number','min="0.000001" step="any" required')+field('dedup_key','Định danh: DOI, số đơn, mã nhiệm vụ / chuyên gia',e.dedup_key)+field('year','Năm ghi nhận',r.year,'number','min="2000" max="2100" required')+field('month','Tháng ghi nhận',r.month,'number','min="1" max="12" required')+field('start_date','Nhiệm vụ: ngày bắt đầu',e.start_date,'date')+field('end_date','Nhiệm vụ: ngày ngừng tính đang thực hiện',e.end_date,'date')+select('status','Phê duyệt',r.status,Object.entries(statuses))+textarea('review_note','Ghi chú rà soát',r.review_note),async form=>{const v=values(form);return save('record',{id,version:r.version,year:+v.year,month:+v.month,metric_id:v.metric_id,status:v.status,review_note:v.review_note,effective:Object.fromEntries(['title','type','reporter','info','evidence','quantity','dedup_key','start_date','end_date'].map(k=>[k,v[k]]))});});
}
function details(id){const m=dashboard(state.data,state.year,state.month).find(x=>x.id===id);$('detailTitle').textContent=m.code+' · '+m.name;$('detailBody').innerHTML=`<p class="muted">${labels[m.method]} · ${m.unit}</p><div class="table-wrap"><table><thead><tr>${m.periods.map((_,i)=>`<th>T${i+1}</th>`).join('')}</tr></thead><tbody><tr>${m.periods.map(v=>`<td>${fmt(v)}</td>`).join('')}</tr></tbody></table></div><h3>Hồ sơ đã duyệt</h3>`+m.records.filter(r=>r.month<=state.month||m.method==='stock').map(r=>`<article class="record-card"><strong>${esc(r.effective.title)}</strong><p class="muted">${esc(r.effective.reporter)} · ${r.month}/${r.year}</p>${links(r.effective.evidence)}</article>`).join('')+`<h3>Số liệu nhập theo tháng</h3>`+state.data.months.filter(v=>v.metric_id===id&&v.value!==null).map(v=>`<p>T${v.month}: <strong>${fmt(v.value)}</strong> · ${esc(v.reason)}</p>`).join('');$('detailDialog').showModal();}
async function sync(force=false){if(!state.manager||state.busy||state.loading||document.querySelector('dialog[open]'))return;state.busy=true;$('syncButton').disabled=true;$('syncButton').textContent='Đang đồng bộ…';try{const result=await call('sync',{force},true);if(!state.manager)return;if(!result.skipped){await load();notice('Đồng bộ hoàn tất: '+result.changed+' hồ sơ mới / thay đổi vào Chờ duyệt.');}else if(force)notice('Một phiên đồng bộ đang chạy. Chờ hoàn tất rồi tải lại.');}catch(e){if(state.manager){notice(e.message,true);try{await load();}catch{}}}finally{state.busy=false;$('syncButton').disabled=false;$('syncButton').textContent='Đồng bộ ngay';}}
async function run(button,fn){if(button.disabled)return;button.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{button.disabled=false;}}
$('unlockForm').addEventListener('submit',async event=>{event.preventDefault();const b=event.submitter;b.disabled=true;$('gateError').textContent='';try{const result=await call('unlock',{code:$('viewCode').value});sessionStorage.setItem('kpi-view',result.token);state.manager=false;await load();$('viewCode').value='';}catch(e){$('gateError').textContent=e.message;}finally{b.disabled=false;}});
$('loginButton').onclick=()=>{$('loginForm').querySelector('.dialog-error').textContent='';$('loginDialog').showModal();};
$('loginForm').addEventListener('submit',async event=>{event.preventDefault();const b=event.submitter;b.disabled=true;try{const v=values(event.target),{error}=await auth.signInWithPassword({email:v.email.trim(),password:v.password});if(error)throw Error('Email hoặc mật khẩu chưa đúng.');state.manager=true;try{await load();}catch(e){state.manager=false;await auth.signOut();throw e;}$('loginDialog').close();event.target.elements.password.value='';}catch(e){event.target.querySelector('.dialog-error').textContent=e.message;}finally{b.disabled=false;}});
$('editForm').addEventListener('submit',async event=>{event.preventDefault();const b=event.submitter;b.disabled=true;try{await editHandler(event.target);$('editDialog').close();}catch(e){event.target.querySelector('.dialog-error').textContent=e.message;}finally{b.disabled=false;}});
$('pinForm').addEventListener('submit',event=>{event.preventDefault();run(event.submitter,async()=>{await save('pin',values(event.target));event.target.reset();notice('Đã đổi mã xem. Các phiên xem cũ đã kết thúc.');});});
$('settingsForm').addEventListener('submit',event=>{event.preventDefault();run(event.submitter,()=>save('settings',{...values(event.target),auto_sync:event.target.elements.auto_sync.checked}));});
$('exitButton').onclick=async()=>{const manager=state.manager;locked();if(manager)await auth.signOut();};
$('refreshButton').onclick=event=>run(event.target,load);$('syncButton').onclick=()=>sync(true);$('helpButton').onclick=()=>$('helpDialog').showModal();$('newMetric').onclick=()=>editMetric(null);$('newRecord').onclick=()=>editRecord(null);
$('year').onchange=event=>{const year=+event.target.value;if(!Number.isInteger(year)||year<2000||year>2100){event.target.value=state.year;return;}state.year=year;run($('refreshButton'),load);};$('month').onchange=event=>{state.month=+event.target.value;render();};
$('recordStatus').onchange=renderRecords;$('recordSearch').oninput=renderRecords;
$('sideNav').onclick=event=>{const b=event.target.closest('[data-panel]');if(b)switchPanel(b.dataset.panel);};
$('workspace').addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;const d=b.dataset;if(d.detail)details(d.detail);if(!state.manager)return;if(d.metric)editMetric(d.metric);if(d.plan)editPlan(d.plan);if(d.month)editMonth(d.month);if(d.record)editRecord(d.record);if(d.delegate)run(b,()=>save('delegate',{user_id:d.delegate,enabled:d.enabled==='true'}));});
$('exportButton').onclick=()=>{const rows=dashboard(state.data,state.year,state.month);const output=csv([['Năm', 'Mã KPI','Nội dung','Đơn vị','Chỉ tiêu năm',...Array.from({length:12},(_,i)=>'Tháng '+(i+1)),'Lũy kế / hiện tại tháng '+state.month],...rows.map(r=>[state.year,r.code,r.name,r.unit,r.plan.target,...r.periods,r.cumulative])]);const url=URL.createObjectURL(new Blob([output],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`KPI-CB2-${state.year}.csv`;a.click();URL.revokeObjectURL(url);};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
setInterval(()=>{if(!document.hidden&&state.manager)sync(false);},60000);
// Expiring a viewer session clears data already displayed, even when the page remains open.
setInterval(async()=>{if(!document.hidden&&!state.manager&&state.data){try{await load();}catch(e){notice(e.message,true);}}},120000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.manager)sync(false);else if(!document.hidden&&state.data)load().catch(e=>notice(e.message,true));});
(async()=>{try{const {data}=await auth.getSession();if(data.session){state.manager=true;try{await load();return;}catch{state.manager=false;await auth.signOut();}}if(sessionStorage.getItem('kpi-view'))await load();}catch(e){$('gateError').textContent=e.message;}})();
