/* AI-CLO PTITHCM V11.8 — standard AI-CLO app window for every modal popup. */
(()=>{
'use strict';
let queued=false,observer=null,hookInstalled=false;
function legacyAssessmentForm(){return document.querySelector('#modal #matrixAssessmentForm, #modal #assessmentForm')}
function normalizeLegacyAssessment(form){if(!form)return;const current=form.elements.namedItem('exam_type');if(current&&current.tagName==='SELECT')current.closest('label')?.remove();let hidden=form.querySelector('input[type="hidden"][name="exam_type"]');if(!hidden){hidden=document.createElement('input');hidden.type='hidden';hidden.name='exam_type';form.append(hidden)}hidden.value='chapter_test';form.classList.add('assessment-window-form');const d=form.elements.namedItem('description');if(d&&!d.dataset.aicloCompact){d.dataset.aicloCompact='1';d.setAttribute('rows','2')}}
function enhanceModal(){const dialog=document.querySelector('#modal');if(!dialog?.open)return null;normalizeLegacyAssessment(legacyAssessmentForm());const title=dialog.querySelector('#modalTitle');if(title){let t=String(title.textContent||'').trim();if(t&&!/^AI-CLO\s*\|/i.test(t))title.textContent=`AI-CLO | ${t}`}
 dialog.querySelectorAll('.form-actions').forEach(x=>x.classList.add('assessment-window-footer'));const body=dialog.querySelector('#modalBody');if(body&&dialog.dataset.aicloWindowFresh!=='1'){body.scrollTop=0;body.scrollLeft=0}
 if(dialog.dataset.aicloStandardWindow!=='1'){dialog.dataset.aicloStandardWindow='1';dialog.dataset.aicloWindowFresh='1';if(window.AICLO_APP_WINDOW?.open)window.AICLO_APP_WINDOW.open(dialog,{className:'assessment-window-modal',width:900,height:680});else dialog.classList.add('quick-edit-modal','assessment-window-modal');requestAnimationFrame(()=>delete dialog.dataset.aicloWindowFresh);dialog.addEventListener('close',()=>{delete dialog.dataset.aicloStandardWindow;delete dialog.dataset.aicloWindowFresh;dialog.classList.remove('assessment-window-modal');legacyAssessmentForm()?.classList.remove('assessment-window-form')},{once:true})}return dialog}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhanceModal()})}
function installHook(){if(hookInstalled)return;const base=window.modal;if(typeof base!=='function')return;if(base.__aicloStandardWindow){hookInstalled=true;return}const wrapped=function(title,html,...args){const result=base.call(this,title,html,...args);queue();return result};wrapped.__aicloStandardWindow=true;wrapped.__aicloBase=base;window.modal=wrapped;hookInstalled=true}
function init(){installHook();const modal=document.querySelector('#modal');if(modal&&!observer){observer=new MutationObserver(queue);observer.observe(modal,{childList:true,subtree:true,attributes:true,attributeFilter:['open']})}queue()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();window.AICLO_ASSESSMENT_WINDOW=Object.freeze({version:'11.8.0',enhance:enhanceModal,open:enhanceModal});
})();