/* AI-CLO PTITHCM V12.0 — one 4-step wizard for Bài kiểm tra and Bài thi cuối kỳ. */
(()=>{
'use strict';
const VERSION='12.0.0';
let wizard=null;
const $=s=>document.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>window.esc?window.esc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sw=(name,text,val)=>`<label class="aiclo-switch-row"><span>${text}</span><span class="aiclo-switch"><input type="checkbox" name="${name}" ${val?'checked':''}><i></i></span></label>`;
const iso=v=>v?new Date(v).toISOString():null;
const cell=(mode,id,cloId)=>`${mode==='topic_clo'?'t':'c'}:${id}:${cloId}`;
const totalMatrix=()=>Object.values(wizard?.matrix||{}).reduce((s,n)=>s+(+n||0),0);
const selectedChapters=()=>wizard.sets.chapters.filter(ch=>wizard.chapters.has(ch.id));
const selectedTopics=chId=>wizard.sets.topics.filter(tp=>wizard.topics.has(tp.id)&&(!chId||tp.chapter_id===chId));
function injectCss(){if(document.querySelector('link[data-aiclo-create-wizard]'))return;let l=document.createElement('link');l.rel='stylesheet';l.href='css/exams/create-wizard.css?v=12.0.0';l.dataset.aicloCreateWizard='1';document.head.appendChild(l)}
async function loadSets(kind){
 const [chapters,clos]=await Promise.all([
  q('chapters','*',x=>contentFilter(x).order('order_index')),
  q('clos','*',x=>contentFilter(x).order('code'))
 ]);
 const ids=chapters.map(x=>x.id);
 const topics=ids.length?await q('topics','*',x=>x.in('chapter_id',ids).order('order_index')):[];
 let questions=await q('questions','id,subject_id,display_code,question_bank_id,chapter_id,topic_id,clo_id,content,correct_answer,explanation,status,question_scope,approval_status,question_options(id,option_key,content)',x=>contentFilter(x).eq('status','active').eq('approval_status','approved'));
 const allowed=kind==='final'?['secure_exam','both']:['practice','both'];
 questions=questions.filter(x=>{let ks=(x.question_options||[]).map(o=>String(o.option_key||'').toUpperCase());return allowed.includes(x.question_scope)&&ks.length===4&&new Set(ks).size===4&&['A','B','C','D'].every(k=>ks.includes(k))});
 return {chapters,topics,clos,questions};
}
function defaults(kind,sets){
 const common={title:'',description:'',duration_minutes:kind==='final'?80:30};
 const settings=kind==='final'?{...common,exam_date:'',exam_session:'',semester:'',school_year:'',variant_count:4}:{...common,max_attempts:1,question_mode:'common_fixed',score_policy:'highest',opens_at:'',closes_at:'',show_answers:false,shuffle_questions:true,shuffle_options:true,allow_ai_feedback:true,counts_toward_grade:true,status:'draft'};
 return {kind,step:1,sets,settings,chapters:new Set(),topics:new Set(),structureMode:'topic_clo',matrix:{}};
}
function openWindow(){let d=$('#modal');if(window.AICLO_APP_WINDOW?.open)window.AICLO_APP_WINDOW.open(d,{className:'assessment-window-modal aiclo-create-wizard-modal',width:940,height:720});else d.classList.add('quick-edit-modal','assessment-window-modal','aiclo-create-wizard-modal')}
function modalOpen(title,html){modal(title,html);openWindow()}
function footer(final=false){let label=final?(wizard.kind==='final'?'Tạo bản nháp đề thi →':'Tạo bản nháp và rút câu →'):'Tiếp tục →';return `<div class="aiclo-wizard-footer"><button id="cwBack" type="button" class="secondary" ${wizard.step===1?'disabled':''}>← Quay lại</button><span class="aiclo-wizard-step">Bước ${wizard.step}/4</span><button id="cwNext" type="button" class="primary">${label}</button></div>`}
function capture(){let f=$('#cwForm');if(!f)return;
 if(wizard.step===1){let v=Object.fromEntries(new FormData(f)),s=wizard.settings;if(wizard.kind==='final')wizard.settings={...s,title:(v.title||'').trim(),description:(v.description||'').trim(),duration_minutes:Math.max(1,+v.duration_minutes||80),exam_date:v.exam_date||'',exam_session:(v.exam_session||'').trim(),semester:(v.semester||'').trim(),school_year:(v.school_year||'').trim(),variant_count:Math.max(1,+v.variant_count||4)};else wizard.settings={...s,title:(v.title||'').trim(),description:(v.description||'').trim(),duration_minutes:Math.max(1,+v.duration_minutes||30),max_attempts:Math.max(1,+v.max_attempts||1),question_mode:v.question_mode||'common_fixed',score_policy:v.score_policy||'highest',opens_at:v.opens_at||'',closes_at:v.closes_at||'',show_answers:!!f.show_answers?.checked,shuffle_questions:!!f.shuffle_questions?.checked,shuffle_options:!!f.shuffle_options?.checked,allow_ai_feedback:!!f.allow_ai_feedback?.checked,counts_toward_grade:!!f.counts_toward_grade?.checked}}
 if(wizard.step===2){wizard.structureMode=f.querySelector('[name="structure_mode"]:checked')?.value||wizard.structureMode;wizard.chapters=new Set($$('[data-cw-chapter]:checked',f).map(x=>x.value));wizard.topics=new Set($$('[data-cw-topic]:checked',f).map(x=>x.value));pruneMatrix()}
 if(wizard.step===3)$$('.cw-matrix-input',f).forEach(i=>wizard.matrix[i.dataset.key]=Math.max(0,+i.value||0));
}
function validate(){capture();let s=wizard.settings;if(wizard.step===1){if(!s.title)return toast(wizard.kind==='final'?'Hãy nhập tên bài thi cuối kỳ':'Hãy nhập tên bài kiểm tra',true),false;if(wizard.kind!=='final'&&s.opens_at&&s.closes_at&&new Date(s.closes_at)<=new Date(s.opens_at))return toast('Thời gian đóng phải sau thời gian mở',true),false;return true}if(wizard.step===2){if(!wizard.chapters.size)return toast('Hãy chọn ít nhất một chương',true),false;for(let ch of wizard.chapters)if(!selectedTopics(ch).length)return toast('Mỗi chương được chọn cần có ít nhất một mục được chọn',true),false;return true}if(wizard.step===3){if(totalMatrix()<1)return toast('Ma trận cần ít nhất một câu',true),false;for(let [k,v] of Object.entries(wizard.matrix)){let [kind,id,cloId]=k.split(':'),have=availability(kind,id,cloId);if(+v>have)return toast(`Một ô cần ${v} nhưng chỉ có ${have} câu`,true),false}return true}return true}
function pruneMatrix(){let allowed=new Set();if(wizard.structureMode==='topic_clo'){for(let tp of selectedTopics())for(let c of wizard.sets.clos)allowed.add(cell('topic_clo',tp.id,c.id))}else{for(let ch of selectedChapters())for(let c of wizard.sets.clos)allowed.add(cell('chapter_pool',ch.id,c.id))}for(let k of Object.keys(wizard.matrix))if(!allowed.has(k))delete wizard.matrix[k]}
function availability(kind,id,cloId){if(kind==='t')return wizard.sets.questions.filter(q=>q.topic_id===id&&q.clo_id===cloId).length;return wizard.sets.questions.filter(q=>q.chapter_id===id&&wizard.topics.has(q.topic_id)&&q.clo_id===cloId).length}
function bindFooter(){let b=$('#cwBack'),n=$('#cwNext');if(b)b.onclick=()=>{if(wizard.step>1){capture();wizard.step--;renderStep()}};if(n)n.onclick=async()=>{if(!validate())return;if(wizard.step<4){wizard.step++;renderStep()}else if(wizard.kind==='final')await createFinalDraft(n);else await createTest(n)}}
function step1(){let s=wizard.settings;if(wizard.kind==='final')return `<form id="cwForm" class="aiclo-wizard-form"><div class="aiclo-wizard-head"><b>1. Thông tin bài thi cuối kỳ</b><span>Nhập thông tin hành chính và kỹ thuật của đề. Đề cuối kỳ không có các công tắc dành cho bài kiểm tra trực tuyến.</span></div><label class="field wide">Tên bài thi<input name="title" required value="${esc(s.title)}" placeholder="Ví dụ: Thi kết thúc học phần"></label><label class="field wide">Mô tả / ghi chú<textarea name="description" rows="2">${esc(s.description)}</textarea></label><label class="field">Thời gian thi (phút)<input name="duration_minutes" type="number" min="1" max="300" value="${s.duration_minutes}"></label><label class="field">Số mã đề<input name="variant_count" type="number" min="1" max="20" value="${s.variant_count}"></label><label class="field">Ngày thi<input name="exam_date" type="date" value="${esc(s.exam_date)}"></label><label class="field">Ca thi<input name="exam_session" value="${esc(s.exam_session)}" placeholder="Ví dụ: Ca 1"></label><label class="field">Học kỳ<input name="semester" value="${esc(s.semester)}" placeholder="Ví dụ: HK1"></label><label class="field">Năm học<input name="school_year" value="${esc(s.school_year)}" placeholder="Ví dụ: 2026–2027"></label><div class="wide aiclo-source-note secure"><b>Nguồn câu hỏi</b><span>Chỉ dùng Ngân hàng đề thi – bảo mật.</span></div>${footer(false)}</form>`;
 return `<form id="cwForm" class="aiclo-wizard-form"><div class="aiclo-wizard-head"><b>1. Thông tin bài kiểm tra</b><span>Tổng số câu không nhập riêng; hệ thống tự tính từ ma trận ở Bước 3.</span></div><label class="field wide">Tên bài<input name="title" required value="${esc(s.title)}"></label><label class="field wide">Mô tả<textarea name="description" rows="2">${esc(s.description)}</textarea></label><label class="field">Thời gian (phút)<input name="duration_minutes" type="number" min="1" max="300" value="${s.duration_minutes}"></label><label class="field">Số lần được làm<input name="max_attempts" type="number" min="1" max="100" value="${s.max_attempts}"></label><label class="field">Cách ghi nhận<select name="score_policy"><option value="highest" ${s.score_policy==='highest'?'selected':''}>Điểm cao nhất</option><option value="latest" ${s.score_policy==='latest'?'selected':''}>Lần cuối</option><option value="average" ${s.score_policy==='average'?'selected':''}>Trung bình</option></select></label><label class="field">Cách rút câu<select name="question_mode"><option value="common_fixed" ${s.question_mode==='common_fixed'?'selected':''}>Đề chung cố định</option><option value="student_fixed" ${s.question_mode==='student_fixed'?'selected':''}>Đề riêng cố định theo sinh viên</option><option value="attempt_random" ${s.question_mode==='attempt_random'?'selected':''}>Rút lại ở mỗi lần làm</option></select></label><label class="field">Mở từ<input name="opens_at" type="datetime-local" value="${esc(s.opens_at)}"></label><label class="field">Đóng lúc<input name="closes_at" type="datetime-local" value="${esc(s.closes_at)}"></label><div class="wide clo-switch-grid">${sw('counts_toward_grade','Tính vào kết quả CLO học phần',s.counts_toward_grade)}${sw('show_answers','Cho xem đáp án/lời giải sau khi nộp',s.show_answers)}${sw('shuffle_questions','Trộn thứ tự câu hỏi',s.shuffle_questions)}${sw('shuffle_options','Trộn thứ tự phương án A–D',s.shuffle_options)}${sw('allow_ai_feedback','Cho phép sinh viên nhận xét AI',s.allow_ai_feedback)}</div><div class="wide aiclo-source-note"><b>Nguồn câu hỏi</b><span>Chỉ dùng Ngân hàng luyện tập – kiểm tra.</span></div>${footer(false)}</form>`}
function step2(){let chapters=wizard.sets.chapters;return `<form id="cwForm" class="aiclo-wizard-form"><div class="aiclo-wizard-head"><b>2. Phạm vi và cách gom câu</b><span>Tick trực tiếp một hoặc nhiều chương. Trong mỗi chương chỉ các mục được tick mới được dùng; mục không chọn tuyệt đối không tham gia pool.</span></div><div class="wide aiclo-structure-mode"><label class="${wizard.structureMode==='topic_clo'?'selected':''}"><input type="radio" name="structure_mode" value="topic_clo" ${wizard.structureMode==='topic_clo'?'checked':''}><b>CLO cho mỗi mục</b><span>Mỗi mục có phân bố CLO riêng.</span></label><label class="${wizard.structureMode==='chapter_pool'?'selected':''}"><input type="radio" name="structure_mode" value="chapter_pool" ${wizard.structureMode==='chapter_pool'?'checked':''}><b>CLO chung các mục thuộc chương</b><span>Chỉ gom các mục đã chọn và vẫn tách riêng từng chương.</span></label></div><div class="aiclo-chapter-choice wide">${chapters.map(ch=>{let on=wizard.chapters.has(ch.id),topics=wizard.sets.topics.filter(t=>t.chapter_id===ch.id);return `<article class="${on?'selected':''}" data-cw-chapter-card="${ch.id}"><label class="chapter-line"><input type="checkbox" data-cw-chapter value="${ch.id}" ${on?'checked':''}> <b>${esc(ch.order_index)}. ${esc(ch.name)}</b></label><div class="aiclo-topic-choice" ${on?'':'hidden'}>${topics.map(tp=>`<label><input type="checkbox" data-cw-topic data-chapter="${ch.id}" value="${tp.id}" ${wizard.topics.has(tp.id)?'checked':''}> ${esc(tp.name)}</label>`).join('')||'<span class="hint">Chương này chưa có mục.</span>'}</div></article>`}).join('')}</div>${footer(false)}</form>`}
function matrixRows(){if(wizard.structureMode==='topic_clo'){let html='';for(let ch of selectedChapters()){let ts=selectedTopics(ch.id);html+=`<tr class="cw-chapter-row"><td colspan="${wizard.sets.clos.length+2}"><b>${esc(ch.order_index)}. ${esc(ch.name)}</b></td></tr>`+ts.map(tp=>rowHtml('t',tp.id,tp.name)).join('')}return html}return selectedChapters().map(ch=>rowHtml('c',ch.id,`${ch.order_index}. ${ch.name}`)).join('')}
function rowHtml(kind,id,label){return `<tr data-cw-row="${kind}:${id}"><td><b>${esc(label)}</b>${kind==='c'?`<small>${esc(selectedTopics(id).map(t=>t.name).join(', '))}</small>`:''}</td>${wizard.sets.clos.map(c=>{let k=`${kind}:${id}:${c.id}`,n=availability(kind,id,c.id);return `<td><div class="clo-matrix-cell"><input class="cw-matrix-input" type="number" min="0" max="${n}" value="${wizard.matrix[k]||0}" data-key="${k}"><span>(${n})</span></div></td>`}).join('')}<td><b data-cw-row-total="${kind}:${id}">0</b></td></tr>`}
function step3(){return `<form id="cwForm" class="aiclo-wizard-form"><div class="aiclo-wizard-head"><b>3. Ma trận câu hỏi</b><span>${wizard.structureMode==='topic_clo'?'Nhập số câu cho từng Mục × CLO.':'Nhập số câu theo Chương × CLO; số trong ngoặc chỉ tính từ các mục đã chọn của chương.'} Tổng số câu được tính tự động.</span></div><div class="wide aiclo-wizard-matrix"><div class="table-wrap"><table class="exam-matrix cw-matrix"><thead><tr><th>${wizard.structureMode==='topic_clo'?'Mục':'Chương'}</th>${wizard.sets.clos.map(c=>`<th>${esc(c.code)}</th>`).join('')}<th>Tổng</th></tr></thead><tbody>${matrixRows()}<tr class="matrix-grand"><td><b>TỔNG</b></td>${wizard.sets.clos.map(c=>`<td><b data-cw-clo-total="${c.id}">0</b></td>`).join('')}<td><b id="cwGrandTotal">${totalMatrix()}</b></td></tr></tbody></table></div><div class="ub-matrix-status ok">Tổng số câu của bài: <b id="cwTotalLabel">${totalMatrix()}</b></div></div>${footer(false)}</form>`}
function cloTotals(){let o={};for(let c of wizard.sets.clos)o[c.id]=0;for(let [k,n] of Object.entries(wizard.matrix)){let id=k.split(':')[2];o[id]=(o[id]||0)+(+n||0)}return o}
function step4(){let s=wizard.settings,ct=cloTotals(),chs=selectedChapters().map(x=>x.name).join(', '),mode=wizard.structureMode==='topic_clo'?'CLO cho mỗi mục':'CLO chung các mục thuộc chương';return `<form id="cwForm" class="aiclo-wizard-form"><div class="aiclo-wizard-head"><b>4. Xác nhận</b><span>Kiểm tra lại cấu hình trước khi tạo bản nháp.</span></div><div class="aiclo-wizard-review wide"><div><b>Loại</b><span>${wizard.kind==='final'?'Bài thi cuối kỳ':'Bài kiểm tra'}</span></div><div><b>Tên</b><span>${esc(s.title)}</span></div><div><b>Phạm vi</b><span>${esc(chs)}</span></div><div><b>Cách gom</b><span>${esc(mode)}</span></div><div><b>Tổng số câu</b><span>${totalMatrix()} câu</span></div><div><b>Phân bố CLO</b><span>${wizard.sets.clos.map(c=>`${esc(c.code)}: ${ct[c.id]||0}`).join(' · ')}</span></div>${wizard.kind==='final'?`<div><b>Nguồn câu</b><span>Ngân hàng đề thi – bảo mật</span></div><div><b>Thông tin thi</b><span>${s.duration_minutes} phút · ${s.variant_count} mã đề${s.exam_date?' · '+esc(s.exam_date):''}</span></div>`:`<div><b>Nguồn câu</b><span>Ngân hàng luyện tập – kiểm tra</span></div><div><b>Kết quả CLO học phần</b><span>${s.counts_toward_grade?'Có tính':'Không tính'}</span></div><div><b>AI sinh viên</b><span>${s.allow_ai_feedback?'Bật':'Tắt'}</span></div><div><b>Thời gian</b><span>${s.duration_minutes} phút · ${s.max_attempts} lượt</span></div>`}</div>${footer(true)}</form>`}
function renderStep(){injectCss();let title=`AI-CLO | ${wizard.kind==='final'?'Bài thi cuối kỳ':'Bài kiểm tra'}`;modalOpen(title,[step1,step2,step3,step4][wizard.step-1]());if(wizard.step===2)bindScope();if(wizard.step===3)bindMatrix();bindFooter()}
function bindScope(){let f=$('#cwForm');$$('[data-cw-chapter]',f).forEach(ch=>ch.onchange=()=>{let id=ch.value,card=f.querySelector(`[data-cw-chapter-card="${id}"]`),box=card?.querySelector('.aiclo-topic-choice');if(ch.checked){wizard.chapters.add(id);let topics=wizard.sets.topics.filter(t=>t.chapter_id===id);topics.forEach(t=>wizard.topics.add(t.id));if(box){box.hidden=false;$$('[data-cw-topic]',box).forEach(t=>t.checked=true)}card?.classList.add('selected')}else{wizard.chapters.delete(id);wizard.sets.topics.filter(t=>t.chapter_id===id).forEach(t=>wizard.topics.delete(t.id));if(box)box.hidden=true;card?.classList.remove('selected')}pruneMatrix()});$$('[data-cw-topic]',f).forEach(tp=>tp.onchange=()=>{tp.checked?wizard.topics.add(tp.value):wizard.topics.delete(tp.value);pruneMatrix()});$$('[name="structure_mode"]',f).forEach(r=>r.onchange=()=>{wizard.structureMode=r.value;wizard.matrix={};renderStep()})}
function bindMatrix(){let f=$('#cwForm');$$('.cw-matrix-input',f).forEach(i=>i.oninput=()=>{let max=+i.max||0,v=Math.max(0,Math.min(max,+i.value||0));i.value=v;wizard.matrix[i.dataset.key]=v;updateTotals()});updateTotals()}
function updateTotals(){let f=$('#cwForm');if(!f)return;$$('[data-cw-row-total]',f).forEach(el=>{let [kind,id]=el.dataset.cwRowTotal.split(':'),n=wizard.sets.clos.reduce((s,c)=>s+(+wizard.matrix[`${kind}:${id}:${c.id}`]||0),0);el.textContent=n});for(let c of wizard.sets.clos){let n=Object.entries(wizard.matrix).filter(([k])=>k.endsWith(`:${c.id}`)).reduce((s,[,v])=>s+(+v||0),0),el=f.querySelector(`[data-cw-clo-total="${c.id}"]`);if(el)el.textContent=n}let n=totalMatrix();if($('#cwGrandTotal'))$('#cwGrandTotal').textContent=n;if($('#cwTotalLabel'))$('#cwTotalLabel').textContent=n}
function pickQuestions(){let out=[],used=new Set();for(let [k,n0] of Object.entries(wizard.matrix)){let n=+n0||0;if(!n)continue;let [kind,id,cloId]=k.split(':'),pool=wizard.sets.questions.filter(q=>q.clo_id===cloId&&!used.has(q.id)&&(kind==='t'?q.topic_id===id:(q.chapter_id===id&&wizard.topics.has(q.topic_id))));for(let i=pool.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}let part=pool.slice(0,n);part.forEach(q=>used.add(q.id));out.push(...part)}return out}
function poolRow(examId,qx){let ch=wizard.sets.chapters.find(x=>x.id===qx.chapter_id),tp=wizard.sets.topics.find(x=>x.id===qx.topic_id),clo=wizard.sets.clos.find(x=>x.id===qx.clo_id);return {exam_id:examId,question_id:qx.id,chapter_id:qx.chapter_id,chapter_name:ch?.name||null,topic_id:qx.topic_id,topic_name:tp?.name||null,clo_id:qx.clo_id,clo_code:clo?.code||null,content:qx.content,correct_answer:qx.correct_answer,explanation:qx.explanation||null,options:(qx.question_options||[]).map(o=>({key:o.option_key,content:o.content}))}}
async function insertExam(row){let r=await db.from('exams').insert(row).select().single();if(!r.error)return {exam:r.data,gradeColumn:true};let m=String(r.error?.message||'');if(!/counts_toward_grade/i.test(m))throw r.error;let copy={...row};delete copy.counts_toward_grade;r=await db.from('exams').insert(copy).select().single();if(r.error)throw r.error;return {exam:r.data,gradeColumn:false}}
async function createTest(btn){btn.disabled=true;btn.textContent='Đang tạo bản nháp…';let exam=null;try{let total=totalMatrix(),picked=pickQuestions();if(picked.length!==total)throw new Error('Không rút đủ số câu theo ma trận');let s=wizard.settings,ct=cloTotals(),row={subject_id:state.subjectId,title:s.title,description:s.description||null,exam_type:'chapter_test',is_clo_assessment:false,total_questions:total,duration_minutes:+s.duration_minutes,max_attempts:+s.max_attempts,question_mode:s.question_mode,score_policy:s.score_policy,opens_at:iso(s.opens_at),closes_at:iso(s.closes_at),show_answers:s.show_answers,shuffle_questions:s.shuffle_questions,shuffle_options:s.shuffle_options,allow_ai_feedback:s.allow_ai_feedback,counts_toward_grade:s.counts_toward_grade,status:'draft',chapter_ids:[...wizard.chapters],topic_ids:[...wizard.topics],clo_counts:Object.fromEntries(wizard.sets.clos.map(c=>[c.code,ct[c.id]||0]).filter(([,n])=>n>0)),created_by:state.user.id};let ins=await insertExam(row);exam=ins.exam;let pool=wizard.sets.questions.filter(q=>wizard.chapters.has(q.chapter_id)&&wizard.topics.has(q.topic_id));let r=await db.from('exam_question_pool').insert(pool.map(q=>poolRow(exam.id,q)));if(r.error)throw r.error;r=await db.from('exam_questions').insert(picked.map((q,i)=>({exam_id:exam.id,question_id:q.id,question_order:i+1})));if(r.error)throw r.error;let chRows=[...wizard.chapters].map(id=>({exam_id:exam.id,chapter_id:id,question_count:picked.filter(q=>q.chapter_id===id).length})).filter(x=>x.question_count>0);if(chRows.length){r=await db.from('exam_chapters').insert(chRows);if(r.error)throw r.error}let cloRows=wizard.sets.clos.map(c=>({exam_id:exam.id,clo_id:c.id,weight:(ct[c.id]||0)*100/total})).filter(x=>x.weight>0);if(cloRows.length){r=await db.from('exam_clos').insert(cloRows);if(r.error)throw r.error}closeModal();if(!ins.gradeColumn)toast('Đã tạo bài. Supabase chưa có cột counts_toward_grade nên tùy chọn tính CLO chưa được lưu.',true);else toast(`Đã tạo bản nháp ${total} câu`);await window.AICLO_EXAM_BUILDER?.open?.('chapter_test',exam.id)}catch(ex){if(exam?.id){await db.from('exam_questions').delete().eq('exam_id',exam.id);await db.from('exam_question_pool').delete().eq('exam_id',exam.id);await db.from('exam_chapters').delete().eq('exam_id',exam.id);await db.from('exam_clos').delete().eq('exam_id',exam.id);await db.from('exams').delete().eq('id',exam.id)}err(ex);btn.disabled=false;btn.textContent='Tạo bản nháp và rút câu →'}}
function finalMatrixRows(){let out=[];if(wizard.structureMode==='topic_clo'){for(let [k,n] of Object.entries(wizard.matrix)){let [kind,id,clo]=k.split(':');if(kind==='t'&&+n)out.push({chapter_id:wizard.sets.topics.find(t=>t.id===id)?.chapter_id,topic_id:id,clo_id:clo,count:+n})}}else for(let [k,n] of Object.entries(wizard.matrix)){let [kind,id,clo]=k.split(':');if(kind==='c'&&+n)out.push({chapter_id:id,topic_ids:selectedTopics(id).map(t=>t.id),clo_id:clo,count:+n})}return out}
async function createFinalDraft(btn){btn.disabled=true;try{let s=wizard.settings,total=totalMatrix(),user=state.user?.id||'user',subject=state.subjectId||'subject',builderKey=`aiclo:v118:builder:${user}:${subject}:final_exam:new`,legacyKey=`ai-clo:v103:final-draft:${user}:${subject}`,builder={type:'final_exam',examId:null,settings:{title:s.title,description:s.description,total_questions:total,duration_minutes:s.duration_minutes,exam_date:s.exam_date,exam_session:s.exam_session,semester:s.semester,school_year:s.school_year,variant_count:s.variant_count},selectedChapters:[...wizard.chapters],selectedTopics:[...wizard.topics],structureMode:wizard.structureMode,matrix:wizard.matrix,collapsed:{info:false,structure:false,questions:false,export:false},updated_at:Date.now()},legacy={metadata:{title:s.title,description:s.description,duration_minutes:s.duration_minutes,exam_date:s.exam_date,exam_session:s.exam_session,semester:s.semester,school_year:s.school_year,variant_count:s.variant_count,source_scope:'secure_exam',builder_mode:wizard.structureMode,selected_chapters:[...wizard.chapters],selected_topics:[...wizard.topics],draft_stage:'matrix'},matrix:finalMatrixRows(),source:'secure_exam',selected:[],variants:[],stage:'matrix',package_id:null,local_updated_at:new Date().toISOString()};localStorage.setItem(builderKey,JSON.stringify(builder));localStorage.setItem(legacyKey,JSON.stringify(legacy));closeModal();toast('Đã tạo bản nháp đề thi cuối kỳ từ Ngân hàng đề thi – bảo mật');await window.AICLO_EXAM_BUILDER?.open?.('final_exam')}catch(ex){err(ex);btn.disabled=false;btn.textContent='Tạo bản nháp đề thi →'}}
async function start(kind='test'){try{injectCss();let normalized=kind==='final'?'final':'test',sets=await loadSets(normalized);if(!sets.chapters.length||!sets.clos.length)return toast('Học phần cần có Chương và CLO trước khi tạo bài',true);if(!sets.questions.length)return toast(normalized==='final'?'Ngân hàng đề thi – bảo mật chưa có câu hỏi hợp lệ':'Ngân hàng luyện tập – kiểm tra chưa có câu hỏi hợp lệ',true);wizard=defaults(normalized,sets);renderStep()}catch(ex){err(ex)}}
window.AICLO_CREATE_WIZARD=Object.freeze({version:VERSION,start});
})();