/* AI-CLO PTITHCM V11.9.1 — 4-step create wizard for chapter tests. */
(()=>{
'use strict';
const VERSION='11.9.1';
let installed=false, wizard=null;
const $=s=>document.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>window.esc?window.esc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sw=(name,text,val)=>`<label class="aiclo-switch-row"><span>${text}</span><span class="aiclo-switch"><input type="checkbox" name="${name}" ${val?'checked':''}><i></i></span></label>`;
const iso=v=>v?new Date(v).toISOString():null;
const totalMatrix=()=>Object.values(wizard?.matrix||{}).reduce((s,n)=>s+(+n||0),0);
const cell=(topicId,cloId)=>`t:${topicId}:${cloId}`;
function injectCss(){if(document.querySelector('link[data-aiclo-create-wizard]'))return;let l=document.createElement('link');l.rel='stylesheet';l.href='css/exams/create-wizard.css?v=11.9.1';l.dataset.aicloCreateWizard='1';document.head.appendChild(l)}
async function loadSets(){
 const [chapters,clos]=await Promise.all([
  q('chapters','*',x=>contentFilter(x).order('order_index')),
  q('clos','*',x=>contentFilter(x).order('code'))
 ]);
 const ids=chapters.map(x=>x.id);
 const topics=ids.length?await q('topics','*',x=>x.in('chapter_id',ids).order('order_index')):[];
 let questions=await q('questions','id,subject_id,display_code,question_bank_id,chapter_id,topic_id,clo_id,content,correct_answer,explanation,status,question_scope,approval_status,question_options(id,option_key,content)',x=>contentFilter(x).eq('status','active').eq('approval_status','approved'));
 questions=questions.filter(x=>{let ks=(x.question_options||[]).map(o=>String(o.option_key||'').toUpperCase());return ['practice','both'].includes(x.question_scope)&&ks.length===4&&new Set(ks).size===4&&['A','B','C','D'].every(k=>ks.includes(k))});
 return {chapters,topics,clos,questions};
}
function defaultWizard(sets){return {step:1,sets,settings:{title:'',description:'',duration_minutes:30,max_attempts:1,question_mode:'common_fixed',score_policy:'highest',opens_at:'',closes_at:'',show_answers:false,shuffle_questions:true,shuffle_options:true,allow_ai_feedback:true,status:'draft'},chapterId:'',topics:new Set(),matrix:{}}}
function openWindow(){let d=$('#modal');if(window.AICLO_APP_WINDOW?.open)window.AICLO_APP_WINDOW.open(d,{className:'assessment-window-modal aiclo-create-wizard-modal',width:900,height:690});else d.classList.add('quick-edit-modal','assessment-window-modal','aiclo-create-wizard-modal')}
function modalOpen(title,html){modal(title,html);openWindow()}
function footer(final=false){return `<div class="aiclo-wizard-footer"><button id="cwBack" type="button" class="secondary" ${wizard.step===1?'disabled':''}>← Quay lại</button><span class="aiclo-wizard-step">Bước ${wizard.step}/4</span><button id="cwNext" type="button" class="${final?'primary':'primary'}">${final?'Tạo bản nháp và rút câu':'Tiếp tục →'}</button></div>`}
function bindFooter(){let back=$('#cwBack'),next=$('#cwNext');if(back)back.onclick=()=>{if(wizard.step>1){captureCurrent();wizard.step--;renderStep()}};if(next)next.onclick=async()=>{if(!validateStep())return;if(wizard.step<4){captureCurrent();wizard.step++;renderStep()}else await createDraftAndDraw(next)}}
function captureCurrent(){let f=$('#cwForm');if(!f)return;if(wizard.step===1){let v=Object.fromEntries(new FormData(f));wizard.settings={...wizard.settings,title:(v.title||'').trim(),description:(v.description||'').trim(),duration_minutes:Math.max(1,+v.duration_minutes||30),max_attempts:Math.max(1,+v.max_attempts||1),question_mode:v.question_mode||'common_fixed',score_policy:v.score_policy||'highest',opens_at:v.opens_at||'',closes_at:v.closes_at||'',show_answers:!!f.show_answers?.checked,shuffle_questions:!!f.shuffle_questions?.checked,shuffle_options:!!f.shuffle_options?.checked,allow_ai_feedback:!!f.allow_ai_feedback?.checked}}
 if(wizard.step===2){let ch=f.querySelector('[name="chapter_id"]:checked');wizard.chapterId=ch?.value||wizard.chapterId;wizard.topics=new Set($$('[data-cw-topic]:checked',f).map(x=>x.value));pruneMatrix()}
 if(wizard.step===3){$$('.cw-matrix-input',f).forEach(i=>wizard.matrix[i.dataset.key]=+i.value||0)}
}
function validateStep(){captureCurrent();if(wizard.step===1){let s=wizard.settings;if(!s.title)return toast('Hãy nhập tên bài kiểm tra',true),false;if(s.opens_at&&s.closes_at&&new Date(s.closes_at)<=new Date(s.opens_at))return toast('Thời gian đóng phải sau thời gian mở',true),false;return true}if(wizard.step===2){if(!wizard.chapterId)return toast('Hãy chọn một chương',true),false;if(!wizard.topics.size)return toast('Hãy chọn ít nhất một mục',true),false;return true}if(wizard.step===3){let n=totalMatrix();if(n<1)return toast('Ma trận cần ít nhất một câu',true),false;for(let [k,v] of Object.entries(wizard.matrix)){let [,topicId,cloId]=k.split(':'),have=availability(topicId,cloId);if(+v>have)return toast(`Một ô cần ${v} nhưng chỉ có ${have} câu`,true),false}return true}return true}
function pruneMatrix(){let allowed=new Set([...wizard.topics].flatMap(t=>wizard.sets.clos.map(c=>cell(t,c.id))));for(let k of Object.keys(wizard.matrix))if(!allowed.has(k))delete wizard.matrix[k]}
function availability(topicId,cloId){return wizard.sets.questions.filter(q=>q.topic_id===topicId&&q.clo_id===cloId).length}
function renderStep(){if(!wizard)return;injectCss();let s=wizard.settings;if(wizard.step===1){modalOpen('AI-CLO | Tạo bài kiểm tra · Thông tin',`<form id="cwForm" class="aiclo-wizard-form"><div class="aiclo-wizard-head"><b>1. Thông tin bài</b><span>Nhập các thiết lập cơ bản. Tổng số câu sẽ được tính từ ma trận ở Bước 3.</span></div><label class="field wide">Tên bài<input name="title" required value="${esc(s.title)}"></label><label class="field wide">Mô tả<textarea name="description" rows="2">${esc(s.description)}</textarea></label><label class="field">Thời gian (phút)<input name="duration_minutes" type="number" min="1" max="300" value="${s.duration_minutes}"></label><label class="field">Số lần được làm<input name="max_attempts" type="number" min="1" max="100" value="${s.max_attempts}"></label><label class="field">Cách ghi nhận<select name="score_policy"><option value="highest" ${s.score_policy==='highest'?'selected':''}>Điểm cao nhất</option><option value="latest" ${s.score_policy==='latest'?'selected':''}>Lần cuối</option><option value="average" ${s.score_policy==='average'?'selected':''}>Trung bình</option></select></label><label class="field">Cách rút câu<select name="question_mode"><option value="common_fixed" ${s.question_mode==='common_fixed'?'selected':''}>Đề chung cố định</option><option value="student_fixed" ${s.question_mode==='student_fixed'?'selected':''}>Đề riêng cố định theo sinh viên</option><option value="attempt_random" ${s.question_mode==='attempt_random'?'selected':''}>Rút lại ở mỗi lần làm</option></select></label><label class="field">Mở từ<input name="opens_at" type="datetime-local" value="${esc(s.opens_at)}"></label><label class="field">Đóng lúc<input name="closes_at" type="datetime-local" value="${esc(s.closes_at)}"></label><div class="wide clo-switch-grid">${sw('show_answers','Cho xem đáp án/lời giải sau khi nộp',s.show_answers)}${sw('shuffle_questions','Trộn thứ tự câu hỏi',s.shuffle_questions)}${sw('shuffle_options','Trộn thứ tự phương án A–D',s.shuffle_options)}${sw('allow_ai_feedback','Cho phép sinh viên nhận xét AI',s.allow_ai_feedback)}</div>${footer(false)}</form>`)}
 else if(wizard.step===2){let chapters=wizard.sets.chapters;modalOpen('AI-CLO | Tạo bài kiểm tra · Phạm vi',`<form id="cwForm" class="aiclo-wizard-form"><div class="aiclo-wizard-head"><b>2. Phạm vi nội dung</b><span>Kiểm tra 1 chương: chọn đúng một chương và các mục được phép dùng.</span></div><div class="aiclo-chapter-choice wide">${chapters.map(ch=>{let checked=wizard.chapterId===ch.id,topics=wizard.sets.topics.filter(t=>t.chapter_id===ch.id);return `<article class="${checked?'selected':''}"><label><input type="radio" name="chapter_id" value="${ch.id}" ${checked?'checked':''}> <b>${esc(ch.order_index)}. ${esc(ch.name)}</b></label><div class="aiclo-topic-choice" ${checked?'':'hidden'}>${topics.map(tp=>`<label><input type="checkbox" data-cw-topic value="${tp.id}" ${wizard.topics.has(tp.id)?'checked':''}> ${esc(tp.name)}</label>`).join('')||'<span class="hint">Chương này chưa có mục.</span>'}</div></article>`}).join('')}</div>${footer(false)}</form>`);let f=$('#cwForm');$$('[name="chapter_id"]',f).forEach(r=>r.onchange=()=>{wizard.chapterId=r.value;wizard.topics=new Set(wizard.sets.topics.filter(t=>t.chapter_id===r.value).map(t=>t.id));pruneMatrix();renderStep()})}
 else if(wizard.step===3){modalOpen('AI-CLO | Tạo bài kiểm tra · Ma trận',`<form id="cwForm" class="aiclo-wizard-form"><div class="aiclo-wizard-head"><b>3. Ma trận câu hỏi</b><span>Nhập số câu theo từng Mục × CLO. Tổng số câu được tính tự động.</span></div><div class="wide aiclo-wizard-matrix">${matrixHtml()}</div>${footer(false)}</form>`);bindMatrixInputs()}
 else{let ch=wizard.sets.chapters.find(x=>x.id===wizard.chapterId),topicNames=wizard.sets.topics.filter(x=>wizard.topics.has(x.id)).map(x=>x.name),ct=cloTotals();modalOpen('AI-CLO | Tạo bài kiểm tra · Xác nhận',`<form id="cwForm" class="aiclo-wizard-form"><div class="aiclo-wizard-head"><b>4. Xác nhận</b><span>Kiểm tra lại trước khi tạo bản nháp và rút câu.</span></div><div class="aiclo-wizard-review wide"><div><b>Tên bài</b><span>${esc(s.title)}</span></div><div><b>Chương</b><span>${esc(ch?.name||'—')}</span></div><div><b>Các mục</b><span>${esc(topicNames.join(', ')||'—')}</span></div><div><b>Tổng số câu</b><span>${totalMatrix()} câu</span></div><div><b>Phân bố CLO</b><span>${wizard.sets.clos.map(c=>`${esc(c.code)}: ${ct[c.id]||0}`).join(' · ')}</span></div><div><b>Thời gian</b><span>${s.duration_minutes} phút · ${s.max_attempts} lượt</span></div><div><b>AI sinh viên</b><span>${s.allow_ai_feedback?'Bật':'Tắt'}</span></div></div>${footer(true)}</form>`)}bindFooter()}
function matrixHtml(){let topics=wizard.sets.topics.filter(t=>wizard.topics.has(t.id));let total=totalMatrix();return `<div class="table-wrap"><table class="exam-matrix cw-matrix"><thead><tr><th>Mục</th>${wizard.sets.clos.map(c=>`<th>${esc(c.code)}</th>`).join('')}<th>Tổng</th></tr></thead><tbody>${topics.map(tp=>`<tr data-cw-row="${tp.id}"><td><b>${esc(tp.name)}</b></td>${wizard.sets.clos.map(c=>{let k=cell(tp.id,c.id),n=availability(tp.id,c.id);return `<td><div class="clo-matrix-cell"><input class="cw-matrix-input" type="number" min="0" max="${n}" value="${wizard.matrix[k]||0}" data-key="${k}" data-topic="${tp.id}" data-clo="${c.id}"><span>(${n})</span></div></td>`}).join('')}<td><b data-cw-row-total="${tp.id}">0</b></td></tr>`).join('')}<tr class="matrix-grand"><td><b>TỔNG</b></td>${wizard.sets.clos.map(c=>`<td><b data-cw-clo-total="${c.id}">0</b></td>`).join('')}<td><b id="cwGrandTotal">${total}</b></td></tr></tbody></table></div><div class="ub-matrix-status ok">Tổng số câu của bài: <b id="cwTotalLabel">${total}</b></div>`}
function bindMatrixInputs(){let f=$('#cwForm');if(!f)return;$$('.cw-matrix-input',f).forEach(i=>i.oninput=()=>{let max=+i.max||0,v=Math.max(0,Math.min(max,+i.value||0));i.value=v;wizard.matrix[i.dataset.key]=v;updateMatrixTotals()});updateMatrixTotals()}
function updateMatrixTotals(){let f=$('#cwForm');if(!f)return;let topics=wizard.sets.topics.filter(t=>wizard.topics.has(t.id));for(let tp of topics){let n=wizard.sets.clos.reduce((s,c)=>s+(+wizard.matrix[cell(tp.id,c.id)]||0),0),el=f.querySelector(`[data-cw-row-total="${tp.id}"]`);if(el)el.textContent=n}for(let c of wizard.sets.clos){let n=topics.reduce((s,tp)=>s+(+wizard.matrix[cell(tp.id,c.id)]||0),0),el=f.querySelector(`[data-cw-clo-total="${c.id}"]`);if(el)el.textContent=n}let total=totalMatrix();let g=$('#cwGrandTotal'),l=$('#cwTotalLabel');if(g)g.textContent=total;if(l)l.textContent=total}
function cloTotals(){let out={};for(let c of wizard.sets.clos)out[c.id]=0;for(let [k,n] of Object.entries(wizard.matrix)){let cloId=k.split(':')[2];out[cloId]=(out[cloId]||0)+(+n||0)}return out}
function pickQuestions(){let out=[],used=new Set();for(let [k,n0] of Object.entries(wizard.matrix)){let n=+n0||0;if(!n)continue;let [,topicId,cloId]=k.split(':'),pool=wizard.sets.questions.filter(q=>q.topic_id===topicId&&q.clo_id===cloId&&!used.has(q.id));for(let i=pool.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}let part=pool.slice(0,n);part.forEach(x=>used.add(x.id));out.push(...part)}return out}
function poolRow(examId,qx){let ch=wizard.sets.chapters.find(x=>x.id===qx.chapter_id),tp=wizard.sets.topics.find(x=>x.id===qx.topic_id),clo=wizard.sets.clos.find(x=>x.id===qx.clo_id);return {exam_id:examId,question_id:qx.id,chapter_id:qx.chapter_id,chapter_name:ch?.name||null,topic_id:qx.topic_id,topic_name:tp?.name||null,clo_id:qx.clo_id,clo_code:clo?.code||null,content:qx.content,correct_answer:qx.correct_answer,explanation:qx.explanation||null,options:(qx.question_options||[]).map(o=>({key:o.option_key,content:o.content}))}}
async function createDraftAndDraw(button){captureCurrent();if(!validateStep())return;let total=totalMatrix(),selected=pickQuestions();if(selected.length!==total)return toast('Không rút đủ số câu theo ma trận',true);button.disabled=true;button.textContent='Đang tạo…';let examId=null;try{let s=wizard.settings,ct=cloTotals(),cloCounts=Object.fromEntries(wizard.sets.clos.map(c=>[c.code,ct[c.id]||0]).filter(([,n])=>n>0)),payload={subject_id:state.subjectId,created_by:state.user.id,title:s.title,description:s.description||null,exam_type:'chapter_test',is_clo_assessment:false,total_questions:total,duration_minutes:s.duration_minutes,max_attempts:s.max_attempts,score_policy:s.score_policy,show_answers:s.show_answers,shuffle_questions:s.shuffle_questions,shuffle_options:s.shuffle_options,opens_at:iso(s.opens_at),closes_at:iso(s.closes_at),allow_ai_feedback:s.allow_ai_feedback,question_mode:s.question_mode,chapter_ids:[wizard.chapterId],topic_ids:[...wizard.topics],clo_counts:cloCounts,status:'draft'};let r=await db.from('exams').insert(payload).select().single();if(r.error)throw r.error;examId=r.data.id;if(selected.length){r=await db.from('exam_questions').insert(selected.map((q,i)=>({exam_id:examId,question_id:q.id,question_order:i+1})));if(r.error)throw r.error}let pool=wizard.sets.questions.filter(q=>q.chapter_id===wizard.chapterId&&wizard.topics.has(q.topic_id));if(pool.length){r=await db.from('exam_question_pool').insert(pool.map(q=>poolRow(examId,q)));if(r.error)throw r.error}r=await db.from('exam_chapters').insert({exam_id:examId,chapter_id:wizard.chapterId,question_count:selected.length});if(r.error)throw r.error;let rows=wizard.sets.clos.map(c=>({exam_id:examId,clo_id:c.id,weight:(ct[c.id]||0)*100/Math.max(1,total)})).filter(x=>x.weight>0);if(rows.length){r=await db.from('exam_clos').insert(rows);if(r.error)throw r.error}closeModal();let id=examId;wizard=null;await window.AICLO_EXAM_BUILDER.open('chapter_test',id);toast(`Đã tạo bản nháp và rút ${total} câu`)}catch(ex){if(examId){try{await db.from('exams').delete().eq('id',examId)}catch{}}button.disabled=false;button.textContent='Tạo bản nháp và rút câu';window.err?err(ex):toast(String(ex?.message||ex),true)}}
async function start(){try{injectCss();let sets=await loadSets();wizard=defaultWizard(sets);renderStep()}catch(ex){window.err?err(ex):toast(String(ex?.message||ex),true)}}
function install(){if(installed)return;let add=$('#addExam');if(!add)return;add.dataset.cwBound='1';add.onclick=start;installed=true}
function init(){install();let c=$('#content');if(c){let obs=new MutationObserver(()=>{if(!$('#addExam')){installed=false;return}if(!$('#addExam').dataset.cwBound){installed=false;install()}});obs.observe(c,{childList:true,subtree:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.AICLO_CREATE_WIZARD=Object.freeze({version:VERSION,start});
})();
