/* AI-CLO PTITHCM V12.2 — pure final-exam export utility.
   No UI ownership, observers or event handlers. Called only by assessment.js. */
(()=>{
'use strict';
const VERSION='12.2.0';
const xesc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const plain=s=>{const d=document.createElement('div');d.innerHTML=String(s??'').replace(/<br\s*\/?\s*>/gi,'\n');return (d.textContent||'').replace(/\u00a0/g,' ').trim()};
function docText(s){let t=plain(s);const greek={alpha:'α',beta:'β',gamma:'γ',delta:'δ',epsilon:'ε',theta:'θ',lambda:'λ',mu:'μ',pi:'π',rho:'ρ',sigma:'σ',phi:'φ',omega:'ω'};t=t.replace(/\$([^$]+)\$/g,'$1').replace(/\\mathbb\{R\}/g,'ℝ').replace(/\\mathbb\{C\}/g,'ℂ').replace(/\\infty/g,'∞').replace(/\\leq?/g,'≤').replace(/\\geq?/g,'≥').replace(/\\neq/g,'≠').replace(/\\in(?![a-z])/g,'∈').replace(/\\to/g,'→').replace(/\\cdot/g,'·').replace(/\\times/g,'×').replace(/\\pm/g,'±');for(const [k,v] of Object.entries(greek))t=t.replace(new RegExp('\\\\'+k+'(?![a-zA-Z])','g'),v);t=t.replace(/\\frac\{([^{}]+)\}\{([^{}]+)\}/g,'($1)/($2)').replace(/\\sqrt\{([^{}]+)\}/g,'√($1)').replace(/\\begin\{[pbvBV]?matrix\}/g,'(').replace(/\\end\{[pbvBV]?matrix\}/g,')').replace(/\\\\/g,'; ').replace(/\s*&\s*/g,', ').replace(/\\[a-zA-Z]+\s*/g,'').replace(/[{}]/g,'');return t.replace(/\s+/g,' ').trim()}
const fmt=(n,d=2)=>{n=Number(n)||0;return n.toFixed(d).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1').replace('.',',')};
const viDate=s=>{const m=String(s||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(s||'')};
const safe=s=>String(s||'de-thi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'de-thi';
function download(data,name,type='application/octet-stream'){const blob=data instanceof Blob?data:new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function run(t,{bold=false,italic=false,size=24}={}){return `<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="Times New Roman"/><w:sz w:val="${size}"/><w:szCs w:val="${size}"/>${bold?'<w:b/><w:bCs/>':''}${italic?'<w:i/><w:iCs/>':''}</w:rPr><w:t xml:space="preserve">${xesc(t)}</w:t></w:r>`}
function pRuns(rs,{align='left',before=0,after=0,keep=false}={}){return `<w:p><w:pPr><w:jc w:val="${align}"/><w:spacing w:before="${before}" w:after="${after}" w:line="276" w:lineRule="auto"/>${keep?'<w:keepNext/>':''}</w:pPr>${rs.map(x=>run(x.t,x)).join('')}</w:p>`}
const p=(t,o={})=>pRuns([{t:docText(t),bold:!!o.bold,italic:!!o.italic,size:o.size||24}],o);
function cell(body,{width=0,align='center',bold=false,span=1}={}){const content=Array.isArray(body)?body.join(''):String(body||'').startsWith('<w:p')?body:p(body,{align,bold});return `<w:tc><w:tcPr>${width?`<w:tcW w:w="${width}" w:type="dxa"/>`:''}${span>1?`<w:gridSpan w:val="${span}"/>`:''}<w:vAlign w:val="center"/><w:tcMar><w:top w:w="70" w:type="dxa"/><w:left w:w="70" w:type="dxa"/><w:bottom w:w="70" w:type="dxa"/><w:right w:w="70" w:type="dxa"/></w:tcMar></w:tcPr>${content}</w:tc>`}
const row=(cells,header=false)=>`<w:tr><w:trPr>${header?'<w:tblHeader/>':''}<w:cantSplit/></w:trPr>${cells.join('')}</w:tr>`;
function table(rows,widths,borders=true){const edge=borders?'single':'nil',sz=borders?'6':'0';return `<w:tbl><w:tblPr><w:tblW w:w="${widths.reduce((a,b)=>a+b,0)}" w:type="dxa"/><w:jc w:val="center"/><w:tblLayout w:type="fixed"/><w:tblBorders>${['top','left','bottom','right','insideH','insideV'].map(x=>`<w:${x} w:val="${edge}" w:sz="${sz}" w:space="0" w:color="000000"/>`).join('')}</w:tblBorders></w:tblPr><w:tblGrid>${widths.map(w=>`<w:gridCol w:w="${w}"/>`).join('')}</w:tblGrid>${rows.join('')}</w:tbl>`}
function styles(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="Times New Roman"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style></w:styles>`}
function footer(code=''){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:p><w:pPr><w:jc w:val="right"/></w:pPr><w:r><w:t>${code?`Mã đề ${xesc(code)} · `:''}Trang </w:t></w:r><w:fldSimple w:instr="PAGE"><w:r><w:t>1</w:t></w:r></w:fldSimple><w:r><w:t>/</w:t></w:r><w:fldSimple w:instr="NUMPAGES"><w:r><w:t>1</w:t></w:r></w:fldSimple></w:p></w:ftr>`}
async function makeDocx(body,code=''){const JSZip=window.JSZip||await window.AICLO_OFFICE_LIBS?.zip?.();if(!JSZip)throw new Error('Không tải được JSZip');const z=new JSZip(),doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>${body}<w:sectPr><w:footerReference w:type="default" r:id="rId1"/><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="650" w:right="650" w:bottom="650" w:left="650" w:header="500" w:footer="500"/></w:sectPr></w:body></w:document>`;z.file('[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>`);z.folder('_rels').file('.rels',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`);z.folder('word').file('document.xml',doc).file('styles.xml',styles()).file('footer1.xml',footer(code));z.folder('word').folder('_rels').file('document.xml.rels',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);return z.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})}
function cloRows(ctx,questions){return ctx.sets.clos.map(c=>({c,qs:questions.filter(q=>q.clo_id===c.id)}))}
function bm06Body(ctx){const m=ctx.metadata,total=ctx.selected.length,point=total?10/total:0,out=[];out.push(p('Biểu mẫu BM06',{align:'right',bold:true}),p('MA TRẬN ĐỀ THI',{align:'center',bold:true,size:30,after:100}),pRuns([{t:'Tên học phần: ',bold:true},{t:ctx.subject?.name||''},{t:'     Học kỳ: ',bold:true},{t:m.semester||''},{t:'     Năm học: ',bold:true},{t:m.school_year||m.academic_year||''}],{after:40}),pRuns([{t:'Ngày thi: ',bold:true},{t:viDate(m.exam_date)},{t:'     Ca thi: ',bold:true},{t:m.exam_session||m.shift||''},{t:'     Thời gian: ',bold:true},{t:`${m.duration_minutes||80} phút`}],{after:80}));const widths=[2600,...ctx.sets.clos.map(()=>1400),1800],rows=[row([cell('Chương',{width:2600,bold:true}),...ctx.sets.clos.map(c=>cell(c.code,{width:1400,bold:true})),cell('Tổng',{width:1800,bold:true})],true)];for(const ch of ctx.sets.chapters){const qs=ctx.selected.filter(q=>q.chapter_id===ch.id);if(!qs.length)continue;rows.push(row([cell(`${ch.order_index}. ${ch.name}`,{width:2600}),...ctx.sets.clos.map(c=>{const n=qs.filter(q=>q.clo_id===c.id).length;return cell([p(`${n} câu`,{align:'center',bold:true}),p(`${fmt(n*point)} điểm`,{align:'center'}),p(`${fmt(total?n*100/total:0,1)}%`,{align:'center'})],{width:1400})}),cell([p(`${qs.length} câu`,{align:'center',bold:true}),p(`${fmt(qs.length*point)} điểm`,{align:'center'})],{width:1800})]))}rows.push(row([cell('TỔNG',{width:2600,bold:true}),...ctx.sets.clos.map(c=>{const n=ctx.selected.filter(q=>q.clo_id===c.id).length;return cell(`${n} câu · ${fmt(n*point)} điểm`,{width:1400,bold:true})}),cell(`${total} câu · 10 điểm`,{width:1800,bold:true})]));out.push(table(rows,widths),p('TRƯỞNG BỘ MÔN',{align:'right',bold:true,before:140}),p(m.head_of_department||'',{align:'right',bold:true,before:600}));return out.join('')}
function optionBody(q){return ['A','B','C','D'].map(k=>pRuns([{t:`${k}. `,bold:true},{t:docText(q.options?.[k]||'')}],{after:20})).join('')}
function bm07Body(ctx,v){const m=ctx.metadata,total=v.questions.length,point=total?10/total:0,out=[];out.push(p('Biểu mẫu BM07',{align:'right',bold:true}),p('HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG',{align:'center',bold:true}),p('CƠ SỞ TẠI THÀNH PHỐ HỒ CHÍ MINH',{align:'center',bold:true}),p('ĐỀ THI KẾT THÚC HỌC PHẦN',{align:'center',bold:true,size:30,after:80}),pRuns([{t:'Học phần: ',bold:true},{t:ctx.subject?.name||''},{t:'     Mã HP: ',bold:true},{t:m.course_code||''}],{after:30}),pRuns([{t:'Ngày thi: ',bold:true},{t:viDate(m.exam_date)},{t:'     Ca thi: ',bold:true},{t:m.exam_session||m.shift||''},{t:'     Thời gian: ',bold:true},{t:`${m.duration_minutes||80} phút`}],{after:30}),p(`Mã đề: ${v.code}`,{align:'center',bold:true,size:26,after:80}));v.questions.forEach((q,i)=>{out.push(pRuns([{t:`Câu ${i+1}. `,bold:true},{t:`(${q.clo_code||''}: ${fmt(point)}đ) `},{t:docText(q.content)}],{before:35,after:20,keep:true}),optionBody(q))});out.push(p('-- Hết --',{align:'center',bold:true,before:100}),p(`Ghi chú: ${m.exam_note||'Sinh viên không sử dụng tài liệu'}`,{after:60}),p('Họ tên SV:………………………………  Lớp:…………………  Ký tên:……………………',{after:100}),table([row([cell([p('TRƯỞNG BỘ MÔN',{align:'center',bold:true}),p(m.head_of_department||'',{align:'center',before:600})],{width:5100}),cell([p('GIẢNG VIÊN RA ĐỀ',{align:'center',bold:true}),p(m.lecturer||'',{align:'center',before:600})],{width:5100})])],[5100,5100],false));return out.join('')}
function bm08Body(ctx,v){const m=ctx.metadata,total=v.questions.length,point=total?10/total:0,out=[];out.push(p('Mẫu BM08',{align:'right',bold:true}),p(`ĐÁP ÁN / HƯỚNG DẪN CHẤM — MÃ ĐỀ ${v.code}`,{align:'center',bold:true,size:28,after:80}),pRuns([{t:'Học phần: ',bold:true},{t:ctx.subject?.name||''},{t:'     Mã HP: ',bold:true},{t:m.course_code||''}],{after:30}),p('1. Đáp án & thang điểm',{bold:true,size:26,after:40}),p(`Mỗi câu ${fmt(point)} điểm.`,{after:30}));const aw=[900,...Array(Math.min(20,total||1)).fill(450)];for(let start=0;start<total;start+=20){const arr=v.questions.slice(start,start+20);out.push(table([row([cell('Câu',{width:900,bold:true}),...arr.map((q,j)=>cell(String(start+j+1),{width:450}))]),row([cell('Đáp án',{width:900,bold:true}),...arr.map(q=>cell(q.correct_answer,{width:450,bold:true}))])],[900,...arr.map(()=>450)]))}out.push(p('2. Phiếu chấm theo CLO',{bold:true,size:26,before:60,after:40}));const widths=[1000,3600,1900,1300,1300],rows=[row(['CLO','Nội dung đánh giá','Câu liên quan','Trọng số','Điểm tối đa'].map((x,i)=>cell(x,{width:widths[i],bold:true})),true)];for(const c of ctx.sets.clos){const nums=v.questions.map((q,i)=>q.clo_id===c.id?i+1:null).filter(Boolean),n=nums.length;rows.push(row([cell(c.code,{width:1000,bold:true}),cell(c.short_description||c.description||'',{width:3600}),cell(nums.join(', '),{width:1900}),cell(`${fmt(total?n*100/total:0,1)}%`,{width:1300}),cell(fmt(n*point),{width:1300})]))}out.push(table(rows,widths),p('Tổng điểm: ……/10',{align:'center',bold:true,before:60}));return out.join('')}
function texText(s){return String(s??'').replace(/([%&_#])/g,'\\$1')}
function texDoc(ctx,v){const m=ctx.metadata,total=v.questions.length,point=total?10/total:0;return `\\documentclass[12pt,a4paper]{article}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T5]{fontenc}\n\\usepackage[vietnamese]{babel}\n\\usepackage{amsmath,amssymb,geometry,enumitem,fancyhdr}\n\\geometry{margin=1.7cm}\n\\pagestyle{fancy}\\fancyhf{}\\fancyfoot[L]{Mã đề ${texText(v.code)}}\\fancyfoot[R]{Trang \\thepage}\n\\begin{document}\n\\begin{center}\\textbf{HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG}\\\\\\textbf{ĐỀ THI KẾT THÚC HỌC PHẦN}\\\\Mã đề: \\textbf{${texText(v.code)}}\\end{center}\n\\noindent Học phần: ${texText(ctx.subject?.name)} \\quad Ngày thi: ${texText(viDate(m.exam_date))} \\quad Thời gian: ${m.duration_minutes||80} phút\n${v.questions.map((q,i)=>`\\medskip\\noindent\\textbf{Câu ${i+1}.} (${texText(q.clo_code||'')}: ${fmt(point)}đ) ${q.content}\n${['A','B','C','D'].map(k=>`\\textbf{${k}.} ${q.options?.[k]||''}`).join('\\\\\n')}`).join('\n')}\n\\begin{center}-- Hết --\\end{center}\n\\end{document}`}
async function bm06(ctx){const blob=await makeDocx(bm06Body(ctx));download(blob,'BM06_Ma_tran_de_thi.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document')}
async function bm07(ctx,v){const blob=await makeDocx(bm07Body(ctx,v),v.code);download(blob,`BM07_De_${v.code}.docx`,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')}
async function bm08(ctx,v){const blob=await makeDocx(bm08Body(ctx,v));download(blob,`BM08_${v.code}.docx`,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')}
async function tex(ctx,v){download(texDoc(ctx,v),`BM07_De_${v.code}.tex`,'text/plain;charset=utf-8')}
async function answerBook(ctx){const XLSX=window.XLSX||await window.AICLO_OFFICE_LIBS?.xlsx?.();if(!XLSX)throw new Error('Không tải được XLSX');const codes=ctx.variants.map(v=>v.code),n=Math.max(0,...ctx.variants.map(v=>v.questions.length)),rows=[];for(let i=0;i<n;i++){const r={'Câu':i+1};for(const v of ctx.variants){const q=v.questions[i];r[v.code]=q?.correct_answer||'';r[`CLO_${v.code}`]=q?.clo_code||ctx.sets.clos.find(c=>c.id===q?.clo_id)?.code||''}rows.push(r)}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows,{header:['Câu',...codes.flatMap(c=>[c,`CLO_${c}`])]}),'Doc');const horizontal=[];for(const v of ctx.variants){const ans={'Mã đề':v.code},clo={'Mã đề':`${v.code}_CLO`};v.questions.forEach((q,i)=>{ans[`Câu ${i+1}`]=q.correct_answer;clo[`Câu ${i+1}`]=q.clo_code||ctx.sets.clos.find(c=>c.id===q.clo_id)?.code||''});horizontal.push(ans,clo)}XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(horizontal),'Ngang');return {XLSX,wb}}
async function answers(ctx){const {XLSX,wb}=await answerBook(ctx);XLSX.writeFile(wb,'Dap_an_CLO.xlsx')}
async function zip(ctx){const JSZip=window.JSZip||await window.AICLO_OFFICE_LIBS?.zip?.(),{XLSX,wb}=await answerBook(ctx);if(!JSZip)throw new Error('Không tải được JSZip');const z=new JSZip();z.file('BM06_Ma_tran_de_thi.docx',await (await makeDocx(bm06Body(ctx))).arrayBuffer());for(const v of ctx.variants){z.file(`BM07/BM07_De_${v.code}.docx`,await (await makeDocx(bm07Body(ctx,v),v.code)).arrayBuffer());z.file(`BM07_TeX/BM07_De_${v.code}.tex`,texDoc(ctx,v));z.file(`BM08/BM08_${v.code}.docx`,await (await makeDocx(bm08Body(ctx,v))).arrayBuffer())}z.file('Dap_an_CLO.xlsx',XLSX.write(wb,{bookType:'xlsx',type:'array'}));z.file('README.txt',`AI-CLO PTITHCM V12.2\nNguồn câu: Ngân hàng đề thi – bảo mật.\nHồ sơ gồm BM06, BM07, BM08, TeX và đáp án CLO.`);download(await z.generateAsync({type:'blob'}),`Ho-so-de-thi-${safe(ctx.subject?.name)}-${new Date().toISOString().slice(0,10)}.zip`)}
window.AICLO_FINAL_EXPORTS=Object.freeze({version:VERSION,bm06,bm07,bm08,tex,answers,zip});
})();