/* AI-CLO PTITHCM V12.3.5 — pure online assessment export utility. */
(()=>{
'use strict';
const VERSION='12.3.5';
const safe=s=>String(s||'de-kiem-tra').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'de-kiem-tra';
const plain=s=>{const d=document.createElement('div');d.innerHTML=String(s??'').replace(/<br\s*\/?\s*>/gi,'\n');return (d.textContent||'').replace(/\u00a0/g,' ').trim()};
function download(data,name,type='application/octet-stream'){const blob=data instanceof Blob?data:new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},700)}
function hash32(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hash32(seed);return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function shuffled(arr,seed){const out=[...arr],r=rng(seed);for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function normalizeOptions(q){const o=Array.isArray(q.options)?q.options:Object.entries(q.options||{}).map(([key,content])=>({key,content}));return o.map((x,i)=>({key:String(x.key||x.option_key||String.fromCharCode(65+i)).toUpperCase(),content:x.content||''}))}
function buildVariant(base,code,{shuffleQuestions=true,shuffleOptions=true}={}){let qs=base.map(q=>({...q,options:normalizeOptions(q)}));if(shuffleQuestions)qs=shuffled(qs,`${code}|questions`);qs=qs.map((q,i)=>{if(!shuffleOptions)return{...q,number:i+1};const original=normalizeOptions(q).map(x=>({...x,origKey:x.key}));const mixed=shuffled(original,`${code}|${q.question_id||q.id||i}|options`);const labels=['A','B','C','D'];const options=mixed.map((x,j)=>({key:labels[j]||String.fromCharCode(65+j),content:x.content,origKey:x.origKey}));const hit=options.find(x=>x.origKey===String(q.correct_answer||'').toUpperCase());return{...q,number:i+1,options,correct_answer:hit?.key||q.correct_answer}});return{code:String(code),questions:qs}}
function buildVariants(base,codes,opts){return(codes||[]).map(code=>buildVariant(base,code,opts))}
function texEscapePlain(s){return plain(s).replace(/([#%&_{}])/g,'\\$1').replace(/\^/g,'\\textasciicircum{}').replace(/~/g,'\\textasciitilde{}')}
function texText(s){const t=plain(s),parts=t.split(/(\$[^$]*\$|\\\([^]*?\\\)|\\\[[^]*?\\\])/g);return parts.map(x=>/^\$|^\\\(|^\\\[/.test(x)?x:texEscapePlain(x)).join('')}
function texForVariant(ctx,v){const exam=ctx.exam||{},sub=ctx.subject||{},now=new Date().toLocaleString('vi-VN');const lines=[];lines.push('\\documentclass[12pt,a4paper]{article}','\\usepackage[utf8]{inputenc}','\\usepackage[T5]{fontenc}','\\usepackage[vietnamese]{babel}','\\usepackage{amsmath,amssymb}','\\usepackage{geometry}','\\usepackage{enumitem}','\\usepackage{fancyhdr}','\\geometry{margin=1.6cm}','\\setlength{\\parindent}{0pt}','\\pagestyle{fancy}','\\fancyhf{}',`\\lfoot{${texEscapePlain(sub.name||'AI-CLO PTITHCM')}}`,`\\rfoot{Mã đề ${texEscapePlain(v.code)} -- Trang \\thepage}`,'\\begin{document}','\\begin{center}','{\\bfseries\\Large BÀI KIỂM TRA}\\\\[4pt]',`{\\bfseries ${texEscapePlain(exam.title||'Bài kiểm tra')}}`,`\\end{center}',`\\textbf{Học phần:} ${texEscapePlain(sub.name||'')}\\hfill \\textbf{Mã học phần:} ${texEscapePlain(sub.code||sub.subject_code||'')}\\\\`,`\\textbf{Mã đề:} '+texEscapePlain(v.code)+'\\hfill \\textbf{Thời gian:} '+texEscapePlain(exam.duration_minutes||'—')+' phút\\\\',`\\textbf{Mô tả:} ${texText(exam.description||'')}\\\\`,`\\textit{Xuất từ AI-CLO PTITHCM: ${texEscapePlain(now)}}`,`\\vspace{0.5em}`);
for(const q of v.questions){lines.push(`\\textbf{Câu ${q.number}.} \\textbf{[${texEscapePlain(q.clo_code||'—')}]}`+(q.display_code?` \\textit{(${texEscapePlain(q.display_code)})}`:'')+` ${texText(q.content||'')}`,'\\begin{enumerate}[label=\\Alph*.,leftmargin=1.8em,itemsep=1pt]');for(const o of q.options)lines.push(`\\item ${texText(o.content||'')}`);lines.push('\\end{enumerate}')}lines.push('\\end{document}');return lines.join('\n')}
async function workbookBuffer(ctx,variants,printRows=4){const ExcelJS=window.ExcelJS||await window.AICLO_OFFICE_LIBS?.exceljs?.();if(!ExcelJS)throw new Error('Không tải được ExcelJS');const wb=new ExcelJS.Workbook();wb.creator='AI-CLO PTITHCM';const font={name:'Times New Roman',size:12};const thin={style:'thin',color:{argb:'FF000000'}},border={top:thin,left:thin,bottom:thin,right:thin};
const ws=wb.addWorksheet('Dap_an');const headers=['Câu'];for(const v of variants)headers.push(v.code,'CLO');ws.addRow(headers);const n=Math.max(0,...variants.map(v=>v.questions.length));for(let i=0;i<n;i++){const row=[i+1];for(const v of variants){const q=v.questions[i];row.push(q?.correct_answer||'',q?.clo_code||'')}ws.addRow(row)}ws.eachRow(r=>r.eachCell(c=>{c.font=font;c.border=border;c.alignment={horizontal:'center',vertical:'middle'}}));ws.getRow(1).font={...font,bold:true};ws.views=[{state:'frozen',ySplit:1,xSplit:1}];ws.columns.forEach((c,i)=>c.width=i===0?8:12);ws.addTable({name:'BangDapAnCLO',ref:'A1',headerRow:true,style:{theme:'TableStyleMedium2',showRowStripes:false},columns:headers.map(name=>({name:String(name)})),rows:Array.from({length:n},(_,i)=>{const row=[i+1];for(const v of variants){const q=v.questions[i];row.push(q?.correct_answer||'',q?.clo_code||'')}return row})});
const info=wb.addWorksheet('Thong_tin');const pairs=[['THÔNG TIN BÀI KIỂM TRA',''],['Học phần',ctx.subject?.name||''],['Mã học phần',ctx.subject?.code||ctx.subject?.subject_code||''],['Tên bài kiểm tra',ctx.exam?.title||''],['Mô tả',ctx.exam?.description||''],['Thời gian',`${ctx.exam?.duration_minutes||'—'} phút`],['Số câu',variants[0]?.questions.length||0],['Số mã đề',variants.length],['Mã đề',variants.map(v=>v.code).join(', ')],['Ngày xuất',new Date().toLocaleString('vi-VN')]];pairs.forEach(x=>info.addRow(x));info.columns=[{width:24},{width:70}];info.eachRow((r,i)=>{r.eachCell(c=>{c.font={...font,bold:i===1||c.col===1};c.border=border;c.alignment={vertical:'middle',wrapText:true}})});info.mergeCells('A1:B1');info.getCell('A1').alignment={horizontal:'center'};
const pr=wb.addWorksheet('Ban_in');let rr=1;for(const v of variants){pr.mergeCells(rr,1,rr,Math.max(6,Math.ceil(v.questions.length/Math.max(1,+printRows))*2+1));const title=pr.getCell(rr,1);title.value=`MÃ ĐỀ ${v.code}`;title.font={...font,bold:true,size:13};title.alignment={horizontal:'center'};rr++;const seg=Math.ceil(v.questions.length/Math.max(1,+printRows));for(let block=0;block<Math.max(1,+printRows);block++){const part=v.questions.slice(block*seg,(block+1)*seg);if(!part.length)continue;const row1=['Câu'],row2=['ĐA'],row3=['CLO'];for(const q of part){row1.push(q.number);row2.push(q.correct_answer||'');row3.push(q.clo_code||'')}[row1,row2,row3].forEach(vals=>{const r=pr.getRow(rr++);vals.forEach((val,j)=>{const c=r.getCell(j+1);c.value=val;c.font={...font,bold:j===0};c.border=border;c.alignment={horizontal:'center',vertical:'middle'}})});rr++}rr++}pr.columns.forEach((c,i)=>c.width=i===0?7:6);pr.pageSetup={paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:0.25,right:0.25,top:0.4,bottom:0.4,header:0.2,footer:0.2}};pr.headerFooter={oddFooter:'Trang &P / &N'};return wb.xlsx.writeBuffer()}
async function downloadWorkbook(ctx,variants,printRows){const buf=await workbookBuffer(ctx,variants,printRows);download(new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`${safe(ctx.exam?.title)}-dap-an-CLO.xlsx`)}
async function downloadZip(ctx,variants,printRows){const JSZip=window.JSZip||await window.AICLO_OFFICE_LIBS?.zip?.();if(!JSZip)throw new Error('Không tải được JSZip');const z=new JSZip();for(const v of variants)z.file(`${safe(ctx.exam?.title)}-${safe(v.code)}.tex`,texForVariant(ctx,v));const buf=await workbookBuffer(ctx,variants,printRows);z.file(`${safe(ctx.exam?.title)}-dap-an-CLO.xlsx`,buf);z.file('README.txt','Gói xuất từ AI-CLO PTITHCM. File Excel gồm sheet Dap_an tương thích Chấm thi CLO, Thong_tin và Ban_in.');const blob=await z.generateAsync({type:'blob'});download(blob,`${safe(ctx.exam?.title)}-ma-de.zip`)}
window.AICLO_ONLINE_EXPORT=Object.freeze({VERSION,buildVariants,texForVariant,workbookBuffer,downloadWorkbook,downloadZip,download,safe});
})();
