/* AI-CLO PTITHCM V11.2 — independent question banks and course settings. */
(()=>{'use strict';
const legacy=window.subjectForm,code=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,24);
const load=()=>q('question_banks','id,name,code,description,source_subject_id,is_active',x=>x.order('name'));
async function hasHistory(id){const [a,b]=await Promise.all([db.from('exams').select('id',{count:'exact',head:true}).eq('subject_id',id),db.from('final_exam_packages').select('id',{count:'exact',head:true}).eq('subject_id',id)]);if(a.error)throw a.error;if(b.error&&!/does not exist|schema cache/i.test(b.error.message||''))throw b.error;return(a.count||0)+(b.count||0)>0}
async function open(s={}){
 if(role()!=='admin')return legacy?.(s);let banks;try{banks=await load()}catch(e){return err(e)}const selected=s.question_bank_id||banks[0]?.id||'__new__';
 modal(s.id?'Cài đặt học phần':'Tạo học phần',`<form id="subjectForm" class="form-grid"><label class="field wide">Tên học phần<input name="name" required value="${esc(s.name||'')}"></label><label class="field">Học kỳ<input name="semester" required value="${esc(s.semester||'Học kỳ 1')}"></label><label class="field">Năm học<input name="academic_year" required value="${esc(s.academic_year||'2026-2027')}"></label><label class="field">Ngày bắt đầu<input name="starts_on" type="date" value="${esc(s.starts_on||'')}"></label><label class="field">Ngày kết thúc<input name="ends_on" type="date" value="${esc(s.ends_on||'')}"></label><label class="field wide"><span>Ngân hàng câu hỏi sử dụng</span><select name="question_bank_id" id="subjectQuestionBank" required>${banks.map(b=>`<option value="${b.id}" ${b.id===selected?'selected':''}>${esc(b.name)} · ${esc(b.code)}</option>`).join('')}<option value="__new__" ${selected==='__new__'?'selected':''}>+ Tạo ngân hàng câu hỏi mới</option></select><small>Chương, Chủ đề, CLO và câu hỏi của ngân hàng đã chọn sẽ tự động xuất hiện trong học phần; dữ liệu không bị sao chép.</small></label><div id="newQuestionBankFields" class="wide form-grid hidden"><label class="field wide">Tên ngân hàng mới<input name="bank_name"></label><label class="field">Mã ngân hàng<input name="bank_code" maxlength="32"></label><label class="field">Nhóm môn<select name="bank_group"><option value="math">Toán</option><option value="physics">Vật lý</option><option value="philosophy">Triết học</option><option value="other">Khác</option></select></label><label class="field wide">Mô tả<input name="bank_description"></label></div><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary" id="saveSubjectV111">Lưu</button></div></form>`);
 const f=$('#subjectForm'),pick=$('#subjectQuestionBank'),fields=$('#newQuestionBankFields'),sync=()=>{const fresh=pick.value==='__new__';fields.classList.toggle('hidden',!fresh);f.elements.bank_name.required=fresh;f.elements.bank_code.required=fresh;if(fresh&&!f.elements.bank_name.value)f.elements.bank_name.value=`Ngân hàng ${f.elements.name.value.trim()}`;if(fresh&&!f.elements.bank_code.value)f.elements.bank_code.value=code(f.elements.name.value)||'NGAN_HANG_MOI'};pick.onchange=sync;f.elements.name.oninput=()=>{if(pick.value==='__new__'){f.elements.bank_name.value=`Ngân hàng ${f.elements.name.value.trim()}`;f.elements.bank_code.value=code(f.elements.name.value)||'NGAN_HANG_MOI'}};sync();
 f.onsubmit=async e=>{e.preventDefault();const btn=$('#saveSubjectV111'),v=Object.fromEntries(new FormData(f));btn.disabled=true;btn.textContent='Đang lưu…';let created=null;try{if(v.starts_on&&v.ends_on&&v.ends_on<v.starts_on)throw new Error('Ngày kết thúc phải bằng hoặc sau ngày bắt đầu.');let bank=v.question_bank_id;if(s.id&&bank!==s.question_bank_id&&await hasHistory(s.id))throw new Error('Học phần đã có bài kiểm tra hoặc đề thi cuối kỳ nên không thể đổi ngân hàng câu hỏi.');if(bank==='__new__'){const r=await db.from('question_banks').insert({name:v.bank_name.trim(),code:code(v.bank_code),discipline_group:v.bank_group||'other',description:v.bank_description.trim()||null,created_by:state.user.id}).select().single();if(r.error)throw r.error;created=r.data;bank=created.id}const row={name:v.name.trim(),semester:v.semester.trim(),academic_year:v.academic_year.trim(),starts_on:v.starts_on||null,ends_on:v.ends_on||null,question_bank_id:bank},r=s.id?await db.from('subjects').update(row).eq('id',s.id).select().single():await db.from('subjects').insert(row).select().single();if(r.error)throw r.error;if(created&&!created.source_subject_id){const u=await db.from('question_banks').update({source_subject_id:r.data.id,updated_at:new Date().toISOString()}).eq('id',created.id);if(u.error)throw u.error}closeModal();toast(s.id?'Đã cập nhật cài đặt học phần':'Đã tạo học phần và gán ngân hàng');await boot(state.user)}catch(error){if(created&&!s.id)await db.from('question_banks').delete().eq('id',created.id);err(error);btn.disabled=false;btn.textContent='Lưu'}};
}
window.subjectForm=open;window.AICLO_QUESTION_BANKS=Object.freeze({load,openSubjectForm:open});
})();
