/* AI-CLO PTITHCM V11.3 — Admin-only system question-bank management. */
(()=>{'use strict';
let currentBank=null,currentTab='all';
const labelOrigin=v=>({lecturer:'Giảng viên biên soạn',gemini:'Gemini hỗ trợ',academy:'Câu hỏi Học viện'}[v]||'Giảng viên biên soạn');
const labelScope=v=>v==='secure_exam'?'Đề thi – bảo mật':v==='both'?'Cả hai':'Luyện tập – kiểm tra';
const labelGroup=v=>({math:'Toán',physics:'Vật lý',philosophy:'Triết học',other:'Khác'}[v]||'Khác');
const bankCode=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,32);
const inTab=(q,tab)=>tab==='all'||tab==='practice'&&['practice','both'].includes(q.question_scope)||tab==='secure_exam'&&['secure_exam','both'].includes(q.question_scope);
const loadBanks=()=>q('question_banks','id,name,code,description,discipline_group,is_active',x=>x.order('name'));
async function bankStats(){const [banks,questions,chapters,topics,clos]=await Promise.all([loadBanks(),q('questions','id,question_bank_id,question_scope'),q('chapters','id,question_bank_id'),q('topics','id,question_bank_id'),q('clos','id,question_bank_id')]);return{banks,questions,chapters,topics,clos}}

async function list(c){
 currentBank=null;const data=await bankStats();
 c.innerHTML=`<div class="v113-bank-page"><div class="v109-workspace-head v114-compact-head"><div><small>QUẢN TRỊ HỆ THỐNG</small><h3>Ngân hàng câu hỏi</h3><p>Quản lý, kiểm tra và sao lưu ngân hàng độc lập.</p></div></div><div class="v113-bank-toolbar"><input id="v113BankSearch" placeholder="Tìm tên hoặc mã ngân hàng…"><select id="v114GroupFilter"><option value="all">Tất cả nhóm môn</option><option value="math">Toán</option><option value="physics">Vật lý</option><option value="philosophy">Triết học</option><option value="other">Khác</option></select><button id="v114AddBank" class="primary">+ Thêm ngân hàng</button></div><div id="v113BankList" class="v112-bank-grid"></div></div>`;
 const draw=()=>{const term=$('#v113BankSearch',c).value.trim().toLowerCase(),group=$('#v114GroupFilter',c).value,banks=data.banks.filter(b=>(group==='all'||b.discipline_group===group)&&(!term||`${b.name} ${b.code}`.toLowerCase().includes(term)));$('#v113BankList',c).innerHTML=banks.map(bank=>{const qs=data.questions.filter(x=>x.question_bank_id===bank.id),linked=state.subjects.filter(s=>s.question_bank_id===bank.id);return `<article class="v112-bank-card"><div><small>${esc(bank.code)}</small><span class="badge v114-group">${esc(labelGroup(bank.discipline_group))}</span><h4>${esc(bank.name)}</h4><p>${data.chapters.filter(x=>x.question_bank_id===bank.id).length} chương · ${data.topics.filter(x=>x.question_bank_id===bank.id).length} chủ đề · ${data.clos.filter(x=>x.question_bank_id===bank.id).length} CLO</p><p>${qs.length} câu hỏi · ${linked.length} học phần sử dụng</p><div><span class="badge green">${qs.filter(x=>['practice','both'].includes(x.question_scope)).length} luyện tập</span><span class="badge secure">🔒 ${qs.filter(x=>['secure_exam','both'].includes(x.question_scope)).length} bảo mật</span></div></div><div class="v112-bank-actions"><button class="secondary" data-v113-open="${bank.id}">Mở ngân hàng</button><button class="primary" data-v113-export="${bank.id}">↓ Tải Excel</button></div></article>`}).join('')||'<div class="empty"><b>Không có ngân hàng phù hợp</b><span>Thử từ khóa hoặc nhóm môn khác.</span></div>';$$('[data-v113-open]',c).forEach(b=>b.onclick=()=>detail(c,data.banks.find(x=>x.id===b.dataset.v113Open)));$$('[data-v113-export]',c).forEach(b=>b.onclick=()=>window.AICLO_QUESTION_EXPORT?.exportBank(data.banks.find(x=>x.id===b.dataset.v113Export),b))};
 $('#v113BankSearch',c).oninput=draw;$('#v114GroupFilter',c).onchange=draw;$('#v114AddBank',c).onclick=()=>newBank(c);draw();
}

function newBank(c){
 c.innerHTML=`<div class="v113-bank-page"><div class="v109-workspace-head v114-compact-head"><button id="v114BackBanks" class="secondary">← Danh sách ngân hàng</button><div><small>NGÂN HÀNG MỚI</small><h3>Thêm ngân hàng câu hỏi</h3><p>Tạo kho nội dung độc lập; sau đó gán ngân hàng cho học phần cần sử dụng.</p></div></div><section class="panel v114-bank-form"><form id="v114BankForm" class="form-grid"><label class="field wide">Tên ngân hàng<input name="name" required maxlength="160" placeholder="Ví dụ: Ngân hàng Đại số tuyến tính"></label><label class="field">Mã ngân hàng<input name="code" required maxlength="32" placeholder="DAI_SO_TUYEN_TINH"></label><label class="field">Nhóm môn<select name="discipline_group" required><option value="math">Toán</option><option value="physics">Vật lý</option><option value="philosophy">Triết học</option><option value="other">Khác</option></select></label><label class="field wide">Mô tả<textarea name="description" maxlength="500" placeholder="Mô tả ngắn phạm vi nội dung…"></textarea></label><label class="check wide"><input name="is_active" type="checkbox" checked> Đang hoạt động</label><div class="form-actions"><button type="button" id="v114CancelBank" class="secondary">Hủy</button><button class="primary">Tạo ngân hàng</button></div></form></section></div>`;
 const form=$('#v114BankForm',c),name=form.elements.name,code=form.elements.code;let auto=true;name.oninput=()=>{if(auto)code.value=bankCode(name.value)};code.oninput=()=>{auto=!code.value||code.value===bankCode(name.value)};$('#v114BackBanks',c).onclick=$('#v114CancelBank',c).onclick=()=>list(c);form.onsubmit=async e=>{e.preventDefault();const button=e.submitter,values=Object.fromEntries(new FormData(form));button.disabled=true;button.textContent='Đang tạo…';const {error}=await db.from('question_banks').insert({name:values.name.trim(),code:bankCode(values.code),discipline_group:values.discipline_group,description:values.description.trim()||null,is_active:values.is_active==='on',created_by:state.user.id});if(error){button.disabled=false;button.textContent='Tạo ngân hàng';return err(error)}toast('Đã tạo ngân hàng câu hỏi');list(c)};
}

async function detail(c,bank,targetQuestionId=null){
 if(!bank)return list(c);currentBank=bank;
 const [questions,chapters,topics,clos]=await Promise.all([q('questions','*,question_options(*)',x=>x.eq('question_bank_id',bank.id).order('created_at',{ascending:false})),q('chapters','*',x=>x.eq('question_bank_id',bank.id).order('order_index')),q('topics','*',x=>x.eq('question_bank_id',bank.id).order('order_index')),q('clos','*',x=>x.eq('question_bank_id',bank.id).order('code'))]);
 const profileIds=[...new Set(questions.map(x=>x.created_by).filter(Boolean))],profiles=profileIds.length?await q('profiles','id,full_name,email',x=>x.in('id',profileIds)):[],profileMap=new Map(profiles.map(x=>[x.id,x]));
 c.innerHTML=`<div class="v113-bank-page"><div class="v109-workspace-head"><button id="v113Back" class="secondary">← Danh sách ngân hàng</button><div><small>${esc(bank.code)}</small><h3>${esc(bank.name)}</h3><p>${chapters.length} chương · ${topics.length} chủ đề · ${clos.length} CLO · ${questions.length} câu hỏi</p></div><button id="v113Export" class="primary">↓ Tải Excel</button></div><div class="v113-linked"><b>Học phần sử dụng:</b> ${state.subjects.filter(s=>s.question_bank_id===bank.id).map(s=>`<span class="badge">${esc(s.name)} · ${esc(s.academic_year||'')}</span>`).join(' ')||'Chưa có'}</div><div class="v109-tabs v113-tabs"><button data-v113-tab="all">Tất cả</button><button data-v113-tab="practice">Luyện tập – kiểm tra</button><button data-v113-tab="secure_exam">🔒 Đề thi – bảo mật</button></div><div class="v113-question-toolbar"><input id="v113QuestionSearch" placeholder="Tìm theo mã hoặc nội dung câu hỏi…"><span id="v113QuestionCount" class="hint"></span></div><div class="panel table-wrap v113-question-table"><table><thead><tr><th>Mã</th><th>Nội dung</th><th>Chương · Chủ đề</th><th>Người nhập</th><th>Phân loại</th><th></th></tr></thead><tbody id="v113QuestionRows"></tbody></table></div></div>`;
 const draw=()=>{const term=$('#v113QuestionSearch',c).value.trim().toLowerCase(),items=questions.filter(x=>inTab(x,currentTab)&&(!term||x.content.toLowerCase().includes(term)||questionCode(x).includes(term)));$$('[data-v113-tab]',c).forEach(b=>b.classList.toggle('active',b.dataset.v113Tab===currentTab));$('#v113QuestionCount',c).textContent=`${items.length}/${questions.length} câu`;$('#v113QuestionRows',c).innerHTML=items.map(x=>{const creator=profileMap.get(x.created_by),chapter=chapters.find(v=>v.id===x.chapter_id),topic=topics.find(v=>v.id===x.topic_id);return `<tr><td><button class="question-code" data-v113-question="${x.id}">${questionCode(x)}</button><br><small>${esc(labelOrigin(x.origin_type))}</small></td><td><button class="question-summary" data-v113-question="${x.id}">${esc(x.content)}</button></td><td><b>${esc(chapter?.name||'—')}</b><br><small>${esc(topic?.name||'—')}</small></td><td>${esc(creator?.full_name||creator?.email||'Chưa xác định')}</td><td><span class="badge ${x.question_scope==='secure_exam'?'secure':''}">${esc(labelScope(x.question_scope))}</span>${x.is_official?'<br><span class="badge green">Câu Học viện</span>':''}</td><td><button data-v113-question="${x.id}">Quản lý</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">Không có câu hỏi phù hợp.</td></tr>';renderMath($('#v113QuestionRows',c))};
 $('#v113Back',c).onclick=()=>list(c);$('#v113Export',c).onclick=e=>window.AICLO_QUESTION_EXPORT?.exportBank(bank,e.currentTarget);$('#v113QuestionSearch',c).oninput=draw;$$('[data-v113-tab]',c).forEach(b=>b.onclick=()=>{currentTab=b.dataset.v113Tab;draw()});$('#v113QuestionRows',c).onclick=e=>{const b=e.target.closest('[data-v113-question]');if(b)openQuestion(questions.find(x=>x.id===b.dataset.v113Question),{bank,chapters,topics,clos,profileMap,c})};draw();
 if(targetQuestionId){const target=questions.find(x=>x.id===targetQuestionId);if(target)openQuestion(target,{bank,chapters,topics,clos,profileMap,c})}
}

function openQuestion(x,ctx){
 const options=Object.fromEntries((x.question_options||[]).map(o=>[o.option_key,o.content])),creator=ctx.profileMap.get(x.created_by),chapter=ctx.chapters.find(v=>v.id===x.chapter_id),topic=ctx.topics.find(v=>v.id===x.topic_id),clo=ctx.clos.find(v=>v.id===x.clo_id);
 openDrawer(`Câu ${questionCode(x)}`,`<div class="question-detail v113-question-detail"><div class="detail-meta"><span class="badge red">${esc(clo?.code||'—')}</span><span class="badge">${esc(chapter?.name||'—')}</span><span class="badge">${esc(topic?.name||'—')}</span>${x.is_official?'<span class="badge green">Câu Học viện</span>':''}</div><div class="question-audit"><div><small>Người nhập</small><b>${esc(creator?.full_name||creator?.email||'Chưa xác định')}</b></div><div><small>Nguồn</small><b>${esc(labelOrigin(x.origin_type))}</b></div></div><div class="detail-question">${esc(x.content)}</div><div class="detail-options">${['A','B','C','D'].map(k=>`<div class="${x.correct_answer===k?'correct':''}"><b>${k}</b><span>${esc(options[k]||'')}</span></div>`).join('')}</div><div class="detail-explanation"><b>Lời giải</b><p>${esc(x.explanation||'Chưa có lời giải.')}</p></div><section class="classification-box"><h4>Quản trị câu hỏi</h4><label class="field">Nhóm sử dụng<select id="v113Scope"><option value="practice">Luyện tập – kiểm tra</option><option value="secure_exam">Đề thi – bảo mật</option><option value="both">Cả hai</option></select></label><div class="v113-admin-actions"><button id="v113SaveScope" class="secondary">Đổi nhóm sử dụng</button><button id="v113RequestEdit" class="secondary">Gửi yêu cầu chỉnh sửa</button><button id="v113Delete" class="danger">Xóa / lưu trữ</button></div></section></div>`,root=>{
  $('#v113Scope',root).value=x.question_scope;$('#v113SaveScope',root).onclick=async()=>{const scope=$('#v113Scope',root).value;if(scope===x.question_scope)return toast('Câu hỏi đang ở nhóm này.');if(!await confirmAction('Đổi nhóm sử dụng',`Chuyển ${questionCode(x)} sang “${labelScope(scope)}”?`,{confirmLabel:'Chuyển'}))return;const archive=await db.rpc('archive_question_revision',{p_question_id:x.id});if(archive.error)return err(archive.error);const {error}=await db.from('questions').update({question_scope:scope,updated_at:new Date().toISOString()}).eq('id',x.id);if(error)return err(error);closeDrawer();toast('Đã đổi nhóm sử dụng');detail(ctx.c,ctx.bank)};
  $('#v113RequestEdit',root).onclick=()=>requestEdit(x,creator);
  $('#v113Delete',root).onclick=()=>removeOrArchive(x,ctx);
 },{wide:true,eyebrow:'QUẢN TRỊ NGÂN HÀNG'});renderMath($('#drawerBody'));
}

function requestEdit(x,creator){if(!x.created_by)return toast('Câu hỏi chưa xác định người nhập.',true);modal(`Yêu cầu chỉnh sửa · ${questionCode(x)}`,`<form id="v113RequestForm" class="form-grid"><p class="hint wide">Gửi đến <b>${esc(creator?.full_name||creator?.email||'người nhập câu')}</b>. Người nhận sẽ thấy thông báo dẫn đến câu hỏi này.</p><label class="field wide">Nội dung cần chỉnh<textarea name="message" required maxlength="1200" placeholder="Nêu rõ nội dung, đáp án hoặc lời giải cần kiểm tra…"></textarea></label><div class="form-actions"><button type="button" class="secondary" onclick="document.querySelector('#modal').close()">Hủy</button><button class="primary">Gửi yêu cầu</button></div></form>`);$('#v113RequestForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='Đang gửi…';const {error}=await db.rpc('admin_request_question_edit',{p_question_id:x.id,p_message:new FormData(e.target).get('message').trim()});if(error){button.disabled=false;button.textContent='Gửi yêu cầu';return err(error)}closeModal();closeDrawer();toast('Đã gửi yêu cầu đến người nhập câu')}}

async function removeOrArchive(x,ctx){
 const [examResult,attemptResult]=await Promise.all([db.from('exam_questions').select('question_id',{count:'exact',head:true}).eq('question_id',x.id),db.from('attempt_questions').select('question_id',{count:'exact',head:true}).eq('question_id',x.id)]);
 if(examResult.error||attemptResult.error)return err(new Error('Không kiểm tra được lịch sử sử dụng nên hệ thống chưa cho phép xóa câu.'));
 const used=(examResult.count||0)+(attemptResult.count||0)>0;
 if(used){
  if(!await confirmAction('Lưu trữ câu hỏi',`${questionCode(x)} đã được dùng trong đề hoặc bài làm nên không thể xóa hẳn. Chuyển câu sang Lưu trữ?`,{confirmLabel:'Lưu trữ',danger:true}))return;
  const {error}=await db.from('questions').update({approval_status:'archived',status:'draft',updated_at:new Date().toISOString()}).eq('id',x.id);if(error)return err(error);
 }else{
  if(!await confirmAction(x.is_official?'Xóa câu hỏi Học viện':'Xóa câu hỏi',`${questionCode(x)} chưa được sử dụng. Thao tác này xóa hẳn câu hỏi và các phương án.${x.is_official?' Đây là câu Học viện đã xác nhận.':''}`,{confirmLabel:'Xóa hẳn',danger:true}))return;
  if(x.is_official&&!await confirmAction('Xác nhận lần hai','Bạn chắc chắn muốn xóa câu hỏi Học viện đã xác nhận?',{confirmLabel:'Tôi chắc chắn xóa',danger:true}))return;
  const {error}=await db.from('questions').delete().eq('id',x.id);if(error)return err(error);
 }
 closeDrawer();toast(used?'Đã lưu trữ câu hỏi':'Đã xóa câu hỏi');detail(ctx.c,ctx.bank);
}

async function openTarget(questionId){if(role()!=='admin')return;const {data:qrow}=await db.from('questions').select('question_bank_id').eq('id',questionId).maybeSingle(),banks=await loadBanks(),bank=banks.find(x=>x.id===qrow?.question_bank_id);if(bank){state.space='system';state.view='questionBanks';v95RefreshShell();await detail($('#content'),bank,questionId)}}
window.systemQuestionBanks=list;window.AICLO_SYSTEM_BANKS=Object.freeze({list,openTarget});
})();
