/* AI-CLO PTITHCM V11.2 — system-wide account management. */
(() => {
'use strict';
const oldUsers=window.users,teacherRoles=['teacher','lecturer','giangvien'];
const roleText=r=>r==='admin'?'Admin':teacherRoles.includes(r)?'Giảng viên':'Sinh viên';
const recent=v=>{if(!v)return'Chưa từng đăng nhập';let s=Math.max(0,(Date.now()-new Date(v))/1000);if(s<90)return'Vừa xong';if(s<3600)return`${Math.floor(s/60)} phút trước`;if(s<86400)return`${Math.floor(s/3600)} giờ trước`;if(s<172800)return'Hôm qua';if(s<2592000)return`${Math.floor(s/86400)} ngày trước`;return new Date(v).toLocaleDateString('vi-VN')};
function heading(){ $('#pageTitle').textContent='Quản lý người dùng';$('#pageSub').textContent='Tạo tài khoản, phân quyền, khóa và quản lý người dùng toàn hệ thống' }
const back=()=>'<button type="button" class="secondary" id="userPageBack">← Quay lại danh sách người dùng</button>';

function createPage(c,onBack){
 heading();c.innerHTML=`<div class="user-subpage-head">${back()}<div><h3>Thêm tài khoản</h3><p>Tạo một tài khoản hoặc nhập đồng thời nhiều tài khoản từ CSV.</p></div></div><div class="user-create-tabs"><button class="active" data-create-tab="single">Tạo một tài khoản</button><button data-create-tab="csv">Nhập danh sách CSV</button></div><section class="panel user-create-panel" id="userCreateBody"></section>`;$('#userPageBack').onclick=onBack;
 const activate=t=>$$('[data-create-tab]',c).forEach(b=>b.classList.toggle('active',b.dataset.createTab===t));
 const single=()=>{activate('single');$('#userCreateBody').innerHTML=`<form id="inlineNewUser" class="form-grid user-inline-form"><label class="field wide">Họ và tên<input name="full_name" required></label><label class="field wide">Email đăng nhập<input name="email" type="email" required></label><label class="field">Vai trò<select name="role" id="inlineNewRole"><option value="teacher">Giảng viên</option><option value="student">Sinh viên</option></select></label><label class="field">MSSV<input name="mssv" id="inlineNewMssv" placeholder="Bắt buộc đối với sinh viên"></label><p class="hint wide">Tài khoản được tạo ở cấp hệ thống. Việc thêm vào học phần được thực hiện trong trang quản lý tài khoản hoặc Danh sách thành viên.</p><div class="form-actions"><button class="primary" id="inlineCreateUser">Tạo tài khoản</button></div></form>`;$('#inlineNewRole').onchange=e=>$('#inlineNewMssv').required=e.target.value==='student';$('#inlineNewUser').onsubmit=async e=>{e.preventDefault();let b=$('#inlineCreateUser'),v=Object.fromEntries(new FormData(e.target));b.disabled=true;b.textContent='Đang tạo…';try{showAccountResults(await createAccounts([{full_name:v.full_name.trim(),email:v.email.trim(),role:v.role,mssv:v.mssv.trim()||null}]))}catch(x){err(x);b.disabled=false;b.textContent='Tạo tài khoản'}}};
 const csv=()=>{activate('csv');$('#userCreateBody').innerHTML=`<form id="inlineCsvUsers" class="form-grid user-inline-form"><div class="csv-guide wide"><b>Cấu trúc CSV</b><code>full_name,email,role,mssv</code><span>Vai trò dùng <b>teacher</b> hoặc <b>student</b>. Tối đa 100 tài khoản mỗi lần.</span></div><label class="field wide">Chọn file CSV<input id="inlineCsvFile" type="file" accept=".csv,text/csv" required></label><div id="inlineCsvPreview" class="wide"></div><div class="form-actions"><button class="primary" id="inlineCsvSubmit">Tạo các tài khoản</button></div></form>`;let parsed=[];$('#inlineCsvFile').onchange=async e=>{try{parsed=parseCsv(await e.target.files[0].text());if(parsed.length>100)throw new Error('File có quá 100 người');$('#inlineCsvPreview').innerHTML=`<span class="badge green">Đã đọc ${parsed.length} tài khoản</span>`}catch(x){parsed=[];err(x)}};$('#inlineCsvUsers').onsubmit=async e=>{e.preventDefault();if(!parsed.length)return toast('Chưa có dữ liệu CSV hợp lệ',true);let b=$('#inlineCsvSubmit');b.disabled=true;b.textContent='Đang tạo…';try{showAccountResults(await createAccounts(parsed))}catch(x){err(x);b.disabled=false;b.textContent='Tạo các tài khoản'}}};
 $('[data-create-tab="single"]',c).onclick=single;$('[data-create-tab="csv"]',c).onclick=csv;single();
}

function managePage(c,p,members,onBack){
 heading();let joined=members.filter(m=>m.user_id===p.id).map(m=>({m,s:state.subjects.find(x=>x.id===m.subject_id)})).filter(x=>x.s);
 c.innerHTML=`<div class="user-subpage-head">${back()}<div><h3>Quản lý tài khoản</h3><p>Thông tin, học phần và quyền truy cập của người dùng.</p></div></div><section class="panel user-account-page"><div class="detail-identity"><div class="avatar">${esc((p.full_name||p.email||'?').trim()[0].toUpperCase())}</div><div><h3>${esc(p.full_name||'Chưa đặt tên')}</h3><p>${esc(p.email||'')}${p.mssv?` · ${esc(p.mssv)}`:''}</p><span class="badge ${p.role==='student'?'green':'red'}">${esc(roleText(p.role))}</span> <span class="badge ${p.is_active===false?'red':'green'}">${p.is_active===false?'Đã khóa':'Hoạt động'}</span></div></div><div class="user-account-actions"><button id="pageEditUser" class="secondary">Sửa thông tin</button><button id="pageResetPassword" class="secondary">Đặt lại mật khẩu</button>${p.role!=='admin'&&p.id!==state.user.id?`<button id="pageToggleLock" class="${p.is_active===false?'primary':'danger'}">${p.is_active===false?'Mở khóa':'Khóa tài khoản'}</button>`:''}</div><div id="pagePasswordResult"></div><div class="panel-head user-course-head"><div><h3>Học phần tham gia</h3><p class="hint">Một người dùng có thể tham gia nhiều học phần.</p></div><span class="badge">${p.role==='admin'?'Toàn hệ thống':joined.length+' học phần'}</span></div><div class="subject-memberships">${p.role==='admin'?'<div><b>Toàn hệ thống</b><small>Quản trị viên</small></div>':joined.map(x=>`<div><b>${esc(x.s.name)}</b><small>${esc(x.s.semester||'')} · ${esc(x.s.academic_year||'')} · ${esc(roleText(x.m.role))}</small></div>`).join('')||'<p class="hint">Chưa tham gia học phần nào.</p>'}</div></section>`;
 $('#userPageBack').onclick=onBack;$('#pageEditUser').onclick=()=>editUserForm(p);$('#pageResetPassword').onclick=async()=>{if(!await confirmAction('Đặt lại mật khẩu',`Đặt lại mật khẩu cho ${p.full_name}?`,{confirmLabel:'Đặt lại'}))return;try{let d=await invokeAdmin({action:'reset_password',user_id:p.id});$('#pagePasswordResult').innerHTML=`<div class="password-result"><b>Mật khẩu tạm mới</b><code>${esc(d.temporary_password)}</code><small>Hãy sao chép ngay. Mật khẩu này chỉ hiển thị một lần.</small></div>`}catch(x){err(x)}};$('#pageToggleLock')?.addEventListener('click',async()=>{let lock=p.is_active!==false;if(!await confirmAction(`${lock?'Khóa':'Mở khóa'} tài khoản`,`Xác nhận ${lock?'khóa':'mở khóa'} tài khoản ${p.full_name}?`,{confirmLabel:lock?'Khóa':'Mở khóa',danger:lock}))return;try{await invokeAdmin({action:lock?'ban':'unban',user_id:p.id});toast(lock?'Đã khóa tài khoản':'Đã mở khóa tài khoản');render()}catch(x){err(x)}});
}

window.users=async function(c){
 if(role()!=='admin')return oldUsers(c);heading();let [profiles,members]=await Promise.all([q('profiles','*',x=>x.order('full_name')),q('subject_members','*')]);
 const listPage=()=>{heading();c.innerHTML=`<div class="stats" id="userStats"></div><div class="user-system-toolbar"><input id="userSearch" placeholder="Tìm theo họ tên, email hoặc mã số…"><select id="userRole"><option value="all">Tất cả vai trò</option><option value="admin">Admin</option><option value="teacher">Giảng viên</option><option value="student">Sinh viên</option></select><select id="userStatus"><option value="all">Tất cả trạng thái</option><option value="active">Đang hoạt động</option><option value="locked">Đã khóa</option></select><button id="addAccountPage" class="primary">+ Thêm tài khoản</button></div><div class="panel table-wrap user-system-table"><table><thead><tr><th>Họ tên</th><th>Email / Mã số</th><th>Vai trò</th><th>Học phần</th><th>Đăng nhập gần nhất</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody id="userRows"></tbody></table></div>`;
  const match=(p,w)=>w==='all'||(w==='teacher'?teacherRoles.includes(p.role):p.role===w),draw=()=>{let s=$('#userSearch').value.trim().toLowerCase(),r=$('#userRole').value,st=$('#userStatus').value,rows=profiles.filter(p=>(!s||[p.full_name,p.email,p.mssv].some(v=>String(v||'').toLowerCase().includes(s)))&&match(p,r)&&(st==='all'||(st==='active'?p.is_active!==false:p.is_active===false)));$('#userStats').innerHTML=`<div class="stat"><small>Tổng tài khoản</small><b>${profiles.length}</b></div><div class="stat"><small>Giảng viên</small><b>${profiles.filter(p=>teacherRoles.includes(p.role)).length}</b></div><div class="stat"><small>Sinh viên</small><b>${profiles.filter(p=>p.role==='student').length}</b></div><div class="stat"><small>Admin</small><b>${profiles.filter(p=>p.role==='admin').length}</b></div><div class="stat"><small>Đã khóa</small><b>${profiles.filter(p=>p.is_active===false).length}</b></div>`;$('#userRows').innerHTML=rows.map(p=>{let n=new Set(members.filter(m=>m.user_id===p.id).map(m=>m.subject_id)).size,course=p.role==='admin'?'Toàn hệ thống':n?`${n} học phần`:'Chưa tham gia';return `<tr class="${p.is_active===false?'account-locked':''}"><td><b>${esc(p.full_name||'Chưa đặt tên')}</b>${p.id===state.user.id?' <span class="badge">Bạn</span>':''}</td><td>${esc(p.email||'—')}<br><small>${esc(p.mssv||'')}</small></td><td><span class="badge ${p.role==='student'?'green':'red'}">${esc(roleText(p.role))}</span></td><td><button class="user-course-count" data-manage-user="${p.id}">${esc(course)}</button></td><td>${esc(recent(p.last_login_at))}</td><td><span class="badge ${p.is_active===false?'red':'green'}">${p.is_active===false?'Đã khóa':'Hoạt động'}</span></td><td><button class="primary compact-manage" data-manage-user="${p.id}">Quản lý</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Không có tài khoản phù hợp.</td></tr>'};draw();$('#userSearch').oninput=draw;$('#userRole').onchange=draw;$('#userStatus').onchange=draw;$('#addAccountPage').onclick=()=>createPage(c,listPage);$('#userRows').onclick=e=>{let b=e.target.closest('[data-manage-user]'),p=b&&profiles.find(x=>x.id===b.dataset.manageUser);if(p)managePage(c,p,members,listPage)}};listPage();
};
window.AICLO_SYSTEM_USERS=Object.freeze({version:'11.2'});
})();
